{title:'Die gefährlichste MAFIA der WELT - Die NATO _ Dr.Daniele Ganser',data-video-id:'22mFeOo3G-s'},
{title:'12.5. 2015 - Pressekonferenz der Aussenminister John Kerry und Sergej Lawrow',data-video-id:'sZnnCoMAiEA'},
{title:'23. März - Begrüßung Alexis Tsipras vor dem Kanzleramt; Solidarität mit Syriza und Griechenland',data-video-id:'8DJUg1J5cBw'},
{title:'3 SAT Kulturzeit - Die Wahrheit über Geld (antikriegTV #2)',data-video-id:'KKj4RoPbKek'},
{title:'3sat ll Westlicher Qualitätsmedien-Kampagne gegen russische Propaganda',data-video-id:'lStWmR452uE'},
{title:'400 US-Söldner in der Ukraine - RT deutsch',data-video-id:'3djxDAlc4rA'},
{title:'65% der US-Amerikaner gegen Blockierung des Iran-Atomabkommens',data-video-id:'Gw1d5x2CujI'},
{title:'70. Jahrestag der Befreiung vom Faschismus - Russisches TV',data-video-id:'5k7ekAJw7xY'},
{title:'7 Punkte Friedensplan Putins ll Jetzt abgelehnt',data-video-id:'mHtejc6Izl0'},
{title:'9_11, Bin Laden und die US-Saudi Connection',data-video-id:'q0kAvaRfZZ0'},
{title:'911 COVER UP - Shepard Smith - Judge Napolitano - 28 pages',data-video-id:'x3-Uh4-cB-k'},
{title:'9_11 - Massive Zweifel der ersten Stunden ll ZDF am 11.9.2001',data-video-id:'EjXU6i3H2P4'},
{title:'9_11 Terror - Richard Gage 14. April in Berlin - 2200 Whistleblower fordern neue Untersuchung',data-video-id:'AR3wADMAFfo'},
{title:'9. Mai 2015 – 70. Jahrestag des Sieges über den deutschen Faschismus - Treptower Park Berlin',data-video-id:'RFOnLCAkHHA'},
{title:'9. Mai 2015 - Blumen am Ehrendenkmal in Berlin-Treptow',data-video-id:'F0aLINmBAwc'},
{title:'Activities of foreign secret services - Argentine President C. Fernández to the UN',data-video-id:'VeV512GQX-Y'},
{title:'Afghanische Aktivistin Malalai Joya - Chelsea Manning und Edward Snowden sind Helden',data-video-id:'_ttN2Ooj_nY'},
{title:'Aktham Suliman - Flüchtlingskrise Folge der US-Politik des Regimechange - Maybrit Illner',data-video-id:'60ddnAVkmBM'},
{title:'Aktienexperte Hellmeyer - Ukrainekonflikt deeskalieren! - n-tv Interview',data-video-id:'Yh0ZJPbzTIE'},
{title:'Aktion Feuerzauber - Das Celler Loch Part1',data-video-id:'u7kUZ6O2eEs'},
{title:'Aktion Feuerzauber - Das Celler Loch Part2',data-video-id:'c-_etUzCezU'},
{title:'Alan Goodmann - Left Forum - U.S. Wars of Aggression and Islamic Jihad',data-video-id:'0ic29GgSOTg'},
{title:'Albtraum Atommüll.(antikriegTV)',data-video-id:'t0Ec4d88qAA'},
{title:'Al Jazeera & Katar - Krieg gegen Syrien - A. Suliman, ehem. Jazeera Korrespondent',data-video-id:'D44GTe6fxxE'},
{title:'Allgemeine Erklärung der Menschenrechte',data-video-id:'d6uW5u6v9o8'},
{title:'Alpha Blondy - War is Illegal We want Peace in the World - 2015 Reggae Jam',data-video-id:'0_WQ3Kf2-7g'},
{title:'alte Version - „DER HERR DER DROHNEN Berliner Compagnie',data-video-id:'JWz3TcVQIwc'},
{title:'André Hahn, DIE LINKE - Straftaten durch V-Leute',data-video-id:'QGltGtv-Frw'},
{title:'Angela Merkel Marionette der USA ll Mathias Richling',data-video-id:'Gnrpfkq95r0'},
{title:'Angela Merkel verkündet das Christentum',data-video-id:'HWnzLeU2Mvo'},
{title:'An israelische Armee im Aida-Flüchtlingslager - Vergesst niemals was die Nazis euch angetan haben!',data-video-id:'xA7mzcckZlo'},
{title:'Annie Machon - European Parliament Committee - NSA Mass Surveillance of EU Citizens - Sept.30, 13',data-video-id:'yQLW5q20l6s'},
{title:'Anstalt Asylrechtsverschärfung 20.10.15 (antikriegTV)',data-video-id:'VB4BoCue5xc'},
{title:'Anstalt Aussenpolitik - Syrien, Assad und Regimechange 20.10.15',data-video-id:'JskxR_0X8rM'},
{title:'Anstalt - Flüchlingskrise 20.10.15 (antikriegTV)',data-video-id:'06TgSiC1eek'},
{title:'Antikriegs-Appell aus Kiew',data-video-id:'3mnl7VOeYhk'},
{title:'Antikriegsdemo Berlin 13. Dezember Friedenswinter 2014',data-video-id:'qzqpn_p3hOQ'},
{title:'Antikriegsdoku - Sir No Sir Trailer',data-video-id:'7Lil1nVk_Vk'},
{title:'Anti-Kriegs-Museum Berlin l antikriegTV',data-video-id:'iY8GtqtSzC8'},
{title:'Antikriegsnachrichten  - - -  Anti-War News - Frieden mit Russland',data-video-id:'sEdp363PASM'},
{title:'AntikriegTV - Antikriegsnachrichten - Umfassender informieren!',data-video-id:'qQNF2bj14IM'},
{title:'Antirussische Berichterstattung der deutschen Presse ll 29 August 2014',data-video-id:'YO_5i2fwqZ0'},
{title:'Antiwar USA - Widerstand _ Resistance (antikrieg.TV)',data-video-id:'DhZrb5ufRL8'},
{title:'ARD bestätigt Faschisten ll ZDF Claus Kleber lügt ll EU schweigt',data-video-id:'NhbdMr8KZo8'},
{title:'ARD Monitor - Geheimoperation Wasser, EU fördert Wasserprivatisierung',data-video-id:'JJvASlzH_Z0'},
{title:'ARD_NDR - Hetze gegen Russland getarnt als harmlose Karnevals-Satire',data-video-id:'TRB6HT3Jegg'},
{title:'ARD Panorama - Der Preis des deutschen Jobwunders (antikriegTV Kanal2)',data-video-id:'upcg00fkdws'},
{title:'ARD - Putin ist kein Partner er ist Gegner 11.11.14',data-video-id:'HNGU1flfDlM'},
{title:'ARD - Russische Sorge vor NATO-Osterweiterung berechtigt und legitim',data-video-id:'f_0t5JI3WCA'},
{title:'ARD Tageschau  NSA überwacht Deutschland   30 6 2013',data-video-id:'DPQkPb4SEDo'},
{title:'ARD Tagesschau   NSA bespietzelt EU    29 6 2013',data-video-id:'4-VjEJSbYkg'},
{title:'ARD-Team - Im Folterkeller der US-Soldaten - Irak 2004 (antikrieg.TV)',data-video-id:'Jas74InLGus'},
{title:'Argentine President C. Fernández - Who supports terrorists, Freedom Fighters, ISIS in Syria',data-video-id:'MZTWZC7uPwM'},
{title:'Armut hat viele Gesichter... Lisa Fitz',data-video-id:'y1Yl3JdXaNY'},
{title:'Armut in Deutschland politisch gewollt - Nationale Armutskonferenz Dez 2012',data-video-id:'NgKBRaguVM8'},
{title:'Armutsbericht - Kommentar von Markus Preiß, WDR',data-video-id:'MeG4kNQsUy8'},
{title:'ASYLRECHT - Kein Mensch ist illegal (antikriegTV)',data-video-id:'B36NQ67cOaU'},
{title:'„Asylverfahrensbeschleunigungsgesetz“ - Interview mit Judith Wiebke, Amnesty International',data-video-id:'q33Rfmwu3Ss'},
{title:'Attac fordert Moratorium für Zahlungen Griechenlands an IWF',data-video-id:'AD9lYGZoNrA'},
{title:'Aufforderung Kiews an Donetsk - Massenexodus Hunderttausender',data-video-id:'IHq4ukU9VNM'},
{title:'Aufklärung des NSU und die vielen V-Männer l Die Anstalt',data-video-id:'wBhsWGmyYqs'},
{title:'Aufschrei ohne Echo  -  NSA Skandal und die Deutschen 3sat',data-video-id:'cTWqaNqAZ5A'},
{title:'Aufstand gegen die Fleischmafia.',data-video-id:'BpPVBustP4E'},
{title:'Aunt Boston Marathon Suspect - Bombing Were Staged',data-video-id:'4ZteHUx1nrw'},
{title:'Auszüge ARD Monitor - NATO als Kriegstreiber in der Ukraine',data-video-id:'fELbgH2rrS8'},
{title:'Baghdad - Deformed Babies born due to Depleted Uranium munitions',data-video-id:'zbfFW02wNJY'},
{title:'Bankenlobby und die ungeloeste Bankenkrise - Frontal21 (antikriegTV)',data-video-id:'Z8bGvW4jLIQ'},
{title:'Barack Merkel Angela Obama',data-video-id:'52nubeKIAyQ'},
{title:'Baroness Ashton of Upholland',data-video-id:'k4UmJH3Zeo8'},
{title:'Bashar al Assad about Kobane and ISIS',data-video-id:'cdTem6AgX4M'},
{title:'BBC Bericht über die Nazis in der Ukraine',data-video-id:'V9sdpDMvcLI'},
{title:'Berlin 18.7.2015 - Protestveranstaltung - EURATOM Nein danke!',data-video-id:'A5Bv1VLwppE'},
{title:'Berlin - Ein Gedicht - Internationaler Anti-Chevron Tag - 21. Mai Brandenburger Tor',data-video-id:'zYCkY6xrhX8'},
{title:'Berliner KünstlerInnen gegen Krieg - 70 Jahre Befreiung von Auschwitz durch die Rote Armee',data-video-id:'M18-vvo4f14'},
{title:'Berlin - Free Chelsea Manning (Wikileaks Whistleblower) - Birthday 2014',data-video-id:'HUXgqzVQX6Q'},
{title:'Berlin - International #AntiChevron Day - May 21, 2015',data-video-id:'aC-VN3v2u44'},
{title:'Berlin - Solidaridad con Ecuador vs Chevrón - NO al Fraude electoral en Honduras',data-video-id:'8Wf1IWEzKuw'},
{title:'Beweis - Nato Osterweiterung wurde ausgeschlossen - Versprechen gebrochen',data-video-id:'RL2-nTV2UaE'},
{title:'Bilder tiefer Trauer aus Gorlovka in der Ostukraine - Westen unterstützt Kiews Kriegsverbrechen',data-video-id:'PVesuateTBE'},
{title:'Bill Moyers - Geheim-Regierung der USA',data-video-id:'3zlI5AtJxfM'},
{title:'Biokrieg für Frieden und Demokratie',data-video-id:'Dniyf-ytPJA'},
{title:'Bizarrer Auftritt - Präsident der EU-Kommission Juncker beim EU-Gipfel in Riga, Mai 2015',data-video-id:'s-InLkH6wNU'},
{title:'Blackrock Investment - Ungeheure Macht im Hintergrund',data-video-id:'Wj3zSf7x2hM'},
{title:'BND im Dienste der NSA (antikriegTV)',data-video-id:'vXuBTqbPivU'},
{title:'BND schnüffelt für NSA l Tom Strohschneider ND-Chefredakteur',data-video-id:'EINRj2HQRGw'},
{title:'BND-Skandal - Barometer steht auf Sturm _ nd-Chefredakteur Tom Strohschneider',data-video-id:'Zhu1xBj8jFM'},
{title:'Börsenexperte Dirk Müller - Griechenland verfügt über immense Gas- u. Ölvorkommen',data-video-id:'ki6_flYvMYQ'},
{title:'Börsenexperte Dirk Müller - NSA - BND - Zinswetten - TTIP - Deutsche Bank',data-video-id:'TtkVdWjB6DI'},
{title:'Börsenexperte Dirk Müller über die Ukrainekrise',data-video-id:'ma12K8My2Ec'},
{title:'Boston bombing - Fox TV - bomb sniffing dogs _ drill before explosions',data-video-id:'MUnLu2XHsHM'},
{title:'Boston Bombing Suspect  Father talks of Possible Inside Job',data-video-id:'BiRjsKT2xqU'},
{title:'Boston Bombing Suspects Aunt',data-video-id:'fGn2EgLjEus'},
{title:'Boston Bombing Suspects Aunt - Show Me the Evidence',data-video-id:'hvTEX87pi30'},
{title:'Boston Marathon Suspects Father - Bombing Were Staged TV Interview',data-video-id:'Q7oCWHBpJdk'},
{title:'Boston Police - 3rd Explosion at Library',data-video-id:'8AbF3l9yYjE'},
{title:'Brandon Bryant, ehemaliger Drohnen Pilot packt aus - Berlin',data-video-id:'e3dz63_u_ag'},
{title:'Braune Aussichten - Nazis rüsten sich für NSU-Prozess',data-video-id:'whqqrEBsrxc'},
{title:'Brief an Obama - Pascha Champ -  Wir sind für den Frieden!',data-video-id:'toS_uyUukl4'},
{title:'Brisante Enthüllungen im NSU-Prozess - Hessischer Verfassungsschutz zunehmend in Erklärungsnot',data-video-id:'VpilJRfCF0Y'},
{title:'BR Kontrovers - Trinkwasser in Gefahr, EU will Trinkwasser privatisieren',data-video-id:'vz3G6F0haRI'},
{title:'BR Quer - Strom autonom, Bürger treiben Energiewende an (antikriegTV Kanal2)',data-video-id:'SdfC8M0_JhU'},
{title:'Bundesjustizministerium - Rechte Vergangenheit frontal21  7.05.13',data-video-id:'JlFEPq5D8UM'},
{title:'Bundeskanzlerin Merkel war glühende Jungkommunistin -  antikriegTV2',data-video-id:'FP95NXxrL6s'},
{title:'Bundesnachrichtendienst BND und Waffentransporte - Monitor April 2015',data-video-id:'Z6em9JsN_HM'},
{title:'Bundesregierung wußte von Totalüberwachung der NSA',data-video-id:'KTNgbcO4LQM'},
{title:'Bundeswehr Einsatz ab 2012 im Inneren',data-video-id:'kFx8ZFr_OPU'},
{title:'Bundeswehreinsatz Syrien - Jürgen Todenhöfer (Phoenix)',data-video-id:'_KCWZLMA1Ig'},
{title:'Bundeswehreinsatz zur Vernichtung syrischer Chemiewaffen',data-video-id:'yc-55Pfz_0g'},
{title:'Bundeswehr - Kein Krieg Song',data-video-id:'oVa0NEwVMA0'},
{title:'Bush-Kriege _ Obama-Kriege _ Süchtig nach Krieg',data-video-id:'sLOrr7nNwJ4'},
{title:'Carl Rove Heckled on Iraq War 21.4.13',data-video-id:'JgEUak89uJc'},
{title:'Charlie Hebdo Journalist - One attackers had blue eyes',data-video-id:'G7GBZYRYnwc'},
{title:'Chelsea Manning Happy Birthday 2014',data-video-id:'nTahQz1kGBw'},
{title:'China - 6-stöckiges Haus in 24 Stundne',data-video-id:'X21zBDQQjQE'},
{title:'China und die neue Seidenstrasse',data-video-id:'pTJ7_GIHGq8'},
{title:'Chomsky on Intervention, Scahill Blasts Stanley McChrystal - The Struggle #508',data-video-id:'xs3MHPhc8ug'},
{title:'Christoph Sieber  Berlin wird  Putingrad',data-video-id:'9WJFIXYSV9k'},
{title:'Christoph Sieber - Das gönn ich euch (2012)',data-video-id:'u7A1TTjb0M8'},
{title:'Christoph Siebers - Klare und bewegende Worte',data-video-id:'f-lX_U7NmPc'},
{title:'CIA Black Operations in Iran',data-video-id:'EdA6tGmBHLw'},
{title:'Civil War in Ukraine  Interview with Vyacheslav Nikonov',data-video-id:'Qs7EJYIchvs'},
{title:'Clip _ Freundschaft China und Russland',data-video-id:'ZeCM1VlmLtg'},
{title:'CNN  Kein Anzeichen für Invasion Russlands - 2.9.14',data-video-id:'BQmeZzhNyoc'},
{title:'CODEPINK Protest während der Senatsanhörung zu ISIS 16.9.14',data-video-id:'IswjT3cXiMc'},
{title:'Condoleezza Rice -  Gas und Ölkrieg gegen Putin',data-video-id:'aF0uYIjaTNE'},
{title:'Coop Antikriegscafe Berlin - Friedensbewegung',data-video-id:'kzK478qG_es'},
{title:'COOP Antikriegscafe Berlin',data-video-id:'M7_Y_l2HgrI'},
{title:'Craig Roberts - EU ist Teil des US Imperiums ll Medien gesteuert',data-video-id:'7pmtfwE7jjk'},
{title:'CrossBorder-Leasing - Privatisierung Wasserwerke - Karusselgeschäft Banken - PPP',data-video-id:'aozuRWEY4pc'},
{title:'Damaskus, Syrien - Palästinensische Flüchtlingslager Jarmuk',data-video-id:'6cV26qmMB7A'},
{title:'Daniele Ganser - Ressourcenkriege Teil 1',data-video-id:'wMpH1X9uUeM'},
{title:'Daniele Ganser - Ressourcenkriege Teil 2',data-video-id:'DTQSSbU7rbg'},
{title:'Das britische Abhörprogramm #Tempora  # Prism',data-video-id:'w-xIaxe2LW0'},
{title:'Das Buch Ukraine im Visier auf der Leipziger Buchmesse',data-video-id:'HSfqyQNchxU'},
{title:'Das Celler Loch ist kein Einzelfall - NDR',data-video-id:'JVyzsTEiPeA'},
{title:'DAS IST UNSER HAUS Pitchvideo',data-video-id:'vqYSwV6qSpo'},
{title:'David Graeber   Occupy und die 99% - antikriegTV2',data-video-id:'70vAnFDzsF8'},
{title:'David Swanson - Left Forum - U.S. Wars of Aggression and Islamic Jihad',data-video-id:'9O0V7jAnNRY'},
{title:'Deformed Babies by use of US Uranium Weapons in Iraq DU - (NSFW)',data-video-id:'8en1FkCRajY'},
{title:'Demonstration gegen Sparpolitik in Italien - 18.5.2013',data-video-id:'CyttQtbMW7Q'},
{title:'Demonstration  in Kiew am 9.4. gegen Klitschko und die Stadtverwaltung',data-video-id:'_9emW1YArEY'},
{title:'Depleted Uranium - Birth defects in Fallujah (Guardian)',data-video-id:'F9wza2LYyj0'},
{title:'Depleted Uranium - Congressman McDermott HBO Interview - 21.4.13',data-video-id:'ZjXMBJDk4LE'},
{title:'Depleted Uranium - Effects in Iraq',data-video-id:'ownN8REg5yo'},
{title:'Der Fall Gustl Mollath -  Erwin Pelzig Neues aus der Anstalt ZDF',data-video-id:'z_gzV0rfgbI'},
{title:'„DER HERR DER DROHNEN Berliner Compagnie - Veranstaltung im Rahmen der Drohnen-Kampagne',data-video-id:'QqTkr3PhDP8'},
{title:'Der Krieg in Syrien - Gespräch mit Karin Leukefeld',data-video-id:'IEOuH_hd-SU'},
{title:'Der Krise ein Ende setzten_ Ein spanisches Dorf trotzt mit sozialistischen Maßnahmen der Krise',data-video-id:'zxC1bNBuOVs'},
{title:'Der Plan der USA, die Welt zu beherrschen - Teil 1 russ  Doku',data-video-id:'xuRcGFk-FPo'},
{title:'Der Plan zur Einkreisung Russlands - Die Welt als Schachbrett',data-video-id:'N9sONGYWci4'},
{title:'Der Weihnachtsfrieden von 1914',data-video-id:'c5s_xlqGTWg'},
{title:'[deutsch] CBS Interview mit Bashar al Assad, Präsident von Syrien',data-video-id:'J0CnGPebsmQ'},
{title:'Deutsche an die Front - Internationaler Frühschoppen 2.2.14',data-video-id:'BjAAtwHZusA'},
{title:'Deutsche-Bank - Geschaftsmodell Hunger - antikrieg TV',data-video-id:'V8_6Wz-QuZU'},
{title:'Deutsche Bank - Organisiertes Verbrechen  Teil 1  - antikriegTV2',data-video-id:'Cag00kAArIQ'},
{title:'Deutsche Bank   Organisiertes Verbrechen  - Teil 2 -  antikriegTV2',data-video-id:'3CVR0Tt9nho'},
{title:'Deutsche Interessen im Kampf um die Ukraine',data-video-id:'pZr_0wLISgQ'},
{title:'Deutsche Medien verharmlosen Faschisten in der Ukraine 25.9.14',data-video-id:'RkMtwPJcPJo'},
{title:'Deutscher Mainstream vs Russia Today',data-video-id:'JF1VLq7Tp98'},
{title:'Deutsches Fernsehen berichtet objektiver über Lage in Syrien 30.10.15',data-video-id:'L09J5kQflng'},
{title:'Deutschland braucht keine Killer-Drohnen - Jürgen Todenhöfer',data-video-id:'H_7dDi8yfsY'},
{title:'Deutschland - Direkte Beschuldigung Russlands MH17 abgeschossen zu haben',data-video-id:'wRVw3M3BxJ8'},
{title:'Deutschlands Weg in den Überwachungstaat - Professor Albrecht (antikriegTV)',data-video-id:'X5LHa6izPmI'},
{title:'Die Anstalt - April.2015 - Max Uthoff, Claus von Wagner, Christoph Sieber, Carolin Kebekus',data-video-id:'3_ZMZvEt91s'},
{title:'Die Anstalt erklärt die Lügen der Wirtschaftsweisen  12.12.14',data-video-id:'pGd3vGmcLl4'},
{title:'Die Anstalt - Herzblatt - Einsame Grossmächte und ihre Rebellen 20.10.15',data-video-id:'SHfBGfujizk'},
{title:'Die Anstalt l Griechenland, Banken, Troika, Journalisten',data-video-id:'REb7PBbOlBg'},
{title:'Die Anstalt - Solo Max Uthoff 20.10.15',data-video-id:'zn6-ei6yK4Q'},
{title:'Die Außenpolitik Russlands - S.E. W. M. Grinin, Russlands Botschafter in Deutschland l antikriegTV',data-video-id:'NfuLp0r1W28'},
{title:'Die deutsche Atombombe - Auerwerke Oranienburg Teil 1',data-video-id:'VFOx7UFKCoo'},
{title:'Die deutsche Atombombe - Auerwerke Oranienburg Teil 2',data-video-id:'Ha6GucCYRt4'},
{title:'Die EU ist eine Diktatur    Martin Schulz bei Maybrit Illner',data-video-id:'nrUy_JIO6Mg'},
{title:'Die geheimen Krieg der CIA - Im Auftrag der Regierung - mit William Blum • BRAVE NEW FILMS',data-video-id:'jJ4VcRaXPrg'},
{title:'Die Geheimverträge G10 zur Überwachung der Bevölkerung - Frontal21',data-video-id:'9dwvhC8tzVU'},
{title:'Diego Fusaro, ital. Philosoph -  Die Ursachen der Immigration',data-video-id:'WBaMPmpQUL8'},
{title:'Die graue Eminenz Joerg Asmussen - HG Butzko   Kleinkunstpreis',data-video-id:'49uYD17P8kw'},
{title:'Die Gründe für Krieg und Terror',data-video-id:'pxr4y22meEg'},
{title:'Die Hartz-Maschine - Geschäfte mit der Arbeitslosigkeit',data-video-id:'zMK6hZPyKVY'},
{title:'Die Internationale - Rosa-Luxemburg-Konferenz 2014',data-video-id:'XPcBQnqvGJ8'},
{title:'DIE LINKE - Bundestag 26.2.2011 -  Afghanistankrieg Abstimmung - antikriegTV2',data-video-id:'vemQGzNKu9A'},
{title:'Die Schweiz erlässt keine antirussische Sanktionen',data-video-id:'NWtAh9F4OFw'},
{title:'Dieser Kapitalismus geht über Leichen. Lucy Redler, Sozialökonomin',data-video-id:'YQsCs57yxkA'},
{title:'Die Spekulationswirtschaft mit mehr als € 500 Billionen',data-video-id:'c-U-vTbzqNY'},
{title:'Die Ukrainekrise bereits vor 15 Jahren angekündigt - RT',data-video-id:'QsW7yuJD1_U'},
{title:'Die (Un-)Abhängigkeit des Mario Draghi von G30',data-video-id:'xpj7Y2_UpEQ'},
{title:'Die USA scheinen die Ukraine zerfallen zu lassen - Rostislav Ischenko (Politologe)',data-video-id:'FFugeapN3hw'},
{title:'Die Verbrechen der USA im Nahen Osten ll ZDF Nichts neues in der Anstalt 23.9.14',data-video-id:'0nLK-nqvA80'},
{title:'Die Wahrheit über Osama Bin Laden und Al Qaida - antikriegTV2',data-video-id:'85KVyTS3Igs'},
{title:'Dirk Müller   Griechenland, Bodenschätze, Nachweise (antikrieg TV)',data-video-id:'HDjJlbyRf0g'},
{title:'Dirk Müller vs. Eric Frey ll US-Interessen in der Ukraine',data-video-id:'ux7sPm7DFWs'},
{title:'Drohnen-Terrorkampagne - Tod per Joystick',data-video-id:'aEyT3T0vYoE'},
{title:'Dr. Seltsams Wochenschau 7. Juli - H.C. Ströbele - Snowden - NSA - PRISM',data-video-id:'vDi27WwOaMc'},
{title:'Dr. Seltsams Wochenschau mit Menschenrechtsanwalt H.-Eberhard Schultz - 6.10.13',data-video-id:'KntnaBzLsIg'},
{title:'DU - The Silent Nuclear War - Depleted Uranium - Part One',data-video-id:'RhD_unMXgCU'},
{title:'DU - The Silent Nuclear War Depleted Uranium  Part Two',data-video-id:'jj41wKzPj6g'},
{title:'Earthships New Solutions Official Trailer',data-video-id:'IEAVJ_darZg'},
{title:'Easter Peace March Berlin 2014',data-video-id:'2hw-o7MPEuw'},
{title:'Ehemaliger NATO-Oberbefehlshaber enthüllt Pentagon-Kriegpläne',data-video-id:'1Vr_slBV6kI'},
{title:'Ehem. EU-Kommissar Verheugen - Fatale Fehler im Ukraine_Russland Konflikt ll nTV',data-video-id:'mXqpudI8qNw'},
{title:'Ehem. Wehrmachtsangehörige verteidigen Nazi-Deutschland',data-video-id:'h-NdFpt74nY'},
{title:'Eindrücke aus Donezk -  RIA Novosti-Korrespondent Armin Siebert',data-video-id:'r9RdfRLhqpU'},
{title:'Einreiseverbot für Grünen-Fraktionschefin im EU-Parlament, Rebecca Harms',data-video-id:'UAuL7w6jlko'},
{title:'Endlich berichtet das ZDF über zivile Opfer 14.7.14',data-video-id:'n-scwgfTeQk'},
{title:'Endstation Bad Kleinen - Versagen deutscher Sicherheitsorgane',data-video-id:'QyoSdaA-9Ro'},
{title:'Erdogans Propaganda - Nicht Russland sondern die Türkei kämpft gegen Islamischen Staat',data-video-id:'87zsQMP1egs'},
{title:'Erfolgreichste Talkshow der Ukraine - Wir können Putin nicht für alles verantwortlich machen!',data-video-id:'JhTeOQEXcUk'},
{title:'Ermächtigungsgesetze - Neues aus der Anstalt 6.4.13',data-video-id:'77VtaGdIU8U'},
{title:'Erwin Pelzig - Geheimverträge vs  Whistleblower ll 7 10 14 ZDF',data-video-id:'uDH5oFz1c4Y'},
{title:'Erwin Pelzig - Rasmussen, die lügende Hämorrhoide 9.9. 2014',data-video-id:'IRzRYAct9Sc'},
{title:'Erwin Pelzig über die Mitte der Gesellschaft - Weihnachts- und Neujahrsansprache',data-video-id:'G6z66j0GH0Q'},
{title:'Erwin Pelzig  Willkommen im Kriegswinter 2014 ll 9.9.14',data-video-id:'KeqjyNoWYRA'},
{title:'Eskalation Ukraine - US-Militär bereits vor Ort',data-video-id:'n181zzq_4FE'},
{title:'Eskalierende globale Ungerechtigkeit',data-video-id:'AcocTsxEftA'},
{title:'EU Commission head Junker - Relations with Russia ‘must be improved,’ US ‘can’t dictate’',data-video-id:'2svx1JiuDo0'},
{title:'EU entscheidet sich gegen Netzneutralität - kommt das Zweiklasseninternet',data-video-id:'OtJe419qMNs'},
{title:'EU-Kommissionspräsident Juncker - Man muss Russland anständig behandeln',data-video-id:'pZvjFtU5Csk'},
{title:'Euromaidan-Aktivisten feiern den Tod Putins vor der russischen Botschaft in Kiew',data-video-id:'luhAPi1uM3E'},
{title:'Ex-Bundesminister von Bülow - Brücke Berlin-Moskau',data-video-id:'WXhR0HWT92M'},
{title:'Ex-Jugoslavia - Depleted Uranium NATO Bombs',data-video-id:'31GQFj0bMFI'},
{title:'Ex-Minister Andreas von Bülow zur geopolitschen Lage',data-video-id:'RDJav3yNmQg'},
{title:'Ex-President Carter Regularly Speaks with Putin About Syria',data-video-id:'RVu92KJiZ_k'},
{title:'extra3 NDR ll Der Ami-Shooter - Globaler Krieg ll 17.9.2014',data-video-id:'Ncdtp_rm_Mg'},
{title:'Fakten zum Abschuss der russischen Su 24 durch die Türkei',data-video-id:'grEj8W8lhhs'},
{title:'Fallbeispiele Terrorismus Made in USA l antikriegTV',data-video-id:'eZBEfDDhGG8'},
{title:'Fälschung - Ukrainisches TV angeblicher Schwerverletzter - Tragödie von Wolnowacha',data-video-id:'Z2lLu_7O_rM'},
{title:'Fernsehkritik tv über Syrien Berichterstattung von ARD und ZDF (antikrieg TV)',data-video-id:'OB42o2QClyI'},
{title:'Flächenbrand Naher u. Mittlerer Osten.. #1 Gespräch mit Karin Leukefeld',data-video-id:'Ri0qdRaZZZM'},
{title:'Flüchtlingskrise massgeblich auch von Berlin verursacht – Unterfinanzierte Hilfsprogramme der UN',data-video-id:'d-dfNWZeTgc'},
{title:'Flüchtlingskrise u. die Verantwortung Deutschlands - Rechtsanwalt Dr. Matthias Lehnert (Sputnik)',data-video-id:'Ut4tWe65oa8'},
{title:'Flugzeugkatastrophe MH17 Ukraine - Christian Wehrschütz, Journalist, ORF',data-video-id:'tqBFfRfh47A'},
{title:'Fox Propaganda - Putin persönlich befahl Nemtsov-Ermordung. Säuberungen wie zur Stalin-Ära',data-video-id:'CHGXbCnpxE4'},
{title:'Free Bradley Manning - Collateral Murder - Wikileaks',data-video-id:'cNm3uVl6saU'},
{title:'Free Bradley Manning Protest während Obama-Rede am 22.8.2013',data-video-id:'ct1ArZeBkzs'},
{title:'Free Chelsea Manning Stop Watching Us Berlin - Diani Barreto 18.11. 2013',data-video-id:'ibw9uXESz-I'},
{title:'Free Mumia Rede von Jamal Hart - Rosa-Luxemburg-Konferenz 2014',data-video-id:'W3S9AqbfUyo'},
{title:'Freihandelsabkommen EU-USA - Neoliberale Globalisierung - Günther Sölken 17.8.13',data-video-id:'qjYCn3jQ60I'},
{title:'Freundschaft Schröder & Putin ll Deutschland & Russland',data-video-id:'b-HzxENWTx0'},
{title:'Frieden statt NATO – Für eine #Weltfriedenskonferenz #WorldPeaceConference',data-video-id:'GKpvs0jCOfs'},
{title:'Frontal21 -  Bankenlobby und die ungelöste Bankenkrise',data-video-id:'oDY9x7phgPg'},
{title:'Frontal 21 - Dschihadist und V-Mann zugleich .. Elmar Theveßen über SITE',data-video-id:'t2MEDrjjh3w'},
{title:'Frontal 21 - Dunkle Seiten von Justiz & Psychiatrie  Dez 2012',data-video-id:'3noDkGdoa6U'},
{title:'Frontal 21 - Totalüberwachung Deutschlands _ US-Firmen beteiligt 1.11.14',data-video-id:'BGHFcm4mDTk'},
{title:'Full Disclosure - Al-Qaeda in Syria, the Story You Havent Heard - Ben Swann',data-video-id:'MKfmiMVtKf8'},
{title:'G8 Gipfelstürmer - Die Blutigen Tagen von Genua.',data-video-id:'Zy1eUuCV4Fk'},
{title:'Gabriele Krone-Schmalz bei Maischberger und Russlandfeinden',data-video-id:'yevzUw_AO8Q'},
{title:'Gabriele Krone Schmalz ll Militarisierte Politik u. diffamierter Pazifismus',data-video-id:'BOIrE1UQBlE'},
{title:'Gabriele Krone Schmalz ll Über Russland und was guten Journalismus ausmacht ll Phoenix',data-video-id:'olBqyauqNYs'},
{title:'Gabriele Krone Schmalz - Verständnis für Russland haben',data-video-id:'hBDz0IgV_ko'},
{title:'Gebet des ukrainischen Nationalisten - Maidan Bataillon Gelöbnis',data-video-id:'6hClu3L7SAo'},
{title:'Gegen Krieg und Rassismus - Berlin Soundstrike Jam Session 26.6.15',data-video-id:'786Fwyf_1Xo'},
{title:'Geheime NATO Waffenlieferungen an IS über Bulgarien _ Türkei - Kurdische Meldungen aus Syrien',data-video-id:'7Pwi5SbR3c0'},
{title:'Geheime Partisanenarmee des BND (1von3) -- Schattenkrieger der Nato',data-video-id:'7BARnjo3e1E'},
{title:'Geheime Partisanenarmee des BND (Teil 2_3) -- Die Schattenkrieger der Nato',data-video-id:'xPkLu3udTcc'},
{title:'Geheime Partisanenarmee des BND (Teil 3_3) -- Die Schattenkrieger der Nato',data-video-id:'Xt1uityfE6E'},
{title:'Genscher - Verständnis für Putin, Schluss mit Sanktionen ll Phoenix 21.9.14',data-video-id:'85N-pH07-w4'},
{title:'Geopolitische Hintergründe der Ukraine Krise - Oberstleutnant a. D. Jochen Scholz l antikriegTV',data-video-id:'s80xIyE6fUA'},
{title:'George Friedman (Stratfor) - Die nächsten 100 Jahre',data-video-id:'68DnyBKOPWo'},
{title:'Georg Schramm - Fakten reden Klartext -  Neues aus der Anstalt (antikriegTV) 3.10.13',data-video-id:'oaXDM_8ii54'},
{title:'Georg Schramm - Iran',data-video-id:'ssKDxkRrTgA'},
{title:'Georg Schramm - Krieg Reich gegen Arm - Kleinkunstpreis 2013',data-video-id:'c5By3zLGoJ4'},
{title:'Georg Schramm - Systematische Volksverdummung durch die Medien',data-video-id:'X9uQiv4DCCs'},
{title:'German Minister Accuses Qatar of Funding ISIL - Germany later officially apologies to Quartar',data-video-id:'kRD1IFa1aP0'},
{title:'Germans to the Front - Deutsche Luftwaffe voll bewaffnet an russischer Grenze',data-video-id:'cHn8uLNhENs'},
{title:'German TV ll  Satire Show about warmongering Ukraine Media Coverage',data-video-id:'wf4fntYVvvY'},
{title:'Germany aids US spying on Europeans - Darnell Stephen Summers',data-video-id:'CvYZUJs8S8s'},
{title:'Geschäfte mit geächteten Waffen - Deutsche Rüstungsunternehmen und die Streumunition',data-video-id:'fclmhKIbXTY'},
{title:'Geschichte der Kriegslügen der US-Präsidenten',data-video-id:'W6DQc-pxWtU'},
{title:'Gesine Schwan über die Hetze gegen Griechenland  -  Monitor, Juli 2015',data-video-id:'q-koQEnL9vE'},
{title:'Gespenst der totalen Überwachung   ZDF heute Journal 7.8.13',data-video-id:'NHE3fP58Z-s'},
{title:'Gladio - Attentate unter falscher Flagge - Italien - antikriegTV2',data-video-id:'GGPZe7XX95A'},
{title:'GLADIO . Teil 1 (antikriegTV)',data-video-id:'SM5SYnVvPCY'},
{title:'Global Wave Kernwaffen abschaffen! Aktionen in Städten weltweit',data-video-id:'SzIxVnTbABg'},
{title:'Goldman Sachs in Griechenland (antikrieg TV)',data-video-id:'LC__Wt-Su_s'},
{title:'Goldman Sachs Verschwörung - Neues aus der Anstalt - antikriegTV2',data-video-id:'966DSq_mSNk'},
{title:'Goldpreis Manipulation',data-video-id:'w5oFhTzwueE'},
{title:'Gorbatschow - Kriegsgefahr! - Russland wird provoziert ll Schweizer Fernsehen 17.9.14',data-video-id:'D_m1EB9YsZY'},
{title:'Greenspans späte Einsicht (antikrieg TV)',data-video-id:'XijcVpdnn3Y'},
{title:'Gregor Gysi - 70 Jahre nach Ende des Nationalsozialismus',data-video-id:'IZ944dUkHhc'},
{title:'Gregor Gysi - Deuschlands Politik von aussen bestimmt',data-video-id:'mNicdDpsttk'},
{title:'Gregor Gysi - Flüchtlinge, Krieg und Hunger - Umdenken gefordert',data-video-id:'ZwzcQGYC-oQ'},
{title:'Gregor Gysi Sanktionen gegen Russland sind lächerlich',data-video-id:'MxQTV1gSrcQ'},
{title:'Gregor Gysi über die Ziehväter von ISIS, al-Nusra und al-Qaida',data-video-id:'Cu8lqVB16oM'},
{title:'Gregor Gysi zu Griechenland - Aschermittwoch',data-video-id:'b-tgNouEHGI'},
{title:'Griechen fordern Wiedergutmachung von Deutschland (antikriegTV)',data-video-id:'iKrXFUyCXq8'},
{title:'Griechenland am Vorabend einer Revolution in Europa',data-video-id:'naL9SAeJRKA'},
{title:'Griechenland - Bodenschätze , Erdgas, Erdöl - Mr. DAX - antikriegTV2',data-video-id:'9poJQsIMrag'},
{title:'Griechenland_ Der Hunger hält Einzug',data-video-id:'QahXnMhxUuY'},
{title:'Griechenlandkrise - Dirk Müller zu den neusten Entwicklungen',data-video-id:'k1rP4VqEVKY'},
{title:'Griechenlandpoker - Schäuble heimlich gefilmt - - Vorsicht! Man glaubt uns nicht',data-video-id:'DP76hiMFsuo'},
{title:'Griechenland - Widerstand gegen deutsche Besetzung (antikriegTV)',data-video-id:'Wua2kAI7o74'},
{title:'Group of Thirty G30 - Mario Draghi und Goldman Sachs - antikriegTV2',data-video-id:'s-hrFkv7in4'},
{title:'Grundlagen der US-Aussenpolitik - Michael Lüders, Politik- u. Islamwissenschaftler',data-video-id:'gOrWsKAqJSs'},
{title:'Günter Grass  - System zerstört sich selbst  - antikriegTV2',data-video-id:'JolW3YbX82E'},
{title:'Gustl Mollath und das Schwarzgeld',data-video-id:'Zmuk1QJfBXo'},
{title:'G.W.Bush zum Thema Folter und Renditions - antikriegTV2',data-video-id:'H9Ae-D7XTAw'},
{title:'Gysi - Völkerrechtswidriger US-Drohnenkrieg aus Ramstein organisiert',data-video-id:'eGEHdO-ZCT0'},
{title:'Hagen Rether - Krasser geht nicht ll Nordkorea und die USA ll 27.9.14',data-video-id:'pYf1XJl5wCA'},
{title:'Hagen Rether  über die USA',data-video-id:'A-E2mEsa-7g'},
{title:'Hand in Hand - Ukrainische Nazis, Poroschenko, Merkel, Obama, EU',data-video-id:'d7EA8POeeZM'},
{title:'Harald Lesch -- Zins_Zinseszins - Perfektes Verbrechen',data-video-id:'XrD_ewkJKHA'},
{title:'Harald Schmidt & Obama Bin Laden',data-video-id:'QYTSVwUNXR4'},
{title:'Hassausbruch in Kiew - Frau aus Lugansk wird als Lügnerin beschimpft',data-video-id:'007MVXVxtZo'},
{title:'Heereskommando Anti-Russland Propaganda ll ZDF Neues aus der Anstalt 23.9.14',data-video-id:'OlTtMPt8Jvg'},
{title:'Heiner Flassbeck - NEIN zum Neoliberalismus',data-video-id:'fEuvxNG41Zs'},
{title:'Heino Wiese (SPD) - «Russland – Menschen und Orte in einem fast unbekannten Land»',data-video-id:'osCUcKasyAU'},
{title:'Herbert Grönemeyer - ISIS ist Resultat westlicher Politik',data-video-id:'a8yRCFVSYa0'},
{title:'Herrschaft durch Angst - Noam Chomsky',data-video-id:'Bflie94UNyE'},
{title:'Hillary Clinton - Unterstützung der USA für Al Quaida und IS, den Islamischen Staat',data-video-id:'hO9_36Qhktk'},
{title:'Hillary Clinton   We created Al Qaeda',data-video-id:'edBqxGJb8YY'},
{title:'Hintergrund Putsch Ukraine - Wer waren die Todesschützen - Teil 1',data-video-id:'5H8lwazZWic'},
{title:'Hintergrund Putsch Ukraine - Wer waren die Todesschützen - Teil 2',data-video-id:'X71PxGCJHFI'},
{title:'History of US-Surveillance - Darnell Stephen Summers, Vietnam Veteran, Stop The War Brigade',data-video-id:'s2OcBuV7Oic'},
{title:'Hitler ist wieder da - Die Anstalt',data-video-id:'ia03DTw6ICQ'},
{title:'Hitlers Helfer - Kult um ukrain. Kriegsverbrecher u. Juden-Mörder Bandera u Waffen-SS-Division l ARD',data-video-id:'KrWbHlJvLiM'},
{title:'Hitler und Griechenland - Frankfurter Allgemeine Sonntagszeitung',data-video-id:'4TAIfW5fKRI'},
{title:'How Anti-War is the United Nations - David Swanson (World Beyond War)',data-video-id:'T76QOcF_cRY'},
{title:'idx.html',data-video-id:''},
{title:'Inside Job german Trailer',data-video-id:'mV8mSsb5KSg'},
{title:'International Action Day Berlin - Support Bradley Manning & Edward Snowden - Diani Baretto 7_27_2013',data-video-id:'izVAcRGDsVI'},
{title:'Intern. Kräftekonstellation Naher u. Mittlerer Osten.. #3 Gespräch mit Karin Leukefeld',data-video-id:'pVYsmQeaG60'},
{title:'In wie vielen Ländern hat die USA militärisch interveniert • mit Stephen Kinzer • BRAVE NEW FILMS',data-video-id:'1JWSHLfPVXc'},
{title:'Irak März 2003 - Völkerrechtswidriger Angriffskrieg _ Kriegsverbrechen',data-video-id:'pWuzXaX1Jg4'},
{title:'Irak - Uranmunition - das strahlende Vermächtnis - Weltspiegel (antikriegTV)',data-video-id:'ljUoJnMlg1Y'},
{title:'Iranians affected with depleted uranium toxic air',data-video-id:'JZ3VFaWboFk'},
{title:'Iraq - Cancer caused by Depleted Uranium munitions used by US-military',data-video-id:'piukk3Oqmi4'},
{title:'Irrsinn der Wirtschaftssanktionen gegen Russland',data-video-id:'e_8rRsH-wYM'},
{title:'ISIS’ Toyota Mystery Solved - US State Department shipped Toyotas to “Free Syrian Army”',data-video-id:'V9k9HbHMZqg'},
{title:'Islamexperte Michael Lüders - Terrorziel Europa - Terror unterstützt vom Westen',data-video-id:'TphauUqyRdw'},
{title:'Island Revolution 2012 kriminelle Bankster zur Rechenschaft gezogen',data-video-id:'_DnLCcj4_Go'},
{title:'IS-Milizen drohen Menschen mit Mord, verabreichen Drogen und zwingen zu kämpfen',data-video-id:'acnmmFaYLgk'},
{title:'Israel and Palestine - Information',data-video-id:'JdGyQZ86CFc'},
{title:'Israel und Palästina - Norbert Blüm spricht Tacheles - antikriegTV2',data-video-id:'x40YSu7rEsE'},
{title:'Iwan Rodionow (RTdeutsch) Rosa-Luxemburg-Konferenz',data-video-id:'g1ySXiWaFH4'},
{title:'Jakob Augstein bei Precht - Ukraine und Poroschenko 30.11.14',data-video-id:'vVe6YlpGeMc'},
{title:'Jean-Claude Juncker - Ohrfeigen beim Gipfeltreffen „Östliche Partnerschaft“',data-video-id:'AV9nRJVb6X4'},
{title:'Jean Ziegler  auf der G7 Demo - Juni 2015',data-video-id:'FFYnLr6NXN4'},
{title:'Jemen - Saudische Kampfjets verhindern zivilen Hilfsflug aus dem Iran',data-video-id:'uRSD7VX7B6w'},
{title:'Jeremy Scahill Interview - Berlin October 2013',data-video-id:'PiPBipV2aic'},
{title:'Jesse Ventura  ENOUGH OF THIS WAR CRAP!-STYnG5WMvOI.mp4.part',data-video-id:'5WMvOI.part'},
{title:'Jetzt offiziell - US-Waffenlieferungen an die Ukraine',data-video-id:'gRkj32Q3X5s'},
{title:'John McCain - Arm Syrian Rebels to Shoot Down Russian Planes (Oct. 2015)',data-video-id:'PKcgbqdEOJ8'},
{title:'Journalist Christian Wehrschütz im Donbass - Bankrotte Ukraine _ Flüchtlingselend',data-video-id:'8Q1_BLqzqzI'},
{title:'json',data-video-id:''},
{title:'J. Todenhöfer - Welche Geheimdienste stehen hinter dem IS (Islamischer Staat)',data-video-id:'Fv7TWC1NX3o'},
{title:'Jüdische Gemeinde Thessaloniki fordert Entschädigungszahlungen der Deutschen Bahn',data-video-id:'N8axSFqTp2Q'},
{title:'Julian Assange Interview - Die Zukunft der Überwachung 12.12.12',data-video-id:'DFyMT0ETrKQ'},
{title:'Juli Zeh zur NSA Affäre',data-video-id:'6u76_YRcFKw'},
{title:'Jürgen Todenhöfer bei der IS - Größte religiöse Säuberung geplant',data-video-id:'21guT36nTIw'},
{title:'Jürgen Todenhöfer bei Pelzig - Oktober 2015',data-video-id:'BxSg6iP5TWo'},
{title:'Jürgen Todenhöfer -  Der Krieg gegen den Islam  - antikriegTV2',data-video-id:'Dtv_0KINEgA'},
{title:'Jürgen Todenhöfer - Der Terror in Paris und die Hintergründe',data-video-id:'SuPRwgAlFOw'},
{title:'Jürgen Todenhöfer - israelische Armee begeht Kriegsverbrechen',data-video-id:'fieBnL7VhZ0'},
{title:'Jürgen Todenhöfer - Offener Brief an alle Kriegspolitiker der Welt',data-video-id:'xg2VCqwOSRc'},
{title:'Jürgen Todenhöfer - Sieger in Afghanistan ist der militärisch industrielle Komplex',data-video-id:'nYGky7eiONM'},
{title:'Jürgen Todenhöfer über die Bombenorgie in Gaza',data-video-id:'K_Hl-clIOpE'},
{title:'Jürgen Todenhöfer Westen ist selbst schuld am Terror der Islamisten',data-video-id:'hVXO4--bvrg'},
{title:'Justus Frantz über Putin, Weltkrieg und Sanktionen gegen Russland.',data-video-id:'8yBAUGpmx08'},
{title:'Kabarettist Uwe Steimle - Russland, Merkel, Kriege, USA, Flüchtlinge',data-video-id:'99iQ52WpRZw'},
{title:'Kabarretist Christoph Sieber über die Realität',data-video-id:'5jER649Nens'},
{title:'Kai Ehlers - Russische Einsätze in Syrien – kleiner Kommentar zur großen Lüge',data-video-id:'rLeiwMEudfs'},
{title:'Kampfroboter und Drohnen - Krieg der Zukunft 2.4.13',data-video-id:'4inEBSUg-Qk'},
{title:'Kampf um Souveränität - Evo Morales, Präsident des Plurinationalen Staates Bolivien (Wien 2012)',data-video-id:'blIyqqG5CFk'},
{title:'Kanzlerin Merkel schwört USA die Treue',data-video-id:'oLHrTG6pNK4'},
{title:'Kaveh - Soundstrike Berlin gegen Rechts (antikrieg.TV)',data-video-id:'LEir53QVVEU'},
{title:'Keine Nabucco Pipeline sondern Abhängigkeit',data-video-id:'BUc6UsieTi8'},
{title:'Keine Sanktionen gegen Russland! Wirtschaftskammerpräsident Leitl',data-video-id:'MakSf9N2WfQ'},
{title:'Keine Sanktionen gegen Russland! Wirtschaftskammerpräsident Leitl  - OK',data-video-id:'R1_vSnyYUxQ'},
{title:'Kein Krieg in meinem Namen!',data-video-id:'EXx007AnswM'},
{title:'Kein Krieg in meinem Namen!',data-video-id:'qKKajttiXn4'},
{title:'Kiew - Antikriegspartei im Parlament ll Mikrofon abgestellt',data-video-id:'X_FRFEcQiPQ'},
{title:'Kiew legalisiert die Anwerbung ausländischer Söldner - antikrieg TV',data-video-id:'TUuHf5RwoQI'},
{title:'Kiew TV-Talkshow debattiert offen über Kriegslügen - Ukraine ruiniert',data-video-id:'ZFZmRLyyujs'},
{title:'Kiew, Ukraine - Polizisten unter Beschuss von Neonazis - 22 1 14 (antikrieg.TV)',data-video-id:'lx6R5nFiIuU'},
{title:'Kiew will Mauer an der Grenze zu Russland errichten',data-video-id:'QVSqJF0VE_Q'},
{title:'Kinder Bataillon ll Ukrainischer Volkssturm 5.9.14',data-video-id:'oP33u6dGZ7M'},
{title:'Kinderprostitution - Vertuschte de Maiziere (CDU) Verstrickungen von Politikern (Kontraste, ARD)',data-video-id:'KWiQijckYKM'},
{title:'Kindersoldaten bei den Rebellen in Syrien (antikriegTV)',data-video-id:'RYq7SF2JtPA'},
{title:'Kissinger - Kiew ist Generalprobe für Regimechange in Moskau (antikrieg.TV)',data-video-id:'yo5_ct7R6Ng'},
{title:'Kissinger - Regimechange in Kiew . Moscow next target (antikrieg.TV)',data-video-id:'ghj3y_BpGaA'},
{title:'Klitschko bringt Nazi Grußformel zurück nach Deutschland',data-video-id:'5HqZMLt8yxE'},
{title:'Kobane - Pässe ausländischer ISIL-Kämpfer mit türkischen Ausreisestempeln - Sky News 26.10.14',data-video-id:'BgXZoog5JcY'},
{title:'Konstantin Wecker u. R. Düringer   Überwachung, Griechenland, Krise, Staatsgewalt - antikriegTV2',data-video-id:'RSOvs2ssFCE'},
{title:'Krasse Fakten - Verbindungen zwischen der Türkei und IS (Islamischer Staat)',data-video-id:'NEgxEohgBXM'},
{title:'Krieg ist geil - Supergeil (antiwarpropaganda copyleft)',data-video-id:'0Evx9LIyMW8'},
{title:'Krieg ist illegal - War is illegal',data-video-id:'xZjugSQ9bNQ'},
{title:'Krieg nicht in unserem Namen - Gabriele Krone-Schmalz - Wir müssen uns wehren!',data-video-id:'llpdnC7rVeQ'},
{title:'Kriegspopaganda gegen Syrien entlarvt  Professor Meyer im ZDFspezial 29.8.13',data-video-id:'gzY_gkq5INQ'},
{title:'Kriegspropaganda Chemiewaffen in Syrien - ARD Monitor',data-video-id:'UEzb3zy03Es'},
{title:'Kriegspropaganda gegen Syrien erklärt 30.8.13',data-video-id:'0IQFkaiG1qE'},
{title:'Kriegspropaganda Kleber ZDF vs Siemens Chef Kaeser',data-video-id:'hwBHr-G2s2A'},
{title:'Krieg stoppen - Dazwischen gehen - DFG-VK',data-video-id:'3XA_F6mNHEI'},
{title:'Kriegstreiber Brok - Offene Aggression Russlands mit regulären Truppen in der Ukraine',data-video-id:'G4Ie64kkSho'},
{title:'Kriegstreiber Schockenhoff über Intervention Russlands in der Ukraine',data-video-id:'uhTGO3_bL_Y'},
{title:'Krim Sezession - Gerhard Schröder vs Josef Joffe (Zeit)',data-video-id:'aohNEBM0Ha4'},
{title:'Krimtour 2015 - Frieden mit Russland - крымтур 2015',data-video-id:'KXh4Uy-aGp8'},
{title:'Krise für 99% = Eldorado für 1%',data-video-id:'smyXk3ZI6E8'},
{title:'Krisenopfer  Die neuen Hausbesetzer in Spanien',data-video-id:'V0IVRHaPoJg'},
{title:'Kritische ARD-Berichterstattung über ukrainischen  Bandera Nazi Kult',data-video-id:'Ym6k4HKSZog'},
{title:'Kurz ueber das Wichtigste zu Schiefergas Fracking',data-video-id:'Mkp9CDBBHpo'},
{title:'«La Bestia» Güterzug für Migranten aus Zentralamerika Richtung USA',data-video-id:'n4qS6CiYfPs'},
{title:'Lafontaine - Verfassungsschutz soll CDU_CSU überwachen - antikriegTV2',data-video-id:'gizFRhnL6MM'},
{title:'Lage in Syrien - FM 88,4 StudioAnsage MEGAspree on Air 1.10.13',data-video-id:'kAYdRl4H290'},
{title:'Lampros Savvidis - Neuste Entwicklungen in Griechenland',data-video-id:'he-N5MWKxnU'},
{title:'Legale Bankgeschäfte oder organisierte Kriminalität (antikrieg TV)',data-video-id:'krwZQqsnI0U'},
{title:'Legale Steuertricks - Google, Apple, Starbucks und Co.',data-video-id:'n8JNYQruqh0'},
{title:'LESCH UND WIR - Herrscher über Milliarden',data-video-id:'UlibpUKBLc8'},
{title:'Lets make money - Filmausschnitt - Hermann Scheer (antikriegTV Kanal2)',data-video-id:'BTbmZzj6wcc'},
{title:'Linke Utopien - Precht diskutiert mit Sahra Wagenknecht',data-video-id:'hOmINGMGcL8'},
{title:'Lobbyismus - Abgeordnetenkorruption in Deutschland',data-video-id:'emjSxEBMREc'},
{title:'Machtkampf der Oligarchen in der Ukraine - Zweite Front',data-video-id:'X842LKiwF2k'},
{title:'Machtkampf in Kiew - Söldner-Bataillon Dnepr-1 stürmt Staatskonzern UkrNafta',data-video-id:'Asi1ty85X9o'},
{title:'Malaysia - Umgang mit Senioren',data-video-id:'KluQA_vxtHo'},
{title:'Manifestacion Berlin - Las manos sucias de Chevrón en Ecuador 30.11.13',data-video-id:'c66PCRN8lVQ'},
{title:'Maria do Socorro Gomes Coelho - Presidente Conselho Mundial da Paz',data-video-id:'XV97OlRk4GM'},
{title:'Mark Lombardi   Künstler auf den Spuren der Mächtigen  - antikriegTV2',data-video-id:'Rb2ZBn3DbUE'},
{title:'Massaker im Gewerkschaftshaus in Odessa - Eine Überlebende berichtet',data-video-id:'FqBl-aaT5dY'},
{title:'Massenmord im Mittelmeer (Rotfuchs)',data-video-id:'6NuyIuzVIRQ'},
{title:'Massive Proteste gegen ukrainische Armee - Mädchen von Spähpanzer überfahren',data-video-id:'_qT1B2F2fdw'},
{title:'Max Uthoff (Die Anstalt) Über den Journalismus und dessen Niedergang',data-video-id:'ixo0jq3OOXY'},
{title:'Max Uthoff - Ukraine und die deutsche Qualitätspresse im Drogenrausch',data-video-id:'68QYPNZD9sI'},
{title:'MC King David calling for Peace and Justice - antikriegTV',data-video-id:'ZLn89jZjDBU'},
{title:'Medienkrieg in der Ukraine gegen TV-Sender mit russ. Programm (antikriegTV)',data-video-id:'YXxbGfe72W8'},
{title:'Medien und Politik ll Strippenzieher im Hinterzimmer',data-video-id:'FN3dSjZl5wU'},
{title:'Merkel - Russischer Präsident Putin ist beim G7 Treffen unerwünscht',data-video-id:'nk0dSE2ezPQ'},
{title:'MH17 Abschuss - Doch Kiew verantwortlich Hochrangiger SPÖ-Politiker fordert vorbehaltlose Aufklärung',data-video-id:'0MXtjKKnvCQ'},
{title:'#MH17 EXPLOSIV  OSZE Beobachter entdeckt an der Boeing Maschinengewehr-Einschüsse',data-video-id:'DkupbOoOl1o'},
{title:'#MH17 wurde mit Maschinengewehr beschossen - CBS Canada TV ll #Ukraine',data-video-id:'WIoH0Ep6XkU'},
{title:'Michael Lüders (Sicherheitsexperte) zur Krise in der Ukraine',data-video-id:'6MRFUM-ViCM'},
{title:'Michael Lüders zur brutalen Politik der USA',data-video-id:'PyqS8zobPpM'},
{title:'Militärisch industrieller Komplex der USA will Ausweitung der Kriege',data-video-id:'u9h3BzNJass'},
{title:'Militär und Abschottung gegen Wirtschaftsflüchtlinge - Die Anstalt Sept. 15',data-video-id:'Pch3Rxxo1GU'},
{title:'Millions Die in the Congo -  U S Role - The Struggle #509',data-video-id:'kz2JVojXPfc'},
{title:'Mit offenen Karten - Der Waffenhandel (antikriegTV Kanal2)',data-video-id:'1dbNjg8GIG4'},
{title:'Monitor (ARD)   Grenzenlose Überwachung durch NSA   Was wusste die Bundesregierung    04 07 2013',data-video-id:'9T3FzYpAkvU'},
{title:'Monitor - Deutschlands neue militaristische Politik (antikrieg.TV) 21.2.14',data-video-id:'7aIBVt5yFNQ'},
{title:'Monitor_ Geschäft mit dem Hunger 30.8.12',data-video-id:'XcC6Ok5aGgI'},
{title:'Monitor - Menschenrechte  Zusammenarbeit mit Diktaturen',data-video-id:'pBT4fgeDiXc'},
{title:'Monitor - Neue Atombomben für die deutsche Bundeswehr 19 06 14',data-video-id:'yAwts76aGlg'},
{title:'MONITOR - Scharfschützen in Kiew',data-video-id:'UR5T6VhtPlc'},
{title:'Morde in Deutschland - Wer terrorisiert hier wen - Die Anstalt',data-video-id:'_7P-xAo-sQI'},
{title:'Mr. Dax - Banken und Politik - antikriegTV2',data-video-id:'RU5kDoRB5-U'},
{title:'Multinational companies buy Greek mines at bargain prices',data-video-id:'K8XSQIE2Kvs'},
{title:'Muslime in Deutschland',data-video-id:'hFRRjIIViSI'},
{title:'Mütter gegen den Krieg - Brigitte Queck - Buchvorstellung',data-video-id:'SEAZd-fWFhs'},
{title:'NachDenkSeiten ll Albrecht Müller ll Gefaht durch manipulativen Kampagnenjournalismus',data-video-id:'KQbHYzlbqVE'},
{title:'Nachdenkseiten - „Sozialausgaben auf Rekordhoch gestiegen“ – Lügen mit Zahlen',data-video-id:'skLjwlqsOvU'},
{title:'Nach Protesten von 250.000 Demonstranten - „Spiegel Online“ diffamiert TTIP-Kritiker (Nachdenkseiten)',data-video-id:'se-PIjEAZ_g'},
{title:'Nachrichten aus der Ostukraine - 4. April 2015',data-video-id:'GN4mpeC6PnI'},
{title:'Nachrichten aus der Ostukraine _ Krim 24.11.15',data-video-id:'NbyVde2smCI'},
{title:'Nachricht von Mumia Abu-Jamal vom 26. April 2015 - Prison Radio',data-video-id:'kPSeVTaNgjs'},
{title:'Nächste Ausflug nach Stalingrad ll Christoph Sieber 30.8.14',data-video-id:'vi45jBQgOHg'},
{title:'NATO - Analyse der Opposition in Deutschland - Alexander Neu, DIE LINKE',data-video-id:'3ryv7O2svVM'},
{title:'NATO-Geheimarmee - Bombenlegerprozess Luxemburg - Sat3',data-video-id:'aQ6I8poqcMo'},
{title:'NATO Geheimarmee GLADIO - Bombenlegerprozess in Luxemburg - TV Sat3',data-video-id:'BIxOACTjroU'},
{title:'NATO General a.D. Kujat - Russland als Supermacht akzeptieren - Jan. 2015',data-video-id:'BAMIj5lTdFM'},
{title:'NATO General a.D. Kujat über gefälschte Beweise der USA gegen  Russland',data-video-id:'asEQ4lt4b6o'},
{title:'Nato Gipfel Chicago 2013 - US Kriegsveteranen werfen ihre Orden weg',data-video-id:'uZjLBD-oDAA'},
{title:'Nein zum Kapitalismus - Jean Ziegler _ Heiner Geissler',data-video-id:'oWh5JVfauwY'},
{title:'Neonazis und Holocaust-Leugner - Wahrheit macht frei  - Nieder mit dem Faschismus',data-video-id:'WJb0cGdAee0'},
{title:'Netanyahu Admits his Countrys Alliance with Saudi Arabia',data-video-id:'JRpeA77WTeY'},
{title:'Neues aus der Anstalt   Pelzig umgeht ZDF Verbot und zählt EU für den Wasserwahn aus 3 08 min',data-video-id:'284hgD4PlDU'},
{title:'Neues aus der Anstalt ZDF 29.4.14',data-video-id:'dh279AiSujw'},
{title:'Never Before Seen Footage 9_11',data-video-id:'tFTOFPds4eU'},
{title:'New York Protest - Dont Attack Syria! - Sept.8, 2013',data-video-id:'raWtjau_IyU'},
{title:'Nie wieder Krieg zwischen Deutschland und Russland',data-video-id:'L3K8R-vMs4c'},
{title:'Nie wieder Krieg zwischen Russland und Deutschland #2',data-video-id:'1L_hCAE67WY'},
{title:'NO al Fraude electoral en Honduras - Berlin 30. Noviembre',data-video-id:'h-GS5F61WRs'},
{title:'Noam Chomsky - Hat Grass recht',data-video-id:'kgXjytYa-9o'},
{title:'Noam Chomsky im Interview 25.6.13',data-video-id:'vlufl9ui4kw'},
{title:'Noam Chomsky - Schurkenstaat USA betreibt globale Ermordungskampagne  mit Kampfdrohnen',data-video-id:'vl2PnLq9JuE'},
{title:'Noam Chomsky - US-Drohnenkrieg, Folter und Terror - Politik des Iran',data-video-id:'lrVqLD2_jsg'},
{title:'Noam Chomsky - Weltweit gefährlichste Terror-Organisation heißt nicht „IS“ sondern ...',data-video-id:'Jm3fiiBMZ9w'},
{title:'Noch mehr Fragen - G8 Gipfel Genua Sommer 2001 - antikriegTV2',data-video-id:'s2cZLJUNGGc'},
{title:'#NoSpyAbkommen (antikriegTV)',data-video-id:'yWF0BrHKliE'},
{title:'Novinsky, ukrain. Oligarch gibt Poroschenko die Schuld am Tod der 70 Maidan-Toten',data-video-id:'uCkkifeb8P8'},
{title:'NS-Geheimsache Uran - Atomjagd in Brandenburg - Teil 1',data-video-id:'zTRIz-qX3g4'},
{title:'NS-Geheimsache Uran - Atomjagd in Brandenburg - Teil 2',data-video-id:'DnmzDvfgPFQ'},
{title:'NS-Geheimsache Uran - Atomjagd in Brandenburg - Teil 3',data-video-id:'sv-LEndwa34'},
{title:'NSU Prozessbeginn - brisante Hintergründe',data-video-id:'EBhgNwfweeo'},
{title:'NSU-Prozess - Die Engstirnigkeit bayerischer Richter',data-video-id:'vASx7-XeWG8'},
{title:'Nulands Hirn - Antikriegsgedicht',data-video-id:'el1SL-FXYhQ'},
{title:'Obama Jokes About Predator Drones At The 2010 White House Correspondents Association Dinner',data-video-id:'cm033GVNX3w'},
{title:'Obama - Russland  Feind der zivilisierten Welt',data-video-id:'3ZBxt0_XHjA'},
{title:'Obamas Videobeweise  für chemische Attacken in Syrien',data-video-id:'eFCxMPWPa1c'},
{title:'Occupy Police   United We Stand - antikriegTV2',data-video-id:'oBrEK1n6L1w'},
{title:'Oles Busina, ermordeter ukrainischer Journalist, Schriftsteller l Russ. TV',data-video-id:'19_OTGIRMps'},
{title:'Online Demo – Stoppt den Fremdenhass – Jürgen Todenhöfer',data-video-id:'zxqY-QNZ4aM'},
{title:'Oskar Lafontaine  Bush und Blair sind Terroristen!',data-video-id:'J8IWe5drYmI'},
{title:'Oskar Lafontaine Gute Nachbarschaftspolitik zu Russland!',data-video-id:'7yH5j23CcP0'},
{title:'Oskar Lafontaine - Türkei darf die IS-Mörderbande nicht weiter unterstützen - bei Maybrit Illner',data-video-id:'zVbPgqGySOk'},
{title:'Oskar Lafontaine über verlogene US-Politik - bei Maybrit Illner',data-video-id:'M9GBBOcZexY'},
{title:'Oskar Lafontaine - Westen muss aufhören Interventionskriege zu führen und Waffen zu exportieren',data-video-id:'p9Gar82Q-hI'},
{title:'Ostukraine l Kinder leben aus Angst vor Beschuss im Atombunker',data-video-id:'e9U5u31DoR0'},
{title:'Ostukrainer - Jazenjuk und Merkel in den Haag vor Gericht stellen',data-video-id:'gyEXl-C5QAQ'},
{title:'Ostukraine - Verbrechen der faschistischen “Ajdar” Kämpfer',data-video-id:'WV7V31mTDjo'},
{title:'Ostukraine - Zerstörungen in Perwomajsk',data-video-id:'EUYiAl9H9a8'},
{title:'Otpor  Gesteuerte Revolten Ukraine, Venezuela, Syrien, Iran  1 antikriegTV',data-video-id:'b2zBdvCYE-g'},
{title:'Otpor - Gesteuerte Revolten Ukraine, Venezuela, Syrien, Iran #1 (antikrieg.TV)',data-video-id:'EzmcPNC2Skk'},
{title:'Otpor - Gesteuerte Revolten Ukraine, Venezuela, Syrien, Iran #2 (antikrieg.TV)',data-video-id:'FgZJa4EQwPA'},
{title:'OXI-Party im Karl-Liebknecht-Haus in Berlin am 5.Juli 2015 - KIEKE MA FILM BERLIN',data-video-id:'wVUGN-N_fMI'},
{title:'PAN - Krieg (antikriegTV)',data-video-id:'hgpanuQRh94'},
{title:'PAN - mix',data-video-id:'NqsyPzJU6co'},
{title:'Panorama - Russland Krise - Mai 2015',data-video-id:'5unAFGZ8RRA'},
{title:'Panorama - Syrien - Flüchtlinge - Frontex',data-video-id:'jX_rlxigKQI'},
{title:'Parteitag DIE LINKE  - Sahra Wagenknecht, Christiane Reymann (antikriegTV)',data-video-id:'URLWMv6EyTY'},
{title:'Pelzig Lieber den Russen vor der Tuer als den Ami in der Leitung (antikriegTV)',data-video-id:'rpzFz2PGgEs'},
{title:'Pensionierter US-General fordert - Anfangen Russen zu töten!',data-video-id:'uczLeBo2sgo'},
{title:'PEOPLE OF THE WORLD STOP THE WAR',data-video-id:'OXCk6mh1XJ4'},
{title:'Perfide Medienlügen zum Thema Flugzeugabsturz MH17',data-video-id:'JhjN3baw57M'},
{title:'Peter Gauweiler (CSU) - Russland miteinzubeziehen wäre wichtig gewesen',data-video-id:'r8moNa6Di6Q'},
{title:'Peter Scholl Latour - Ukraine, Russland, China u. Iran',data-video-id:'imAhis-coX4'},
{title:'PKW MAUT und Massenüberwachung (antikriegTV)',data-video-id:'NHL1jrxtq84'},
{title:'Plant Kiew Angriff auf Russland S-300 Flugabwehrraketen einsatzbereit',data-video-id:'9VrBDAPpWKI'},
{title:'Platz der Unabhängigkeit Kiew Ukraine - Neonazis (antikrieg.TV)',data-video-id:'3m8XEJ_0lSE'},
{title:'Polen bereitet sich auf den Krieg mit Russland vor',data-video-id:'CRGMzsNTCgA'},
{title:'Polizeibeamter mit Kontakten zur Pegida-Bewegung',data-video-id:'ECjC9ICwYYM'},
{title:'Polizeigewerkschaftsboss - Facebook wird von CIA finanziert (antikriegTV)',data-video-id:'9xFf410iH9g'},
{title:'Portugals Nelkenrevolution - Viva Portugal - (antikriegTV)',data-video-id:'5l5zCd_wVXk'},
{title:'p.pl',data-video-id:''},
{title:'PPP - Public Private Partnership (antikriegTV)',data-video-id:'MvzjBqAk8fE'},
{title:'Präsident Ecuadors kritisiert US-Sanktionen gegen Venezuela - antikriegTV',data-video-id:'eGxuaBmIrNA'},
{title:'Präsident Putin - Bau von South Stream Pipeline abgebrochen',data-video-id:'rfaTf5Z186k'},
{title:'Präsident Rafael Correa - Ecuadors #Antichevron Kampagne',data-video-id:'LDxyPGW-1Wk'},
{title:'#PRISM Demo anläslich Obamabesuch in Berlin  19 6 2013',data-video-id:'zZ4xO5_AbVs'},
{title:'#PRISM Demo   Cornelia Otto 19 6 2013',data-video-id:'R7RRmqvGwXc'},
{title:'Prism - Spionagesoftware der USA',data-video-id:'y4UVgZynbQM'},
{title:'Prof. Dr. Manojlo (Moskau) - Ukraine von neonazistischen Gruppen kontrolliert',data-video-id:'y0Dn2IFfKRI'},
{title:'Prof. Foschepoth, Historiker ll #NSA, alliertes Recht in Deutschland ll ARD Tagesschau',data-video-id:'jV3VRBjUOb4'},
{title:'Prof. Michel Chossudovsky Part 1 - Rosa Luxemburg Konferenz Berlin 2014',data-video-id:'U1UHS9wWZXo'},
{title:'Prof. Michel Chossudovsky Part 2 - Rosa Luxemburg Konferenz Berlin 2014',data-video-id:'cSHup56PqqM'},
{title:'Prof. Noam Chomsky - US-Aggression gegen Russland - verständliche Politik Russlands',data-video-id:'sdSxKHYkjDI'},
{title:'Prof. Noam Chomsky (USA) - Griechenland und das Schuldenregime Europa',data-video-id:'151ENsX7S1w'},
{title:'Propaganda-Chemiewaffen Syrien - J. Hippler, Politikwissensch._Friedensforscher - ARD Monitor',data-video-id:'7I85FdOOQHI'},
{title:'Propaganda im US-Fernsehen - Putin und Assad schuldig an Flüchtlingskrise',data-video-id:'ReH6ofWm6T0'},
{title:'Propaganda und Falschmeldungen über Syrien 2013',data-video-id:'alkyY86ngno'},
{title:'Propaganda - WeiWei - PussyRiot - Femen - Euromaidan - Antichina - AntiPutin',data-video-id:'IVlBN71WFKg'},
{title:'Proteste in der Türkei - Brutales Vorgehen der Behörden - 4.6.13',data-video-id:'sl--oRXd2XY'},
{title:'Putin als Liebhaber',data-video-id:'Nu16xN5Tzxo'},
{title:'Putin Berater Glazjev  Russland will keinen Krieg! Hochgefährliche Situation l RT',data-video-id:'gHP4uMrLTqI'},
{title:'Putin Der Präsident Teil 1 - Russ. TV Kanal Rossija 1',data-video-id:'ugYi9mIvQSk'},
{title:'Putin Der Präsident Teil 2 - Russ. TV Kanal Rossija 1',data-video-id:'evGrf8AGQLI'},
{title:'PUTIN IST NICHT UNSER FEIND - Jürgen Todenhöfer',data-video-id:'LL2JIgn8amU'},
{title:'Putin Versteher Mathias Broeckers packt aus',data-video-id:'ttAf_GKif1A'},
{title:'Putschgefahr in Venezuela',data-video-id:'AkL6UzWuTgs'},
{title:'Quadrokopter-Drohnen Experimente -  ETH Zürich',data-video-id:'sgMAy1jR6ZQ'},
{title:'Radpanzer - Unbemannt, autonom operierend, serienreif (antikriegTV)',data-video-id:'OFXkjJZxuyQ'},
{title:'Ranghöchster US-General - ISIS wird  unterstützt von wichtigen arabischen Verbündeten (Sept.2014)',data-video-id:'lAU1EIGhWAI'},
{title:'Rapper aus Moskau unterstützen Putin',data-video-id:'RBVLeV3rc5Q'},
{title:'Razzia bei der Deutsche Bank am 12.12.12 - Zinsmanipulation(LIBOR)',data-video-id:'TYBttOtDQpQ'},
{title:'Razzia bei der Deutschen Bank Tagesausblick - Dirk Müller Mr. Dax (antikriegTV Kanal2)',data-video-id:'YdpK2xOJh6s'},
{title:'RBB Abendschau  Yes we Scan Chor   die PRISM Demo in Berlin   18 06 2013',data-video-id:'CKC9mcbp-II'},
{title:'Rechter Terror in Griechenland - Aufstieg der Chrysi Avgi',data-video-id:'FiBPWCXaXbw'},
{title:'Recycling von Kunstoff zurück zu Öl',data-video-id:'AtPdA5f4ZUk'},
{title:'Regierung dementiert - Atomwaffen in Büchel - ARD Monitor',data-video-id:'nA_d_3i3H4g'},
{title:'Regierungskriminalität und das Ende des Rechtsystems (antikrieg TV)',data-video-id:'CIlJhFNOa5w'},
{title:'Report München ll Smartphone als Super-Wanze',data-video-id:'P1UkCV91WfA'},
{title:'Revolutionen Made in USA - Wo die nächste',data-video-id:'3vhZUfZcWpo'},
{title:'Rhetorische Mobilmachung der NATO gegen Russland ll gefälschte Satellitenfotos der USA',data-video-id:'_djOMcOrKKA'},
{title:'Richard David Precht ll Rhetorik des Kalten Krieges extrem gefährlich',data-video-id:'aKigr_77YHg'},
{title:'Rick Rozoff - Nuland Instructed U.S. Envoy On Ukrainian Government Makeup',data-video-id:'shCYy7XpAe4'},
{title:'Riesige Gasvorkommen in Griechenland - Gezielte Destabilisierung - Dirk Müller',data-video-id:'jpJSx9-1V0U'},
{title:'Rod Starz _ Rebel Diaz - Refugees & Western Imperialism',data-video-id:'6s9LYcOq5Hc'},
{title:'Roland Dumas - Syrien Konfilkt seit langem geplant - 10  Juni 2013)',data-video-id:'FLlmLtIRNRA'},
{title:'Rome - Protests against austerity - May, 18, 2013',data-video-id:'QiYuP-bfObg'},
{title:'Ron Paul - Ukraine MH17 & what the Media Wont Report About',data-video-id:'34H69LoLAM8'},
{title:'Roseanne Barr - Die Wahrheit über Hollywood und Manipulation',data-video-id:'PzAWqJqxDaI'},
{title:'Russian President Putin at Waldai Disscussion Forum (Oct.2014)',data-video-id:'lvhjO-LHBNk'},
{title:'Russian President Putin on Ukrainian Crisis -  Feb 23',data-video-id:'d0wnNCCdHcs'},
{title:'Russian President Putin - Ukrainian army is NATO legion (english)',data-video-id:'MikMsGZeTBA'},
{title:'Russische Kriegsreporter in Syrien',data-video-id:'iVruPXqKGcI'},
{title:'Russischer Generalstab - Türkischer Su 24-Abschuss schwere Straftat',data-video-id:'_CHvjFBdwHg'},
{title:'Russland als Großmacht in einer multipolaren Welt -  Prof. Dr. Schröder (Uni Freiburg)',data-video-id:'nxe2UOhQVaM'},
{title:'Russland _ NATO  Neuer Kalter Krieg  ll  Monitor',data-video-id:'Jlcdtt6lsF4'},
{title:'Russlands Aussenminister - USA üben wegen Russland massiven Druck auf alle Länder aus -',data-video-id:'q5Tg3Q-PT7A'},
{title:'Russlands Außenminister - Was wollen die Deutschen',data-video-id:'3b3sHx3Ym40'},
{title:'Russlands geopolitische Rolle ll Interview Sergei Glasjew l antikriegTV',data-video-id:'EQSDQUsTS-Q'},
{title:'Russlands Präsident Putin - Aggressive Kräfte versuchen Russland zu destabilisieren',data-video-id:'CrN89PvAepo'},
{title:'Russland Versteher Max Uthoff und Claus von Wagner',data-video-id:'_UQclNdQNg4'},
{title:'Russland wie eine Orange zerlegen - Deutscher Plan Orangene Revolution l Ana von Keitz',data-video-id:'UI8qge4OE5w'},
{title:'Russ TV Erster Kanal USA planen Krieg gegen Russland',data-video-id:'zYF5NBKJKUE'},
{title:'Russ. TV - Neuer Kalter Krieg = Totaler Krieg des Westens gegen Russland',data-video-id:'GXBzzuIGEtI'},
{title:'Sahra Wagenknecht - Bundeswehreinsatz in Syrien ist völkerrechtswidrig',data-video-id:'aVkuJgptYso'},
{title:'Sahra Wagenknecht, DIE LINKE - Griechenland, Ukraine, Russland',data-video-id:'hcKo3lQ3US0'},
{title:'Sahra Wagenknecht - Zur falschen Politik der EZB l 22.1.15',data-video-id:'Mvel1-WMPUU'},
{title:'sample1',data-video-id:'WVT9ZUzw5AQ'},
{title:'Sanktionen gegen Russland gegen Interessen Deutschlands',data-video-id:'gQaZ08vMuDQ'},
{title:'Sanktionspolitik gegen Russland ll Monitor über die Doppelmoral',data-video-id:'iXNShg2xsKo'},
{title:'Sardiniens Geheimnis -  Nato-Schießplatz Quirra - Teil 2 - antikriegTV2',data-video-id:'1zQ4jYdGgmk'},
{title:'Saudi first suspected in Boston Martathon bombing deported for reasons of national security',data-video-id:'TwhqGv8p-SE'},
{title:'Scheinheilige EU-Flüchtlingspolitik - 10 Euro Nahrung pro Person_Monat in Syriens Nachbarländern',data-video-id:'eyM1s0A0Tsc'},
{title:'Schluss mit den Kriegen - Britische Kriegsveteranen',data-video-id:'_I2CPuMiUCE'},
{title:'Schmidt Helmut bei Beckmann - Auszug 4.5.13',data-video-id:'kpFBTMmWkX0'},
{title:'Schröder_Merkel Amtsübergabe - Tresor, Geheimunterlagen und Berlusconis Uhren',data-video-id:'F7BZz-XeR7A'},
{title:'Schweizer TV - Ukraine Reportage von Ch Wehrschütz  12.12.14',data-video-id:'26LBn34Xkns'},
{title:'Schwerer Beschuss der Wohnviertel Nähe Flughafen Lugansk - OSCE vor Ort',data-video-id:'B3H9CXqpBj8'},
{title:'Sigmar Gabriel und seine TTIP-Täuschungspolitik',data-video-id:'gJhTMCxNBs0'},
{title:'Situation von Geflüchteten in Deutschland und an den EU-Außengrenzen - Maik Bischoff',data-video-id:'wz-Nmc9itRE'},
{title:'Sky News Interview with Syrian and Foreign Wahhabi Radical Jihadis Captured in Syria',data-video-id:'Xca00-TUVfQ'},
{title:'Snowden - Geheimhaltung, Kriegsverbrechen, Folter - Chelsea Manning_Sam Adams Award',data-video-id:'7csI5QF7PCE'},
{title:'Soziale Gerechtigkeit _  Neid und Gier - Wilfried Schmickler 09.12.12',data-video-id:'h3KlgJAtisE'},
{title:'Spanische Arbeitskräfte in Berlin',data-video-id:'HQKc2w0GEUw'},
{title:'Spiegel TV Journalist steigt aus',data-video-id:'WMN0CdNdvzg'},
{title:'Spionageaffäre - Die Vertuschung der BND-Hilfe für die NSA 29.04.2015',data-video-id:'hwSFeszKSi8'},
{title:'Spionage der NSA offiziell erlaubt  Frontal 21 ZDF 30.7.13',data-video-id:'jwEfz5ulKw0'},
{title:'Ständige Publikumskonferenz Medien  Warum gegen Russland',data-video-id:'7xpKGvmm_cI'},
{title:'Stefan Kretzschmar zum Ukrainekonflikt ll Unsere Medien sagen nicht die Wahrheit',data-video-id:'3EPYdqAb70g'},
{title:'#StopWatching Demo am Samstag 27 07 2013',data-video-id:'9Q02rqSxSQo'},
{title:'Störsender -  Kernenergie  - Dieter Hildebrandt',data-video-id:'gj_2_eH7QbE'},
{title:'Störsender - Steueroasen - Dieter Hildebrandt',data-video-id:'t6AU2NZll9Q'},
{title:'Strategie Weltherrschaft Made in USA - Oberstleutnant a. D. Jochen Scholz l antikriegTV',data-video-id:'IZJbAOwx17s'},
{title:'STRATFOR - Kaukasus - Die Grundlagen der Geopolitik',data-video-id:'MsJKf5xPYbQ'},
{title:'Super-Mario, Goldman Sachs und Supereinfluss-Reiche',data-video-id:'QFd38m72ERA'},
{title:'Syrian refugees - We Didnt Leave Because of Assad - Terrorists made us refugees',data-video-id:'IbBNwCn6W94'},
{title:'Syria WMD - False Flag Attack - Ron Paul, US-politician',data-video-id:'_b65WPor1Ww'},
{title:'Syrien 2011 - Die Sozial- und Wirtschaftspolitik #4 Gespräch mit Karin Leukefeld',data-video-id:'2PdNkTBGARA'},
{title:'Syrien - Al Kaida Ableger erobert Palästinenser-Lager Yarmouk in Damaskus - antikriegTV',data-video-id:'Hz4qG3M4TmY'},
{title:'Syrien - BBC - Rebellen zwingen Gefangene zu Selbstmordattentaten',data-video-id:'FFPI4WxqsCs'},
{title:'SYRIEN - Chemie-Waffen - Klartext Prof. Günter Meyer',data-video-id:'KePy6FbYqEs'},
{title:'SYRIEN - Chemie-Waffen - Monitor - Klartext Prof. Günter Meyer',data-video-id:'mMiW-oEAK5I'},
{title:'Syrien   Der Täter steht schon fest',data-video-id:'qm-LHSrOn88'},
{title:'Syrien - Friedensforscher Daniele Ganser zu Obamas Kriegserklärung',data-video-id:'SkTmT8ODDy0'},
{title:'SYRIEN - Giftgas - Michael Lüders, Politik u. Islamwissenschaftler, bei Beckmann',data-video-id:'beWnF4bjpMw'},
{title:'Syrien Hintergrund -  Peter Scholl Latour 4.5.13',data-video-id:'MGtYUq1uMpY'},
{title:'Syrienkonflikt - US-Eliten verfolgen unterschiedliche Interessen (theRealNews)',data-video-id:'B_pGhMGk99g'},
{title:'Syrienkonflikt - US-Journalist stellt Obamas Führungsrolle in Frage',data-video-id:'Nmb2GHWHZAE'},
{title:'Syrienkrise - Harald Kujat (General a.D.) und Wolfgang Gehrcke, MdB',data-video-id:'W2UraTrfvJE'},
{title:'Syrien - Mythos Moderate Rebellen und Freie Syrische Armee - Harte Fakten',data-video-id:'cUdlEly68co'},
{title:'Syrien Propaganda-Berichterstattung ARD & ZDF',data-video-id:'bUGE5jZImG0'},
{title:'Syriens Präsident Assad - Interview 2015 - Westen will keine Partner sondern Marionetten',data-video-id:'aupk9SG_WeY'},
{title:'Syrien und Irak - Kriegspropaganda im Vergleich',data-video-id:'0xgEVKi1aJE'},
{title:'Syrien - Wer sind die Terroristen Von der FSA (Freie Syrischen Armee) und Al-Nusra Front (PBS)',data-video-id:'sFQ9YD7OssU'},
{title:'Syrische Frau attackiert US-Senator McCain wegen dessen Kriegshetze',data-video-id:'HMYgezBxrwg'},
{title:'Syrische Kriegsflüchtlinge - Hintergründe (antikriegTV)',data-video-id:'xD92dQz5zIk'},
{title:'Syrische Opposition und die Al Kaida, ZDF',data-video-id:'9WwlGIJ42ZI'},
{title:'Syrischer Präsident Bashar al Assad  - Interview',data-video-id:'cNa7tHzTMQo'},
{title:'Tacheles Berlin - antikriegTV',data-video-id:'C5RgasOen84'},
{title:'Tacheles zum Gaza Konflikt und Antisemitismusvorwürfen',data-video-id:'RBoTyYK_Pps'},
{title:'Tagesschaue -  Anti Terror Datei - Nov. 2012',data-video-id:'dMvArAA1w0g'},
{title:'Tagesschau - Supergeil - Propaganda - Supergeil',data-video-id:'n5TmCJw8Q84'},
{title:'Tagesthemen -  gegen den Iran - antikriegTV2',data-video-id:'eVzY27yDE68'},
{title:'Tagesthemen PR Desaster - Freiwilligen Bataillone ll 1.10.14',data-video-id:'GH5ELim57D4'},
{title:'Tagesthemen trommeln gegen Syrien - antikriegTV2',data-video-id:'mO_rgjPfUss'},
{title:'Terroranschlag Paris - Vorwarnungen (Beschreibung beachten)',data-video-id:'zrYzoZebTAY'},
{title:'Terror-Milizen erobern syrische Provinzhauptstadt Idlib',data-video-id:'UJNy-Cv4RQk'},
{title:'Terrormiliz IS  - Islamischer Staat - Militärische und wirtschaftliche Macht',data-video-id:'gwbomBsr0_I'},
{title:'The Role of the BBC in the Syrian Conflict',data-video-id:'UdjBPm-dqV4'},
{title:'Thomas Roth versucht Präsident Putin zu provozieren - Georgienkrise',data-video-id:'Z3fqFUVx604'},
{title:'Todenhöfer, Augstein und Gysi über die deutsche Medienlandschaft',data-video-id:'iIdkAo4i7Go'},
{title:'Tötung durch Drohnen - Fall von informeller Todesstrafe  - Johannes Feest',data-video-id:'Rf1jJDJ-Kw8'},
{title:'TTIP   Geheimakte Freihandelsabkommen',data-video-id:'3Tm2RHuW4x8'},
{title:'TTIP und Drohnen lügen nicht - ZDF Heute Show',data-video-id:'6KuxnTfs25I'},
{title:'Türkei - Beweise für Erdogans unterstützt des Islamischen Staat',data-video-id:'qzLuIRYO2tk'},
{title:'Türkei - Bilder der anhaltenden Proteste 2.6.13',data-video-id:'DkxoxMnxeNQ'},
{title:'Türkei bombardiert die Feinde des Islamischen Staates IS - Monitor',data-video-id:'P_YK7nweeDE'},
{title:'Türkei unterstützt Anti-Assad Kämpfer - Whistleblower Chefredakteur Dündar',data-video-id:'iDq2adZpmlQ'},
{title:'Türkei unterstützt Terroristenmiliz IS  - Ehem. NATO-Oberbefehlshaber Wesley Clark',data-video-id:'jx6JUt_7xos'},
{title:'TV-Hetze gegen Muslime in den USA',data-video-id:'JZ1z5YyrWXI'},
{title:'Überlebender Yezide berichtet über Massaker durch ISIS',data-video-id:'Sa36BXc__N4'},
{title:'Über Russland - Hart aber fair 9.9.14',data-video-id:'1_VLUN0bEPw'},
{title:'Ukraine - Abgeordneter von Bewohnern wegen Mobilmachung verprügelt',data-video-id:'abXNxU0KYJc'},
{title:'Ukraine - Berichte über zunehmende Proteste gegen die Regierung',data-video-id:'hcwQtVj-kpA'},
{title:'#Ukraine - Bewaffnete unter den Demonstranten in Kiew 18.2.14 (antikriegTV)',data-video-id:'dsAUdmxGXyE'},
{title:'Ukraine - Brutale Gewalt gegen Polizei in Kiew 18.2.14 (antikriegTV)',data-video-id:'wzl0NayIT3o'},
{title:'Ukraine - Ehem. US-Nachrichtendienstler bezweifeln Anschuldigungen gegen Russland',data-video-id:'mQL4ZU5gA_o'},
{title:'Ukraineeinsatz bewaffneter deutscher Fallschirmjäger und Drohnen ll 6.10.14',data-video-id:'4YsNs2vQKxU'},
{title:'Ukraine - Festgehaltene keine Mitglieder der OSZE-Mission - OSZE-Sprecher Neukirch',data-video-id:'mWeU_4UEAq8'},
{title:'Ukraine -  Gewalttätige Pro-EU Demonstrationen Januar 2014',data-video-id:'6ljK1OvuJpI'},
{title:'Ukraine - Julia Timoschenko - Autor Frank Schumann - Stimme Russland',data-video-id:'BqbrRbaCfYQ'},
{title:'Ukraine; Kampf um das Gas - Monitor 13 3.14',data-video-id:'s35HkTCByk0'},
{title:'Ukraine - Kiew entzieht Euronews die Sendelizenz - antikriegTV',data-video-id:'KR09zNwwmXE'},
{title:'Ukraine, Kiew - Gewalteskalation der Neonazis (antikrieg.TV)',data-video-id:'hFfokKSbeHQ'},
{title:'Ukrainekonflikt - Bremer Landesbank Chefökonom Hellmeyer',data-video-id:'bPWkAppvkfw'},
{title:'Ukraine-Konflikt - Vortrag von Gabriele Krone Schmalz l Harzsparkasse Dez. 14',data-video-id:'FRNeQuJ7CEk'},
{title:'Ukrainekrise - Österreichs Grüne gegen jede weitere Eskalation der USA',data-video-id:'awtX-1d_kPI'},
{title:'Ukraine - Krone-Schmalz - Unverantwortlicher Journalismus',data-video-id:'18tUv7kr5Xs'},
{title:'Ukraine - Lebensniveau massiv eingebrochen',data-video-id:'iJiPNbzepA4'},
{title:'Ukraine; Massive Proteste von Soldaten, Müttern und Ehefrauen. Massive Verluste',data-video-id:'4coa9zc_pJg'},
{title:'Ukraine - MH17 Augenzeugen berichten von Kampfjet ll russ. sprachiger BBC',data-video-id:'KdSH_ajncuA'},
{title:'Ukraine - Mütter gegen Krieg',data-video-id:'8kEWXmEw1a8'},
{title:'Ukraine - Nationalistische Kampfer bereiten sich auf den Krieg vor',data-video-id:'Q43GJJzZFBc'},
{title:'Ukraine, NATO-Kriege ll Mitternachtsspitzen - Wilfried Schmickler   30 8 14',data-video-id:'4zSpiaXgRzI'},
{title:'Ukraine Nazi like torture techniques used in Kramatorsk against POWs and civilians sitting in pits',data-video-id:'R2BECdCONiU'},
{title:'Ukraine; Neonazis attackieren Stadtverwaltungsgebäude von Kriwoj Rog (antikrieg.TV)',data-video-id:'5YVQkWvs4Tg'},
{title:'Ukraine - Protesters with guns caught on tape 18.2.14',data-video-id:'tfBFMqUl4Dg'},
{title:'Ukraine - Rechter Sektor und Putschisten Regierung arbeiten zusammen unterstützt von EU & USA',data-video-id:'n4x15N2iQ-I'},
{title:'Ukraines War in Donbass Vs  Russias War in Chechnya ll The Difference',data-video-id:'OU3aBvhtWXw'},
{title:'Ukraine - Trauma of War - Donbass Kids',data-video-id:'WyeEz07epVI'},
{title:'Ukraine  USA organisierten den Staatsstreich l Democracy Now',data-video-id:'dwhqwzcGXds'},
{title:'Ukraine - USA wollen den Krieg nach Europa tragen',data-video-id:'m53XxOgIndg'},
{title:'Ukraine - US-Instrukteur für Kiews Soldaten bei der Arbeit',data-video-id:'mjXoZ7g4muo'},
{title:'Ukraine - Verbrennen einer Puppe, die Putin darstellen soll',data-video-id:'Kq4J3Hs6r_c'},
{title:'Ukraine - Will Poroschenko den Transnistrien-Konflikt neu entfachen',data-video-id:'EpTJ2Gc4TRs'},
{title:'Ukrainian Major, military expert Oleksandr Taran - No Russian troops in Ukraine - Stop the War',data-video-id:'y-NUKPa-dV4'},
{title:'Ukrainische Faschisten im Bundeswehrkrankenhaus behandelt',data-video-id:'J2wTWJTKcU4'},
{title:'Ukrainische Faschisten vor dem Parlament in Kiew 19.10.14',data-video-id:'1bRT2xWIbgo'},
{title:'Ukrainische Militärs - Wir beschießen unsere Städte, bombardieren Wohnviertel',data-video-id:'SqLqbTxRgFs'},
{title:'Ukrainischer Botschafter im ARD - Neonazi-Brigaden sind ein Teil unserer Armee',data-video-id:'dnUMo6pziMs'},
{title:'Ukrainischer Journalist ruft im ukrain.TV zum Mord an Ostukrainern auf',data-video-id:'94WlwxYX2tE'},
{title:'Ukrainischer Politiker - Donbass zurückerobern oder unbewohnbar machen',data-video-id:'uyG2BL4iKFo'},
{title:'Ukrainischer Putschist Jazenjuk rechtfertigt sein Regime im Deutschen Fernsehen',data-video-id:'q57SQYwcmhs'},
{title:'Ukrainische TV Show - Ex-General beschreibt die Lage schonungslos',data-video-id:'d9RjpDXLJbk'},
{title:'Unbezahlte deutsche Kriegsschulden gegenüber Griechenland',data-video-id:'2GLq2R5h2jI'},
{title:'Unfassbare Kriegsverbrechen des Westens - Jürgen Todenhöfer _ Peter Scholl-Latour u.a.',data-video-id:'J2O7LSFLu0M'},
{title:'Unmenschliche Politik - Festung Europa',data-video-id:'ybVb32haKj8'},
{title:'UN session on Minsk2 - Russian TV',data-video-id:'PJB1ZsoQ0r4'},
{title:'Unterbringung von Flüchtlingen - Lösungsmodelle',data-video-id:'2LW6h2sTFTc'},
{title:'Unterstützung der ISIS über die Türkei - Deutsche Welle',data-video-id:'hTS2NkLcQD8'},
{title:'Uranium & Phoshor weapons led to cancer rise in Gaza - 21.4.13',data-video-id:'7GvfqXpOEcY'},
{title:'Uranmunition im Irak -  Reaktionen auf den Weltspiegel-Bericht',data-video-id:'C9HTKGQRXYg'},
{title:'Uranmunition und DU in Kriegswaffen - Edmund Lengfelder',data-video-id:'ggM6pGjanPc'},
{title:'USA &  EU unterstützen Nazis in der Ukraine',data-video-id:'O0Rw3jHLsv4'},
{title:'USA führen weltweit Kriege - weitere in Vorbereitung 14.7.14',data-video-id:'y62wAR-I330'},
{title:'USA ll Addicted to War ll Süchtig nach Krieg ll Irak Irak Irak Irak Syrien',data-video-id:'flBRhSF_wNU'},
{title:'USA okkupieren die Erde mit US Militärbasen',data-video-id:'kKHShIYTY1Y'},
{title:'US-Außenministerin  500000 Tote Kinder waren den Preis wert!!! 12.12.14',data-video-id:'8pkSOSxUHws'},
{title:'US-Congressma Grayson - Obama’s draft Authorization for the Use of Military Force against ISIS',data-video-id:'ZKHLifE3P7E'},
{title:'US Drohnen töten von Deutschland aus',data-video-id:'dVebhC6i9lw'},
{title:'US-General a.D. John M. Keane - Russland- u. China-Politik der USA',data-video-id:'4xMjGZbKU6s'},
{title:'U.S. Intelligence knew in 2012 - Rise of ISIS, Arms shipments from Libya to Syria',data-video-id:'tgSnEBqx97k'},
{title:'US-Kongressabgeordnete Gabbard - USA in illegalen Krieg gegen Syriens Regierung verwickelt',data-video-id:'Ppr7AsQm4Xw'},
{title:'US-Kriegsverbrechen Falluja Teil 1 _ Verbotene Nuklear u. Chemiekampfstoffe',data-video-id:'Ys8cusvlMHI'},
{title:'US-Kriegsverbrechen Falluja Teil 2 _ Verbotene Nuklear u. Chemiekampfstoffe',data-video-id:'RU5JDziBKn0'},
{title:'US-Kriegsverbrechen Falluja Teil 3 _ Verbotene Nuklear u. Chemiekampfstoffe',data-video-id:'d09WXBtu59s'},
{title:'US-Militärfilm belegt Biowaffen-Tests an der eigenen Bevölkerung',data-video-id:'OsMgT0OShVc'},
{title:'US-Militär im der Ukraine - Immer aggressivere Unterstützung',data-video-id:'2dEuipnEaDc'},
{title:'US-Politik der Vorherrschaft und die Folgen - Prof. Dr. Massarrat l antikriegTV',data-video-id:'js8AqZDgYuE'},
{title:'US-Politiker amüsieren sich über Krieg und Mord',data-video-id:'CaMqD2j_iXc'},
{title:'US-Politiker Paul zu Syrien - ISIS und Al-Qaida von USA geschaffen u. unterstützt',data-video-id:'xZDidZnqM5Q'},
{title:'US-Politiker Ron Paul - Paris und was getan werden sollte',data-video-id:'MUFjNDzGvBE'},
{title:'US Propaganda in der Ukraine und in Geogien - Ein Vergleich',data-video-id:'tWxSpYbfBR4'},
{title:'US-Senator McCain und die Terrorgruppe ISIS ll Hintergründe ll 28.9.14 (antikriegTV)',data-video-id:'w4RyJFPIKcs'},
{title:'US-Strategie gegen Russland l George Friedman STRATFOR @ Chicago Council on Global Affairs',data-video-id:'o060JXXVQ4U'},
{title:'US-Täuschungspolitik im Kalten Krieg gegen Russsland',data-video-id:'0gqVIMADrRI'},
{title:'US-Wahlkampf - Koch Brothers Milliarden für Republikaner',data-video-id:'DGOSWLlhzaQ'},
{title:'Verdacht auf Giftgaseinsatz durch syrische Rebellen 06 05 13',data-video-id:'p5cH9NAPX5A'},
{title:'Verfahrener NSU-Prozess und die Medien ZAPP',data-video-id:'R_G828Tdyl4'},
{title:'Verfassung aushebeln - Helmut Schmidt + Wolfgang Schäuble',data-video-id:'7YLUbudQfdw'},
{title:'Vergleich der Machtverhältnisse - USA und China',data-video-id:'mnd5chpIMlw'},
{title:'Verhaftungswelle in der Türkei - Einschüchterung der Protestbewegung',data-video-id:'ao6yNIKQotU'},
{title:'Verhör eines gefangenen ukrainischen Sodaten',data-video-id:'hxoXeSmHH8Q'},
{title:'Vermögenspyramide (english) (antikriegTV Kanal2)',data-video-id:'TrkalrZineI'},
{title:'Versäumte Chancen in Partnerschaft EU-Russland - Ehem. Generalsekretär d. Europarates, W. Schwimmer',data-video-id:'1cVcbAaACEg'},
{title:'V-Leute und mögliche Straftaten - Hans-Christian Ströbele, MdB B90_Grüne',data-video-id:'ky87C8_u6ec'},
{title:'Volker Pispers - Antirussische Propaganda der USA',data-video-id:'jFDc83_9434'},
{title:'Volker Pispers ll USA im Endstadium des Kapitalismus ll 2014',data-video-id:'_xDSNyOimjg'},
{title:'Volker Pispers - Skrupelloser Weltpolizist USA - 9_11 und Terrorismus',data-video-id:'L6aNXjYHV50'},
{title:'Volker Pispers - Über Russen, Iraner und US-Amerikaner',data-video-id:'3zqzYrnlnXs'},
{title:'Volker Pispers - Verschwoerung am Fruehstueckstisch (antikriegTV)',data-video-id:'aikYu8GSYlo'},
{title:'Völkerrechtsbruch Kosovo als Blaupause für die Krim -Altkanzler Schröder',data-video-id:'rFy5ZBvUC-0'},
{title:'Von Boko Haram entführt l Schülerin aus Nigeria macht Aussage beim Menschenrechtsgipfel in Genf',data-video-id:'a9PAhjlfKpQ'},
{title:'Von den USA und der EU versuchte Putsch Nr.2 in der Ukraine',data-video-id:'Dr3I5NTSF3s'},
{title:'Vorbild Island Ausweg aus der Krise (22.08.2012)',data-video-id:'mLsh0a_WWgE'},
{title:'Vortrag Renate Bastian - Kriegsgefangene, Zwangsarbeiterinnen, deutsche Deserteure (1939-1945)',data-video-id:'rawt9rgIG0c'},
{title:'Waffenexporte und Nachrichten . Deutschland 12.12.12',data-video-id:'6lNSkGgpz9M'},
{title:'Wagenknecht - Klartext zu Griechenland',data-video-id:'qYIHIp0xJMI'},
{title:'Wahrheiten hinter der Politik - Lisa Fitz - antikriegTV2',data-video-id:'fAzrtlozqZA'},
{title:'Wahrheit über ISIS, USA, Taliban, 11.September, Russland, Ukraine.',data-video-id:'J6Q_fxenrIw'},
{title:'Walther Stützle (SPD) - Wir sind möglicherweise am Vorabend eines großes Krieges',data-video-id:'EPQpcNRw5VM'},
{title:'Warcrimes Iraq - Depleted Uranium du weapons - 21.4.13',data-video-id:'UlTYgqhxUdY'},
{title:'Warnung - Nach dem Dritten Reich droht jetzt das Vierte Reich',data-video-id:'JxDoI-Pzjcs'},
{title:'Warnung vor dem globalen Handelsabkommen „TTIP“',data-video-id:'QxMIyVJOqrA'},
{title:'Was geschah wirklich in Libyen Für was stand Gaddafi',data-video-id:'7zbDLaSEN-c'},
{title:'Was westliche Politik im Orient anrichtet - Michael Lüders, Nahostexperte (antikriegTV)',data-video-id:'Xc1S4sUql7w'},
{title:'WDR 2 Klartext zu Obamas Berlin-Besuch - Politik der Lüge',data-video-id:'2O0c53r5xK0'},
{title:'WDR  - Dirk Müller, die verarschte Bevölkerung (antikriegTV Kanal2)',data-video-id:'NDn1mHSiNsM'},
{title:'WDR  Ukrainisches Militär terrorisiert die Zivilbevölkerung - Europa mitveranwortlich!',data-video-id:'LEH3j8kol8E'},
{title:'Weltflüchtlingstag 2015 Refugees Welcome - Flucht ist kein Verbrechen  Berlin 20.6.',data-video-id:'fKXgo_Vau_A'},
{title:'Weltspiegel Ecuador - Die schmutzigen Hände von Chevron - Umweltverschmutzung im Regenwald',data-video-id:'NsLKhtovAyo'},
{title:'++ Weltweiter Protest gegen Monsanto ++ 25. Mai ++',data-video-id:'lyHDGda0irs'},
{title:'Wem gehört das Geld - Der Andere Neue Fabian',data-video-id:'tKqUi04YIho'},
{title:'Wer hat das Dorf Sartana (Ostukraine) beschossen',data-video-id:'DL-wI68KEwM'},
{title:'Wer hat den Umsturz in der Ukraine gefördert und bejubelt Rückblick',data-video-id:'xtYvWSAEMoA'},
{title:'Westen kontrollierte Ost-Post - Souveränität Deutschlands 20.11.2012',data-video-id:'or3tzI-JvyU'},
{title:'Westliche Propaganda - totale Manipulation ist möglich - Nachdenkseiten',data-video-id:'Dn5a49_6ch0'},
{title:'Westliche Strategie der Einkreisung Russlands',data-video-id:'nAEdV1BkkjE'},
{title:'Wie Banken die Regulierung umgehen - Die miesen Tricks der Finanzaristokratie',data-video-id:'5iQAiKW0wEU'},
{title:'Wie konnte die NSA der mächtigste US-Geheimdienst werden - mit James Bamford • BRAVE NEW FILMS',data-video-id:'ARZYnq02Syo'},
{title:'Wie und warum die USA Kriege anheizen',data-video-id:'f6drI_h0XFk'},
{title:'Wieviel totale Überwachung ist möglich',data-video-id:'1h8SxsrP0cw'},
{title:'Wikileaks Enthüllungen - Uranmunition im Irak - antikriegTV2',data-video-id:'mizQGNqKZrU'},
{title:'William Blum - USA wollen Weltherrschaft seit 200 Jahren',data-video-id:'7kWznShQ0Lw'},
{title:'Willy Wimmer (CDU) - Der Konflikt im Yemen - iran. Rundfunk',data-video-id:'9GK2jqc5g_A'},
{title:'Willy Wimmer (CDU) - Geopolitik und Wiederkehr der Hasardeure',data-video-id:'6dNmQrNBN5w'},
{title:'Willy Wimmer (CDU) - Lausanner Abkommen Iran und G5+1 - iran. Rundfunk',data-video-id:'HDII61ggAdg'},
{title:'Wirtschaftslobbyisten machen Politik und schreiben Gesetze',data-video-id:'Dg2C6DdTaOM'},
{title:'Wirtschafts-Refugees Welcome - Willkommenskultur fürs Kapital - Die Anstalt Sept. 2015',data-video-id:'ieeTSE4rh6g'},
{title:'Wirtschaftsspionage der USA - Geheimdienst-Experte Schmidt-Eenboom',data-video-id:'4PFlTHFcXlE'},
{title:'Wladimir Putin über die USA und andere Feinde des Weltfriedens',data-video-id:'9ickBGWJRKw'},
{title:'Wladimir Putin - Wir akzeptieren keine Weltordnung Made in USA',data-video-id:'kaoXYqVjr2w'},
{title:'Wolfgang Hetzer -  Finanzkrise 2008 (antikriegTV)',data-video-id:'nQVSLlboLUY'},
{title:'World Wealth Report 2012',data-video-id:'cdA853pm7l0'},
{title:'yarmouk',data-video-id:'bmcw7YPXTGc'},
{title:'ZAPP Magazin gegen Russia Today 13.11.14',data-video-id:'cvX9DGi9l2E'},
{title:'Zbigniew Brzezinski - USA befeuern weltweit Konflike',data-video-id:'W-yo6eihwLA'},
{title:'ZDF - Das Deutsch Russische Verhältnis',data-video-id:'5It9C8mtHy8'},
{title:'ZDF Die Anstalt Anticapitalista 1.1.14',data-video-id:'XQ-a0ih0Nn8'},
{title:'ZDF Die Anstalt - Drohnenkrieg ist Frieden 2.2.15',data-video-id:'vTCyzs1S16k'},
{title:'ZDF Die Anstalt - Freihandelsabkommen 4.2.15',data-video-id:'PrWFprp-eMo'},
{title:'ZDF Die Anstalt - Medien & Meinungsmathematik 2.2.15',data-video-id:'q2euIizoGa4'},
{title:'ZDF erklärt Griechenland-Folter - Neues aus der Anstalt',data-video-id:'fayj-dlc2rk'},
{title:'ZDF - Hacker beweisen - Türkei liefert Waffen an Islamisten in Syrien!',data-video-id:'NFd7JuKNYAo'},
{title:'ZDF heute journal   Datenschützer fordern mehr Transparenz 27 06 2013',data-video-id:'sHIORmepoig'},
{title:'ZDF Heute-Show vs. RT-Deutsch - Kostenlose Werbung',data-video-id:'1cwDrmi9bIg'},
{title:'ZDF heute  Überwachung   Datenskandal weitet sich aus   01 07 2013',data-video-id:'bSHmKv8E-_Y'},
{title:'ZDF macht Russland für MH17 Abschuss verantwortlich  10.9.14',data-video-id:'RlhX_9MgcUU'},
{title:'ZDF über Seitensprünge von Sarkozy & Merkel - Neues aus der Anstalt',data-video-id:'gW9fb3Ud5s4'},
{title:'ZDF - Ukrainischer Präsident attackiert Russland im deutschen Fernsehen',data-video-id:'W5eY8hgwM4M'},
{title:'ZDF - USA finanzierten Putsch in Ukraine - Neues in der Anstalt',data-video-id:'T9CXm598q4k'},
{title:'ZDF verharmlost ukrainische Neonazis als politische Hardliner 10.9.14',data-video-id:'0VvUQHS1bJQ'},
{title:'Zugriff im Tunnel - Das tödliches Drama von Bad Kleinen',data-video-id:'_B2eiC5pWTA'},
{title:'Zugriff im Tunnel - Das tödliches Drama von Bad Kleinen (Kurzversion)',data-video-id:'9m6V9sS6VEM'},
{title:'Zur Außenpolitik der Russischen Föderation Fragen an Botschafter Wladimir M. Grinin, Berlin',data-video-id:'J9uha25WNNc'},
{title:'Геополитика - Планы по расчленению России в 1914 и 2014',data-video-id:'H4rjqHddbUE'},
{title:'ヒットラーの米国ビジネスパートナー --- 極秘 - Hitlers business partners from the U.S.',data-video-id:'6-fv28NOMcA'},
