// Define a new module for our app
var app = angular.module("instantSearch", []);

// Create the instant search filter

app.filter('searchFor', function(){

  // All filters must return a function. The first parameter
  // is the data that is to be filtered, and the second is an
  // argument that may be passed with a colon (searchFor:searchString)

  return function(arr, searchString){

    if(!searchString){
      return arr;
    }

    var result = [];

    searchString = searchString.toLowerCase();

    // Using the forEach helper method to loop through the array
    angular.forEach(arr, function(item){

      if(item.title.toLowerCase().match(searchString)){
        result.push(item);
      }

    });

    return result;
  };

});

// The controller

function InstantSearchController($scope){

  // The data model. These books would normally be requested via AJAX,
  // but are hardcoded here for simplicity. See the next example for
  // tips on using AJAX.

  $scope.books = [
    {
      url: 'http://tutorialzine.com/2013/07/50-must-have-plugins-for-extending-twitter-bootstrap/',
      title: '50 Must-have plugins for extending Twitter Bootstrap',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/07/featured_4-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/08/simple-registration-system-php-mysql/',
      title: 'Making a Super Simple Registration System With PHP and MySQL',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/08/simple_registration_system-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/08/slideout-footer-css/',
      title: 'Create a slide-out footer with this neat z-index trick',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/08/slide-out-footer-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/06/digital-clock/',
      title: 'How to Make a Digital Clock with jQuery and CSS3',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/06/digital_clock-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/05/diagonal-fade-gallery/',
      title: 'Smooth Diagonal Fade Gallery with CSS3 Transitions',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/05/featured-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/05/mini-ajax-file-upload-form/',
      title: 'Mini AJAX File Upload Form',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/05/ajax-file-upload-form-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/04/services-chooser-backbone-js/',
      title: 'Your First Backbone.js App – Service Chooser',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/04/service_chooser_form-100x100.jpg'
    }
  ];


  $scope.videos = [
{title:'Die gefährlichste MAFIA der WELT - Die NATO _ Dr.Daniele Ganser',q:'22mFeOo3G-s'},
{title:'12.5. 2015 - Pressekonferenz der Aussenminister John Kerry und Sergej Lawrow',q:'sZnnCoMAiEA'},
{title:'23. März - Begrüßung Alexis Tsipras vor dem Kanzleramt; Solidarität mit Syriza und Griechenland',q:'8DJUg1J5cBw'},
{title:'3 SAT Kulturzeit - Die Wahrheit über Geld (antikriegTV #2)',q:'KKj4RoPbKek'},
{title:'3sat ll Westlicher Qualitätsmedien-Kampagne gegen russische Propaganda',q:'lStWmR452uE'},
{title:'400 US-Söldner in der Ukraine - RT deutsch',q:'3djxDAlc4rA'},
{title:'65% der US-Amerikaner gegen Blockierung des Iran-Atomabkommens',q:'Gw1d5x2CujI'},
{title:'70. Jahrestag der Befreiung vom Faschismus - Russisches TV',q:'5k7ekAJw7xY'},
{title:'7 Punkte Friedensplan Putins ll Jetzt abgelehnt',q:'mHtejc6Izl0'},
{title:'9_11, Bin Laden und die US-Saudi Connection',q:'q0kAvaRfZZ0'},
{title:'911 COVER UP - Shepard Smith - Judge Napolitano - 28 pages',q:'x3-Uh4-cB-k'},
{title:'9_11 - Massive Zweifel der ersten Stunden ll ZDF am 11.9.2001',q:'EjXU6i3H2P4'},
{title:'9_11 Terror - Richard Gage 14. April in Berlin - 2200 Whistleblower fordern neue Untersuchung',q:'AR3wADMAFfo'},
{title:'9. Mai 2015 – 70. Jahrestag des Sieges über den deutschen Faschismus - Treptower Park Berlin',q:'RFOnLCAkHHA'},
{title:'9. Mai 2015 - Blumen am Ehrendenkmal in Berlin-Treptow',q:'F0aLINmBAwc'},
{title:'Activities of foreign secret services - Argentine President C. Fernández to the UN',q:'VeV512GQX-Y'},
{title:'Afghanische Aktivistin Malalai Joya - Chelsea Manning und Edward Snowden sind Helden',q:'_ttN2Ooj_nY'},
{title:'Aktham Suliman - Flüchtlingskrise Folge der US-Politik des Regimechange - Maybrit Illner',q:'60ddnAVkmBM'},
{title:'Aktienexperte Hellmeyer - Ukrainekonflikt deeskalieren! - n-tv Interview',q:'Yh0ZJPbzTIE'},
{title:'Aktion Feuerzauber - Das Celler Loch Part1',q:'u7kUZ6O2eEs'},
{title:'Aktion Feuerzauber - Das Celler Loch Part2',q:'c-_etUzCezU'},
{title:'Alan Goodmann - Left Forum - U.S. Wars of Aggression and Islamic Jihad',q:'0ic29GgSOTg'},
{title:'Albtraum Atommüll.(antikriegTV)',q:'t0Ec4d88qAA'},
{title:'Al Jazeera & Katar - Krieg gegen Syrien - A. Suliman, ehem. Jazeera Korrespondent',q:'D44GTe6fxxE'},
{title:'Allgemeine Erklärung der Menschenrechte',q:'d6uW5u6v9o8'},
{title:'Alpha Blondy - War is Illegal We want Peace in the World - 2015 Reggae Jam',q:'0_WQ3Kf2-7g'},
{title:'alte Version - „DER HERR DER DROHNEN Berliner Compagnie',q:'JWz3TcVQIwc'},
{title:'André Hahn, DIE LINKE - Straftaten durch V-Leute',q:'QGltGtv-Frw'},
{title:'Angela Merkel Marionette der USA ll Mathias Richling',q:'Gnrpfkq95r0'},
{title:'Angela Merkel verkündet das Christentum',q:'HWnzLeU2Mvo'},
{title:'An israelische Armee im Aida-Flüchtlingslager - Vergesst niemals was die Nazis euch angetan haben!',q:'xA7mzcckZlo'},
{title:'Annie Machon - European Parliament Committee - NSA Mass Surveillance of EU Citizens - Sept.30, 13',q:'yQLW5q20l6s'},
{title:'Anstalt Asylrechtsverschärfung 20.10.15 (antikriegTV)',q:'VB4BoCue5xc'},
{title:'Anstalt Aussenpolitik - Syrien, Assad und Regimechange 20.10.15',q:'JskxR_0X8rM'},
{title:'Anstalt - Flüchlingskrise 20.10.15 (antikriegTV)',q:'06TgSiC1eek'},
{title:'Antikriegs-Appell aus Kiew',q:'3mnl7VOeYhk'},
{title:'Antikriegsdemo Berlin 13. Dezember Friedenswinter 2014',q:'qzqpn_p3hOQ'},
{title:'Antikriegsdoku - Sir No Sir Trailer',q:'7Lil1nVk_Vk'},
{title:'Anti-Kriegs-Museum Berlin l antikriegTV',q:'iY8GtqtSzC8'},
{title:'Antikriegsnachrichten  - - -  Anti-War News - Frieden mit Russland',q:'sEdp363PASM'},
{title:'AntikriegTV - Antikriegsnachrichten - Umfassender informieren!',q:'qQNF2bj14IM'},
{title:'Antirussische Berichterstattung der deutschen Presse ll 29 August 2014',q:'YO_5i2fwqZ0'},
{title:'Antiwar USA - Widerstand _ Resistance (antikrieg.TV)',q:'DhZrb5ufRL8'},
{title:'ARD bestätigt Faschisten ll ZDF Claus Kleber lügt ll EU schweigt',q:'NhbdMr8KZo8'},
{title:'ARD Monitor - Geheimoperation Wasser, EU fördert Wasserprivatisierung',q:'JJvASlzH_Z0'},
{title:'ARD_NDR - Hetze gegen Russland getarnt als harmlose Karnevals-Satire',q:'TRB6HT3Jegg'},
{title:'ARD Panorama - Der Preis des deutschen Jobwunders (antikriegTV Kanal2)',q:'upcg00fkdws'},
{title:'ARD - Putin ist kein Partner er ist Gegner 11.11.14',q:'HNGU1flfDlM'},
{title:'ARD - Russische Sorge vor NATO-Osterweiterung berechtigt und legitim',q:'f_0t5JI3WCA'},
{title:'ARD Tageschau  NSA überwacht Deutschland   30 6 2013',q:'DPQkPb4SEDo'},
{title:'ARD Tagesschau   NSA bespietzelt EU    29 6 2013',q:'4-VjEJSbYkg'},
{title:'ARD-Team - Im Folterkeller der US-Soldaten - Irak 2004 (antikrieg.TV)',q:'Jas74InLGus'},
{title:'Argentine President C. Fernández - Who supports terrorists, Freedom Fighters, ISIS in Syria',q:'MZTWZC7uPwM'},
{title:'Armut hat viele Gesichter... Lisa Fitz',q:'y1Yl3JdXaNY'},
{title:'Armut in Deutschland politisch gewollt - Nationale Armutskonferenz Dez 2012',q:'NgKBRaguVM8'},
{title:'Armutsbericht - Kommentar von Markus Preiß, WDR',q:'MeG4kNQsUy8'},
{title:'ASYLRECHT - Kein Mensch ist illegal (antikriegTV)',q:'B36NQ67cOaU'},
{title:'„Asylverfahrensbeschleunigungsgesetz“ - Interview mit Judith Wiebke, Amnesty International',q:'q33Rfmwu3Ss'},
{title:'Attac fordert Moratorium für Zahlungen Griechenlands an IWF',q:'AD9lYGZoNrA'},
{title:'Aufforderung Kiews an Donetsk - Massenexodus Hunderttausender',q:'IHq4ukU9VNM'},
{title:'Aufklärung des NSU und die vielen V-Männer l Die Anstalt',q:'wBhsWGmyYqs'},
{title:'Aufschrei ohne Echo  -  NSA Skandal und die Deutschen 3sat',q:'cTWqaNqAZ5A'},
{title:'Aufstand gegen die Fleischmafia.',q:'BpPVBustP4E'},
{title:'Aunt Boston Marathon Suspect - Bombing Were Staged',q:'4ZteHUx1nrw'},
{title:'Auszüge ARD Monitor - NATO als Kriegstreiber in der Ukraine',q:'fELbgH2rrS8'},
{title:'Baghdad - Deformed Babies born due to Depleted Uranium munitions',q:'zbfFW02wNJY'},
{title:'Bankenlobby und die ungeloeste Bankenkrise - Frontal21 (antikriegTV)',q:'Z8bGvW4jLIQ'},
{title:'Barack Merkel Angela Obama',q:'52nubeKIAyQ'},
{title:'Baroness Ashton of Upholland',q:'k4UmJH3Zeo8'},
{title:'Bashar al Assad about Kobane and ISIS',q:'cdTem6AgX4M'},
{title:'BBC Bericht über die Nazis in der Ukraine',q:'V9sdpDMvcLI'},
{title:'Berlin 18.7.2015 - Protestveranstaltung - EURATOM Nein danke!',q:'A5Bv1VLwppE'},
{title:'Berlin - Ein Gedicht - Internationaler Anti-Chevron Tag - 21. Mai Brandenburger Tor',q:'zYCkY6xrhX8'},
{title:'Berliner KünstlerInnen gegen Krieg - 70 Jahre Befreiung von Auschwitz durch die Rote Armee',q:'M18-vvo4f14'},
{title:'Berlin - Free Chelsea Manning (Wikileaks Whistleblower) - Birthday 2014',q:'HUXgqzVQX6Q'},
{title:'Berlin - International #AntiChevron Day - May 21, 2015',q:'aC-VN3v2u44'},
{title:'Berlin - Solidaridad con Ecuador vs Chevrón - NO al Fraude electoral en Honduras',q:'8Wf1IWEzKuw'},
{title:'Beweis - Nato Osterweiterung wurde ausgeschlossen - Versprechen gebrochen',q:'RL2-nTV2UaE'},
{title:'Bilder tiefer Trauer aus Gorlovka in der Ostukraine - Westen unterstützt Kiews Kriegsverbrechen',q:'PVesuateTBE'},
{title:'Bill Moyers - Geheim-Regierung der USA',q:'3zlI5AtJxfM'},
{title:'Biokrieg für Frieden und Demokratie',q:'Dniyf-ytPJA'},
{title:'Bizarrer Auftritt - Präsident der EU-Kommission Juncker beim EU-Gipfel in Riga, Mai 2015',q:'s-InLkH6wNU'},
{title:'Blackrock Investment - Ungeheure Macht im Hintergrund',q:'Wj3zSf7x2hM'},
{title:'BND im Dienste der NSA (antikriegTV)',q:'vXuBTqbPivU'},
{title:'BND schnüffelt für NSA l Tom Strohschneider ND-Chefredakteur',q:'EINRj2HQRGw'},
{title:'BND-Skandal - Barometer steht auf Sturm _ nd-Chefredakteur Tom Strohschneider',q:'Zhu1xBj8jFM'},
{title:'Börsenexperte Dirk Müller - Griechenland verfügt über immense Gas- u. Ölvorkommen',q:'ki6_flYvMYQ'},
{title:'Börsenexperte Dirk Müller - NSA - BND - Zinswetten - TTIP - Deutsche Bank',q:'TtkVdWjB6DI'},
{title:'Börsenexperte Dirk Müller über die Ukrainekrise',q:'ma12K8My2Ec'},
{title:'Boston bombing - Fox TV - bomb sniffing dogs _ drill before explosions',q:'MUnLu2XHsHM'},
{title:'Boston Bombing Suspect  Father talks of Possible Inside Job',q:'BiRjsKT2xqU'},
{title:'Boston Bombing Suspects Aunt',q:'fGn2EgLjEus'},
{title:'Boston Bombing Suspects Aunt - Show Me the Evidence',q:'hvTEX87pi30'},
{title:'Boston Marathon Suspects Father - Bombing Were Staged TV Interview',q:'Q7oCWHBpJdk'},
{title:'Boston Police - 3rd Explosion at Library',q:'8AbF3l9yYjE'},
{title:'Brandon Bryant, ehemaliger Drohnen Pilot packt aus - Berlin',q:'e3dz63_u_ag'},
{title:'Braune Aussichten - Nazis rüsten sich für NSU-Prozess',q:'whqqrEBsrxc'},
{title:'Brief an Obama - Pascha Champ -  Wir sind für den Frieden!',q:'toS_uyUukl4'},
{title:'Brisante Enthüllungen im NSU-Prozess - Hessischer Verfassungsschutz zunehmend in Erklärungsnot',q:'VpilJRfCF0Y'},
{title:'BR Kontrovers - Trinkwasser in Gefahr, EU will Trinkwasser privatisieren',q:'vz3G6F0haRI'},
{title:'BR Quer - Strom autonom, Bürger treiben Energiewende an (antikriegTV Kanal2)',q:'SdfC8M0_JhU'},
{title:'Bundesjustizministerium - Rechte Vergangenheit frontal21  7.05.13',q:'JlFEPq5D8UM'},
{title:'Bundeskanzlerin Merkel war glühende Jungkommunistin -  antikriegTV2',q:'FP95NXxrL6s'},
{title:'Bundesnachrichtendienst BND und Waffentransporte - Monitor April 2015',q:'Z6em9JsN_HM'},
{title:'Bundesregierung wußte von Totalüberwachung der NSA',q:'KTNgbcO4LQM'},
{title:'Bundeswehr Einsatz ab 2012 im Inneren',q:'kFx8ZFr_OPU'},
{title:'Bundeswehreinsatz Syrien - Jürgen Todenhöfer (Phoenix)',q:'_KCWZLMA1Ig'},
{title:'Bundeswehreinsatz zur Vernichtung syrischer Chemiewaffen',q:'yc-55Pfz_0g'},
{title:'Bundeswehr - Kein Krieg Song',q:'oVa0NEwVMA0'},
{title:'Bush-Kriege _ Obama-Kriege _ Süchtig nach Krieg',q:'sLOrr7nNwJ4'},
{title:'Carl Rove Heckled on Iraq War 21.4.13',q:'JgEUak89uJc'},
{title:'Charlie Hebdo Journalist - One attackers had blue eyes',q:'G7GBZYRYnwc'},
{title:'Chelsea Manning Happy Birthday 2014',q:'nTahQz1kGBw'},
{title:'China - 6-stöckiges Haus in 24 Stundne',q:'X21zBDQQjQE'},
{title:'China und die neue Seidenstrasse',q:'pTJ7_GIHGq8'},
{title:'Chomsky on Intervention, Scahill Blasts Stanley McChrystal - The Struggle #508',q:'xs3MHPhc8ug'},
{title:'Christoph Sieber  Berlin wird  Putingrad',q:'9WJFIXYSV9k'},
{title:'Christoph Sieber - Das gönn ich euch (2012)',q:'u7A1TTjb0M8'},
{title:'Christoph Siebers - Klare und bewegende Worte',q:'f-lX_U7NmPc'},
{title:'CIA Black Operations in Iran',q:'EdA6tGmBHLw'},
{title:'Civil War in Ukraine  Interview with Vyacheslav Nikonov',q:'Qs7EJYIchvs'},
{title:'Clip _ Freundschaft China und Russland',q:'ZeCM1VlmLtg'},
{title:'CNN  Kein Anzeichen für Invasion Russlands - 2.9.14',q:'BQmeZzhNyoc'},
{title:'CODEPINK Protest während der Senatsanhörung zu ISIS 16.9.14',q:'IswjT3cXiMc'},
{title:'Condoleezza Rice -  Gas und Ölkrieg gegen Putin',q:'aF0uYIjaTNE'},
{title:'Coop Antikriegscafe Berlin - Friedensbewegung',q:'kzK478qG_es'},
{title:'COOP Antikriegscafe Berlin',q:'M7_Y_l2HgrI'},
{title:'Craig Roberts - EU ist Teil des US Imperiums ll Medien gesteuert',q:'7pmtfwE7jjk'},
{title:'CrossBorder-Leasing - Privatisierung Wasserwerke - Karusselgeschäft Banken - PPP',q:'aozuRWEY4pc'},
{title:'Damaskus, Syrien - Palästinensische Flüchtlingslager Jarmuk',q:'6cV26qmMB7A'},
{title:'Daniele Ganser - Ressourcenkriege Teil 1',q:'wMpH1X9uUeM'},
{title:'Daniele Ganser - Ressourcenkriege Teil 2',q:'DTQSSbU7rbg'},
{title:'Das britische Abhörprogramm #Tempora  # Prism',q:'w-xIaxe2LW0'},
{title:'Das Buch Ukraine im Visier auf der Leipziger Buchmesse',q:'HSfqyQNchxU'},
{title:'Das Celler Loch ist kein Einzelfall - NDR',q:'JVyzsTEiPeA'},
{title:'DAS IST UNSER HAUS Pitchvideo',q:'vqYSwV6qSpo'},
{title:'David Graeber   Occupy und die 99% - antikriegTV2',q:'70vAnFDzsF8'},
{title:'David Swanson - Left Forum - U.S. Wars of Aggression and Islamic Jihad',q:'9O0V7jAnNRY'},
{title:'Deformed Babies by use of US Uranium Weapons in Iraq DU - (NSFW)',q:'8en1FkCRajY'},
{title:'Demonstration gegen Sparpolitik in Italien - 18.5.2013',q:'CyttQtbMW7Q'},
{title:'Demonstration  in Kiew am 9.4. gegen Klitschko und die Stadtverwaltung',q:'_9emW1YArEY'},
{title:'Depleted Uranium - Birth defects in Fallujah (Guardian)',q:'F9wza2LYyj0'},
{title:'Depleted Uranium - Congressman McDermott HBO Interview - 21.4.13',q:'ZjXMBJDk4LE'},
{title:'Depleted Uranium - Effects in Iraq',q:'ownN8REg5yo'},
{title:'Der Fall Gustl Mollath -  Erwin Pelzig Neues aus der Anstalt ZDF',q:'z_gzV0rfgbI'},
{title:'„DER HERR DER DROHNEN Berliner Compagnie - Veranstaltung im Rahmen der Drohnen-Kampagne',q:'QqTkr3PhDP8'},
{title:'Der Krieg in Syrien - Gespräch mit Karin Leukefeld',q:'IEOuH_hd-SU'},
{title:'Der Krise ein Ende setzten_ Ein spanisches Dorf trotzt mit sozialistischen Maßnahmen der Krise',q:'zxC1bNBuOVs'},
{title:'Der Plan der USA, die Welt zu beherrschen - Teil 1 russ  Doku',q:'xuRcGFk-FPo'},
{title:'Der Plan zur Einkreisung Russlands - Die Welt als Schachbrett',q:'N9sONGYWci4'},
{title:'Der Weihnachtsfrieden von 1914',q:'c5s_xlqGTWg'},
{title:'[deutsch] CBS Interview mit Bashar al Assad, Präsident von Syrien',q:'J0CnGPebsmQ'},
{title:'Deutsche an die Front - Internationaler Frühschoppen 2.2.14',q:'BjAAtwHZusA'},
{title:'Deutsche-Bank - Geschaftsmodell Hunger - antikrieg TV',q:'V8_6Wz-QuZU'},
{title:'Deutsche Bank - Organisiertes Verbrechen  Teil 1  - antikriegTV2',q:'Cag00kAArIQ'},
{title:'Deutsche Bank   Organisiertes Verbrechen  - Teil 2 -  antikriegTV2',q:'3CVR0Tt9nho'},
{title:'Deutsche Interessen im Kampf um die Ukraine',q:'pZr_0wLISgQ'},
{title:'Deutsche Medien verharmlosen Faschisten in der Ukraine 25.9.14',q:'RkMtwPJcPJo'},
{title:'Deutscher Mainstream vs Russia Today',q:'JF1VLq7Tp98'},
{title:'Deutsches Fernsehen berichtet objektiver über Lage in Syrien 30.10.15',q:'L09J5kQflng'},
{title:'Deutschland braucht keine Killer-Drohnen - Jürgen Todenhöfer',q:'H_7dDi8yfsY'},
{title:'Deutschland - Direkte Beschuldigung Russlands MH17 abgeschossen zu haben',q:'wRVw3M3BxJ8'},
{title:'Deutschlands Weg in den Überwachungstaat - Professor Albrecht (antikriegTV)',q:'X5LHa6izPmI'},
{title:'Die Anstalt - April.2015 - Max Uthoff, Claus von Wagner, Christoph Sieber, Carolin Kebekus',q:'3_ZMZvEt91s'},
{title:'Die Anstalt erklärt die Lügen der Wirtschaftsweisen  12.12.14',q:'pGd3vGmcLl4'},
{title:'Die Anstalt - Herzblatt - Einsame Grossmächte und ihre Rebellen 20.10.15',q:'SHfBGfujizk'},
{title:'Die Anstalt l Griechenland, Banken, Troika, Journalisten',q:'REb7PBbOlBg'},
{title:'Die Anstalt - Solo Max Uthoff 20.10.15',q:'zn6-ei6yK4Q'},
{title:'Die Außenpolitik Russlands - S.E. W. M. Grinin, Russlands Botschafter in Deutschland l antikriegTV',q:'NfuLp0r1W28'},
{title:'Die deutsche Atombombe - Auerwerke Oranienburg Teil 1',q:'VFOx7UFKCoo'},
{title:'Die deutsche Atombombe - Auerwerke Oranienburg Teil 2',q:'Ha6GucCYRt4'},
{title:'Die EU ist eine Diktatur    Martin Schulz bei Maybrit Illner',q:'nrUy_JIO6Mg'},
{title:'Die geheimen Krieg der CIA - Im Auftrag der Regierung - mit William Blum • BRAVE NEW FILMS',q:'jJ4VcRaXPrg'},
{title:'Die Geheimverträge G10 zur Überwachung der Bevölkerung - Frontal21',q:'9dwvhC8tzVU'},
{title:'Diego Fusaro, ital. Philosoph -  Die Ursachen der Immigration',q:'WBaMPmpQUL8'},
{title:'Die graue Eminenz Joerg Asmussen - HG Butzko   Kleinkunstpreis',q:'49uYD17P8kw'},
{title:'Die Gründe für Krieg und Terror',q:'pxr4y22meEg'},
{title:'Die Hartz-Maschine - Geschäfte mit der Arbeitslosigkeit',q:'zMK6hZPyKVY'},
{title:'Die Internationale - Rosa-Luxemburg-Konferenz 2014',q:'XPcBQnqvGJ8'},
{title:'DIE LINKE - Bundestag 26.2.2011 -  Afghanistankrieg Abstimmung - antikriegTV2',q:'vemQGzNKu9A'},
{title:'Die Schweiz erlässt keine antirussische Sanktionen',q:'NWtAh9F4OFw'},
{title:'Dieser Kapitalismus geht über Leichen. Lucy Redler, Sozialökonomin',q:'YQsCs57yxkA'},
{title:'Die Spekulationswirtschaft mit mehr als € 500 Billionen',q:'c-U-vTbzqNY'},
{title:'Die Ukrainekrise bereits vor 15 Jahren angekündigt - RT',q:'QsW7yuJD1_U'},
{title:'Die (Un-)Abhängigkeit des Mario Draghi von G30',q:'xpj7Y2_UpEQ'},
{title:'Die USA scheinen die Ukraine zerfallen zu lassen - Rostislav Ischenko (Politologe)',q:'FFugeapN3hw'},
{title:'Die Verbrechen der USA im Nahen Osten ll ZDF Nichts neues in der Anstalt 23.9.14',q:'0nLK-nqvA80'},
{title:'Die Wahrheit über Osama Bin Laden und Al Qaida - antikriegTV2',q:'85KVyTS3Igs'},
{title:'Dirk Müller   Griechenland, Bodenschätze, Nachweise (antikrieg TV)',q:'HDjJlbyRf0g'},
{title:'Dirk Müller vs. Eric Frey ll US-Interessen in der Ukraine',q:'ux7sPm7DFWs'},
{title:'Drohnen-Terrorkampagne - Tod per Joystick',q:'aEyT3T0vYoE'},
{title:'Dr. Seltsams Wochenschau 7. Juli - H.C. Ströbele - Snowden - NSA - PRISM',q:'vDi27WwOaMc'},
{title:'Dr. Seltsams Wochenschau mit Menschenrechtsanwalt H.-Eberhard Schultz - 6.10.13',q:'KntnaBzLsIg'},
{title:'DU - The Silent Nuclear War - Depleted Uranium - Part One',q:'RhD_unMXgCU'},
{title:'DU - The Silent Nuclear War Depleted Uranium  Part Two',q:'jj41wKzPj6g'},
{title:'Earthships New Solutions Official Trailer',q:'IEAVJ_darZg'},
{title:'Easter Peace March Berlin 2014',q:'2hw-o7MPEuw'},
{title:'Ehemaliger NATO-Oberbefehlshaber enthüllt Pentagon-Kriegpläne',q:'1Vr_slBV6kI'},
{title:'Ehem. EU-Kommissar Verheugen - Fatale Fehler im Ukraine_Russland Konflikt ll nTV',q:'mXqpudI8qNw'},
{title:'Ehem. Wehrmachtsangehörige verteidigen Nazi-Deutschland',q:'h-NdFpt74nY'},
{title:'Eindrücke aus Donezk -  RIA Novosti-Korrespondent Armin Siebert',q:'r9RdfRLhqpU'},
{title:'Einreiseverbot für Grünen-Fraktionschefin im EU-Parlament, Rebecca Harms',q:'UAuL7w6jlko'},
{title:'Endlich berichtet das ZDF über zivile Opfer 14.7.14',q:'n-scwgfTeQk'},
{title:'Endstation Bad Kleinen - Versagen deutscher Sicherheitsorgane',q:'QyoSdaA-9Ro'},
{title:'Erdogans Propaganda - Nicht Russland sondern die Türkei kämpft gegen Islamischen Staat',q:'87zsQMP1egs'},
{title:'Erfolgreichste Talkshow der Ukraine - Wir können Putin nicht für alles verantwortlich machen!',q:'JhTeOQEXcUk'},
{title:'Ermächtigungsgesetze - Neues aus der Anstalt 6.4.13',q:'77VtaGdIU8U'},
{title:'Erwin Pelzig - Geheimverträge vs  Whistleblower ll 7 10 14 ZDF',q:'uDH5oFz1c4Y'},
{title:'Erwin Pelzig - Rasmussen, die lügende Hämorrhoide 9.9. 2014',q:'IRzRYAct9Sc'},
{title:'Erwin Pelzig über die Mitte der Gesellschaft - Weihnachts- und Neujahrsansprache',q:'G6z66j0GH0Q'},
{title:'Erwin Pelzig  Willkommen im Kriegswinter 2014 ll 9.9.14',q:'KeqjyNoWYRA'},
{title:'Eskalation Ukraine - US-Militär bereits vor Ort',q:'n181zzq_4FE'},
{title:'Eskalierende globale Ungerechtigkeit',q:'AcocTsxEftA'},
{title:'EU Commission head Junker - Relations with Russia ‘must be improved,’ US ‘can’t dictate’',q:'2svx1JiuDo0'},
{title:'EU entscheidet sich gegen Netzneutralität - kommt das Zweiklasseninternet',q:'OtJe419qMNs'},
{title:'EU-Kommissionspräsident Juncker - Man muss Russland anständig behandeln',q:'pZvjFtU5Csk'},
{title:'Euromaidan-Aktivisten feiern den Tod Putins vor der russischen Botschaft in Kiew',q:'luhAPi1uM3E'},
{title:'Ex-Bundesminister von Bülow - Brücke Berlin-Moskau',q:'WXhR0HWT92M'},
{title:'Ex-Jugoslavia - Depleted Uranium NATO Bombs',q:'31GQFj0bMFI'},
{title:'Ex-Minister Andreas von Bülow zur geopolitschen Lage',q:'RDJav3yNmQg'},
{title:'Ex-President Carter Regularly Speaks with Putin About Syria',q:'RVu92KJiZ_k'},
{title:'extra3 NDR ll Der Ami-Shooter - Globaler Krieg ll 17.9.2014',q:'Ncdtp_rm_Mg'},
{title:'Fakten zum Abschuss der russischen Su 24 durch die Türkei',q:'grEj8W8lhhs'},
{title:'Fallbeispiele Terrorismus Made in USA l antikriegTV',q:'eZBEfDDhGG8'},
{title:'Fälschung - Ukrainisches TV angeblicher Schwerverletzter - Tragödie von Wolnowacha',q:'Z2lLu_7O_rM'},
{title:'Fernsehkritik tv über Syrien Berichterstattung von ARD und ZDF (antikrieg TV)',q:'OB42o2QClyI'},
{title:'Flächenbrand Naher u. Mittlerer Osten.. #1 Gespräch mit Karin Leukefeld',q:'Ri0qdRaZZZM'},
{title:'Flüchtlingskrise massgeblich auch von Berlin verursacht – Unterfinanzierte Hilfsprogramme der UN',q:'d-dfNWZeTgc'},
{title:'Flüchtlingskrise u. die Verantwortung Deutschlands - Rechtsanwalt Dr. Matthias Lehnert (Sputnik)',q:'Ut4tWe65oa8'},
{title:'Flugzeugkatastrophe MH17 Ukraine - Christian Wehrschütz, Journalist, ORF',q:'tqBFfRfh47A'},
{title:'Fox Propaganda - Putin persönlich befahl Nemtsov-Ermordung. Säuberungen wie zur Stalin-Ära',q:'CHGXbCnpxE4'},
{title:'Free Bradley Manning - Collateral Murder - Wikileaks',q:'cNm3uVl6saU'},
{title:'Free Bradley Manning Protest während Obama-Rede am 22.8.2013',q:'ct1ArZeBkzs'},
{title:'Free Chelsea Manning Stop Watching Us Berlin - Diani Barreto 18.11. 2013',q:'ibw9uXESz-I'},
{title:'Free Mumia Rede von Jamal Hart - Rosa-Luxemburg-Konferenz 2014',q:'W3S9AqbfUyo'},
{title:'Freihandelsabkommen EU-USA - Neoliberale Globalisierung - Günther Sölken 17.8.13',q:'qjYCn3jQ60I'},
{title:'Freundschaft Schröder & Putin ll Deutschland & Russland',q:'b-HzxENWTx0'},
{title:'Frieden statt NATO – Für eine #Weltfriedenskonferenz #WorldPeaceConference',q:'GKpvs0jCOfs'},
{title:'Frontal21 -  Bankenlobby und die ungelöste Bankenkrise',q:'oDY9x7phgPg'},
{title:'Frontal 21 - Dschihadist und V-Mann zugleich .. Elmar Theveßen über SITE',q:'t2MEDrjjh3w'},
{title:'Frontal 21 - Dunkle Seiten von Justiz & Psychiatrie  Dez 2012',q:'3noDkGdoa6U'},
{title:'Frontal 21 - Totalüberwachung Deutschlands _ US-Firmen beteiligt 1.11.14',q:'BGHFcm4mDTk'},
{title:'Full Disclosure - Al-Qaeda in Syria, the Story You Havent Heard - Ben Swann',q:'MKfmiMVtKf8'},
{title:'G8 Gipfelstürmer - Die Blutigen Tagen von Genua.',q:'Zy1eUuCV4Fk'},
{title:'Gabriele Krone-Schmalz bei Maischberger und Russlandfeinden',q:'yevzUw_AO8Q'},
{title:'Gabriele Krone Schmalz ll Militarisierte Politik u. diffamierter Pazifismus',q:'BOIrE1UQBlE'},
{title:'Gabriele Krone Schmalz ll Über Russland und was guten Journalismus ausmacht ll Phoenix',q:'olBqyauqNYs'},
{title:'Gabriele Krone Schmalz - Verständnis für Russland haben',q:'hBDz0IgV_ko'},
{title:'Gebet des ukrainischen Nationalisten - Maidan Bataillon Gelöbnis',q:'6hClu3L7SAo'},
{title:'Gegen Krieg und Rassismus - Berlin Soundstrike Jam Session 26.6.15',q:'786Fwyf_1Xo'},
{title:'Geheime NATO Waffenlieferungen an IS über Bulgarien _ Türkei - Kurdische Meldungen aus Syrien',q:'7Pwi5SbR3c0'},
{title:'Geheime Partisanenarmee des BND (1von3) -- Schattenkrieger der Nato',q:'7BARnjo3e1E'},
{title:'Geheime Partisanenarmee des BND (Teil 2_3) -- Die Schattenkrieger der Nato',q:'xPkLu3udTcc'},
{title:'Geheime Partisanenarmee des BND (Teil 3_3) -- Die Schattenkrieger der Nato',q:'Xt1uityfE6E'},
{title:'Genscher - Verständnis für Putin, Schluss mit Sanktionen ll Phoenix 21.9.14',q:'85N-pH07-w4'},
{title:'Geopolitische Hintergründe der Ukraine Krise - Oberstleutnant a. D. Jochen Scholz l antikriegTV',q:'s80xIyE6fUA'},
{title:'George Friedman (Stratfor) - Die nächsten 100 Jahre',q:'68DnyBKOPWo'},
{title:'Georg Schramm - Fakten reden Klartext -  Neues aus der Anstalt (antikriegTV) 3.10.13',q:'oaXDM_8ii54'},
{title:'Georg Schramm - Iran',q:'ssKDxkRrTgA'},
{title:'Georg Schramm - Krieg Reich gegen Arm - Kleinkunstpreis 2013',q:'c5By3zLGoJ4'},
{title:'Georg Schramm - Systematische Volksverdummung durch die Medien',q:'X9uQiv4DCCs'},
{title:'German Minister Accuses Qatar of Funding ISIL - Germany later officially apologies to Quartar',q:'kRD1IFa1aP0'},
{title:'Germans to the Front - Deutsche Luftwaffe voll bewaffnet an russischer Grenze',q:'cHn8uLNhENs'},
{title:'German TV ll  Satire Show about warmongering Ukraine Media Coverage',q:'wf4fntYVvvY'},
{title:'Germany aids US spying on Europeans - Darnell Stephen Summers',q:'CvYZUJs8S8s'},
{title:'Geschäfte mit geächteten Waffen - Deutsche Rüstungsunternehmen und die Streumunition',q:'fclmhKIbXTY'},
{title:'Geschichte der Kriegslügen der US-Präsidenten',q:'W6DQc-pxWtU'},
{title:'Gesine Schwan über die Hetze gegen Griechenland  -  Monitor, Juli 2015',q:'q-koQEnL9vE'},
{title:'Gespenst der totalen Überwachung   ZDF heute Journal 7.8.13',q:'NHE3fP58Z-s'},
{title:'Gladio - Attentate unter falscher Flagge - Italien - antikriegTV2',q:'GGPZe7XX95A'},
{title:'GLADIO . Teil 1 (antikriegTV)',q:'SM5SYnVvPCY'},
{title:'Global Wave Kernwaffen abschaffen! Aktionen in Städten weltweit',q:'SzIxVnTbABg'},
{title:'Goldman Sachs in Griechenland (antikrieg TV)',q:'LC__Wt-Su_s'},
{title:'Goldman Sachs Verschwörung - Neues aus der Anstalt - antikriegTV2',q:'966DSq_mSNk'},
{title:'Goldpreis Manipulation',q:'w5oFhTzwueE'},
{title:'Gorbatschow - Kriegsgefahr! - Russland wird provoziert ll Schweizer Fernsehen 17.9.14',q:'D_m1EB9YsZY'},
{title:'Greenspans späte Einsicht (antikrieg TV)',q:'XijcVpdnn3Y'},
{title:'Gregor Gysi - 70 Jahre nach Ende des Nationalsozialismus',q:'IZ944dUkHhc'},
{title:'Gregor Gysi - Deuschlands Politik von aussen bestimmt',q:'mNicdDpsttk'},
{title:'Gregor Gysi - Flüchtlinge, Krieg und Hunger - Umdenken gefordert',q:'ZwzcQGYC-oQ'},
{title:'Gregor Gysi Sanktionen gegen Russland sind lächerlich',q:'MxQTV1gSrcQ'},
{title:'Gregor Gysi über die Ziehväter von ISIS, al-Nusra und al-Qaida',q:'Cu8lqVB16oM'},
{title:'Gregor Gysi zu Griechenland - Aschermittwoch',q:'b-tgNouEHGI'},
{title:'Griechen fordern Wiedergutmachung von Deutschland (antikriegTV)',q:'iKrXFUyCXq8'},
{title:'Griechenland am Vorabend einer Revolution in Europa',q:'naL9SAeJRKA'},
{title:'Griechenland - Bodenschätze , Erdgas, Erdöl - Mr. DAX - antikriegTV2',q:'9poJQsIMrag'},
{title:'Griechenland_ Der Hunger hält Einzug',q:'QahXnMhxUuY'},
{title:'Griechenlandkrise - Dirk Müller zu den neusten Entwicklungen',q:'k1rP4VqEVKY'},
{title:'Griechenlandpoker - Schäuble heimlich gefilmt - - Vorsicht! Man glaubt uns nicht',q:'DP76hiMFsuo'},
{title:'Griechenland - Widerstand gegen deutsche Besetzung (antikriegTV)',q:'Wua2kAI7o74'},
{title:'Group of Thirty G30 - Mario Draghi und Goldman Sachs - antikriegTV2',q:'s-hrFkv7in4'},
{title:'Grundlagen der US-Aussenpolitik - Michael Lüders, Politik- u. Islamwissenschaftler',q:'gOrWsKAqJSs'},
{title:'Günter Grass  - System zerstört sich selbst  - antikriegTV2',q:'JolW3YbX82E'},
{title:'Gustl Mollath und das Schwarzgeld',q:'Zmuk1QJfBXo'},
{title:'G.W.Bush zum Thema Folter und Renditions - antikriegTV2',q:'H9Ae-D7XTAw'},
{title:'Gysi - Völkerrechtswidriger US-Drohnenkrieg aus Ramstein organisiert',q:'eGEHdO-ZCT0'},
{title:'Hagen Rether - Krasser geht nicht ll Nordkorea und die USA ll 27.9.14',q:'pYf1XJl5wCA'},
{title:'Hagen Rether  über die USA',q:'A-E2mEsa-7g'},
{title:'Hand in Hand - Ukrainische Nazis, Poroschenko, Merkel, Obama, EU',q:'d7EA8POeeZM'},
{title:'Harald Lesch -- Zins_Zinseszins - Perfektes Verbrechen',q:'XrD_ewkJKHA'},
{title:'Harald Schmidt & Obama Bin Laden',q:'QYTSVwUNXR4'},
{title:'Hassausbruch in Kiew - Frau aus Lugansk wird als Lügnerin beschimpft',q:'007MVXVxtZo'},
{title:'Heereskommando Anti-Russland Propaganda ll ZDF Neues aus der Anstalt 23.9.14',q:'OlTtMPt8Jvg'},
{title:'Heiner Flassbeck - NEIN zum Neoliberalismus',q:'fEuvxNG41Zs'},
{title:'Heino Wiese (SPD) - «Russland – Menschen und Orte in einem fast unbekannten Land»',q:'osCUcKasyAU'},
{title:'Herbert Grönemeyer - ISIS ist Resultat westlicher Politik',q:'a8yRCFVSYa0'},
{title:'Herrschaft durch Angst - Noam Chomsky',q:'Bflie94UNyE'},
{title:'Hillary Clinton - Unterstützung der USA für Al Quaida und IS, den Islamischen Staat',q:'hO9_36Qhktk'},
{title:'Hillary Clinton   We created Al Qaeda',q:'edBqxGJb8YY'},
{title:'Hintergrund Putsch Ukraine - Wer waren die Todesschützen - Teil 1',q:'5H8lwazZWic'},
{title:'Hintergrund Putsch Ukraine - Wer waren die Todesschützen - Teil 2',q:'X71PxGCJHFI'},
{title:'History of US-Surveillance - Darnell Stephen Summers, Vietnam Veteran, Stop The War Brigade',q:'s2OcBuV7Oic'},
{title:'Hitler ist wieder da - Die Anstalt',q:'ia03DTw6ICQ'},
{title:'Hitlers Helfer - Kult um ukrain. Kriegsverbrecher u. Juden-Mörder Bandera u Waffen-SS-Division l ARD',q:'KrWbHlJvLiM'},
{title:'Hitler und Griechenland - Frankfurter Allgemeine Sonntagszeitung',q:'4TAIfW5fKRI'},
{title:'How Anti-War is the United Nations - David Swanson (World Beyond War)',q:'T76QOcF_cRY'},
{title:'idx.html',q:''},
{title:'Inside Job german Trailer',q:'mV8mSsb5KSg'},
{title:'International Action Day Berlin - Support Bradley Manning & Edward Snowden - Diani Baretto 7_27_2013',q:'izVAcRGDsVI'},
{title:'Intern. Kräftekonstellation Naher u. Mittlerer Osten.. #3 Gespräch mit Karin Leukefeld',q:'pVYsmQeaG60'},
{title:'In wie vielen Ländern hat die USA militärisch interveniert • mit Stephen Kinzer • BRAVE NEW FILMS',q:'1JWSHLfPVXc'},
{title:'Irak März 2003 - Völkerrechtswidriger Angriffskrieg _ Kriegsverbrechen',q:'pWuzXaX1Jg4'},
{title:'Irak - Uranmunition - das strahlende Vermächtnis - Weltspiegel (antikriegTV)',q:'ljUoJnMlg1Y'},
{title:'Iranians affected with depleted uranium toxic air',q:'JZ3VFaWboFk'},
{title:'Iraq - Cancer caused by Depleted Uranium munitions used by US-military',q:'piukk3Oqmi4'},
{title:'Irrsinn der Wirtschaftssanktionen gegen Russland',q:'e_8rRsH-wYM'},
{title:'ISIS’ Toyota Mystery Solved - US State Department shipped Toyotas to “Free Syrian Army”',q:'V9k9HbHMZqg'},
{title:'Islamexperte Michael Lüders - Terrorziel Europa - Terror unterstützt vom Westen',q:'TphauUqyRdw'},
{title:'Island Revolution 2012 kriminelle Bankster zur Rechenschaft gezogen',q:'_DnLCcj4_Go'},
{title:'IS-Milizen drohen Menschen mit Mord, verabreichen Drogen und zwingen zu kämpfen',q:'acnmmFaYLgk'},
{title:'Israel and Palestine - Information',q:'JdGyQZ86CFc'},
{title:'Israel und Palästina - Norbert Blüm spricht Tacheles - antikriegTV2',q:'x40YSu7rEsE'},
{title:'Iwan Rodionow (RTdeutsch) Rosa-Luxemburg-Konferenz',q:'g1ySXiWaFH4'},
{title:'Jakob Augstein bei Precht - Ukraine und Poroschenko 30.11.14',q:'vVe6YlpGeMc'},
{title:'Jean-Claude Juncker - Ohrfeigen beim Gipfeltreffen „Östliche Partnerschaft“',q:'AV9nRJVb6X4'},
{title:'Jean Ziegler  auf der G7 Demo - Juni 2015',q:'FFYnLr6NXN4'},
{title:'Jemen - Saudische Kampfjets verhindern zivilen Hilfsflug aus dem Iran',q:'uRSD7VX7B6w'},
{title:'Jeremy Scahill Interview - Berlin October 2013',q:'PiPBipV2aic'},
{title:'Jesse Ventura  ENOUGH OF THIS WAR CRAP!-STYnG5WMvOI.mp4.part',q:'5WMvOI.part'},
{title:'Jetzt offiziell - US-Waffenlieferungen an die Ukraine',q:'gRkj32Q3X5s'},
{title:'John McCain - Arm Syrian Rebels to Shoot Down Russian Planes (Oct. 2015)',q:'PKcgbqdEOJ8'},
{title:'Journalist Christian Wehrschütz im Donbass - Bankrotte Ukraine _ Flüchtlingselend',q:'8Q1_BLqzqzI'},
{title:'json',q:''},
{title:'J. Todenhöfer - Welche Geheimdienste stehen hinter dem IS (Islamischer Staat)',q:'Fv7TWC1NX3o'},
{title:'Jüdische Gemeinde Thessaloniki fordert Entschädigungszahlungen der Deutschen Bahn',q:'N8axSFqTp2Q'},
{title:'Julian Assange Interview - Die Zukunft der Überwachung 12.12.12',q:'DFyMT0ETrKQ'},
{title:'Juli Zeh zur NSA Affäre',q:'6u76_YRcFKw'},
{title:'Jürgen Todenhöfer bei der IS - Größte religiöse Säuberung geplant',q:'21guT36nTIw'},
{title:'Jürgen Todenhöfer bei Pelzig - Oktober 2015',q:'BxSg6iP5TWo'},
{title:'Jürgen Todenhöfer -  Der Krieg gegen den Islam  - antikriegTV2',q:'Dtv_0KINEgA'},
{title:'Jürgen Todenhöfer - Der Terror in Paris und die Hintergründe',q:'SuPRwgAlFOw'},
{title:'Jürgen Todenhöfer - israelische Armee begeht Kriegsverbrechen',q:'fieBnL7VhZ0'},
{title:'Jürgen Todenhöfer - Offener Brief an alle Kriegspolitiker der Welt',q:'xg2VCqwOSRc'},
{title:'Jürgen Todenhöfer - Sieger in Afghanistan ist der militärisch industrielle Komplex',q:'nYGky7eiONM'},
{title:'Jürgen Todenhöfer über die Bombenorgie in Gaza',q:'K_Hl-clIOpE'},
{title:'Jürgen Todenhöfer Westen ist selbst schuld am Terror der Islamisten',q:'hVXO4--bvrg'},
{title:'Justus Frantz über Putin, Weltkrieg und Sanktionen gegen Russland.',q:'8yBAUGpmx08'},
{title:'Kabarettist Uwe Steimle - Russland, Merkel, Kriege, USA, Flüchtlinge',q:'99iQ52WpRZw'},
{title:'Kabarretist Christoph Sieber über die Realität',q:'5jER649Nens'},
{title:'Kai Ehlers - Russische Einsätze in Syrien – kleiner Kommentar zur großen Lüge',q:'rLeiwMEudfs'},
{title:'Kampfroboter und Drohnen - Krieg der Zukunft 2.4.13',q:'4inEBSUg-Qk'},
{title:'Kampf um Souveränität - Evo Morales, Präsident des Plurinationalen Staates Bolivien (Wien 2012)',q:'blIyqqG5CFk'},
{title:'Kanzlerin Merkel schwört USA die Treue',q:'oLHrTG6pNK4'},
{title:'Kaveh - Soundstrike Berlin gegen Rechts (antikrieg.TV)',q:'LEir53QVVEU'},
{title:'Keine Nabucco Pipeline sondern Abhängigkeit',q:'BUc6UsieTi8'},
{title:'Keine Sanktionen gegen Russland! Wirtschaftskammerpräsident Leitl',q:'MakSf9N2WfQ'},
{title:'Keine Sanktionen gegen Russland! Wirtschaftskammerpräsident Leitl  - OK',q:'R1_vSnyYUxQ'},
{title:'Kein Krieg in meinem Namen!',q:'EXx007AnswM'},
{title:'Kein Krieg in meinem Namen!',q:'qKKajttiXn4'},
{title:'Kiew - Antikriegspartei im Parlament ll Mikrofon abgestellt',q:'X_FRFEcQiPQ'},
{title:'Kiew legalisiert die Anwerbung ausländischer Söldner - antikrieg TV',q:'TUuHf5RwoQI'},
{title:'Kiew TV-Talkshow debattiert offen über Kriegslügen - Ukraine ruiniert',q:'ZFZmRLyyujs'},
{title:'Kiew, Ukraine - Polizisten unter Beschuss von Neonazis - 22 1 14 (antikrieg.TV)',q:'lx6R5nFiIuU'},
{title:'Kiew will Mauer an der Grenze zu Russland errichten',q:'QVSqJF0VE_Q'},
{title:'Kinder Bataillon ll Ukrainischer Volkssturm 5.9.14',q:'oP33u6dGZ7M'},
{title:'Kinderprostitution - Vertuschte de Maiziere (CDU) Verstrickungen von Politikern (Kontraste, ARD)',q:'KWiQijckYKM'},
{title:'Kindersoldaten bei den Rebellen in Syrien (antikriegTV)',q:'RYq7SF2JtPA'},
{title:'Kissinger - Kiew ist Generalprobe für Regimechange in Moskau (antikrieg.TV)',q:'yo5_ct7R6Ng'},
{title:'Kissinger - Regimechange in Kiew . Moscow next target (antikrieg.TV)',q:'ghj3y_BpGaA'},
{title:'Klitschko bringt Nazi Grußformel zurück nach Deutschland',q:'5HqZMLt8yxE'},
{title:'Kobane - Pässe ausländischer ISIL-Kämpfer mit türkischen Ausreisestempeln - Sky News 26.10.14',q:'BgXZoog5JcY'},
{title:'Konstantin Wecker u. R. Düringer   Überwachung, Griechenland, Krise, Staatsgewalt - antikriegTV2',q:'RSOvs2ssFCE'},
{title:'Krasse Fakten - Verbindungen zwischen der Türkei und IS (Islamischer Staat)',q:'NEgxEohgBXM'},
{title:'Krieg ist geil - Supergeil (antiwarpropaganda copyleft)',q:'0Evx9LIyMW8'},
{title:'Krieg ist illegal - War is illegal',q:'xZjugSQ9bNQ'},
{title:'Krieg nicht in unserem Namen - Gabriele Krone-Schmalz - Wir müssen uns wehren!',q:'llpdnC7rVeQ'},
{title:'Kriegspopaganda gegen Syrien entlarvt  Professor Meyer im ZDFspezial 29.8.13',q:'gzY_gkq5INQ'},
{title:'Kriegspropaganda Chemiewaffen in Syrien - ARD Monitor',q:'UEzb3zy03Es'},
{title:'Kriegspropaganda gegen Syrien erklärt 30.8.13',q:'0IQFkaiG1qE'},
{title:'Kriegspropaganda Kleber ZDF vs Siemens Chef Kaeser',q:'hwBHr-G2s2A'},
{title:'Krieg stoppen - Dazwischen gehen - DFG-VK',q:'3XA_F6mNHEI'},
{title:'Kriegstreiber Brok - Offene Aggression Russlands mit regulären Truppen in der Ukraine',q:'G4Ie64kkSho'},
{title:'Kriegstreiber Schockenhoff über Intervention Russlands in der Ukraine',q:'uhTGO3_bL_Y'},
{title:'Krim Sezession - Gerhard Schröder vs Josef Joffe (Zeit)',q:'aohNEBM0Ha4'},
{title:'Krimtour 2015 - Frieden mit Russland - крымтур 2015',q:'KXh4Uy-aGp8'},
{title:'Krise für 99% = Eldorado für 1%',q:'smyXk3ZI6E8'},
{title:'Krisenopfer  Die neuen Hausbesetzer in Spanien',q:'V0IVRHaPoJg'},
{title:'Kritische ARD-Berichterstattung über ukrainischen  Bandera Nazi Kult',q:'Ym6k4HKSZog'},
{title:'Kurz ueber das Wichtigste zu Schiefergas Fracking',q:'Mkp9CDBBHpo'},
{title:'«La Bestia» Güterzug für Migranten aus Zentralamerika Richtung USA',q:'n4qS6CiYfPs'},
{title:'Lafontaine - Verfassungsschutz soll CDU_CSU überwachen - antikriegTV2',q:'gizFRhnL6MM'},
{title:'Lage in Syrien - FM 88,4 StudioAnsage MEGAspree on Air 1.10.13',q:'kAYdRl4H290'},
{title:'Lampros Savvidis - Neuste Entwicklungen in Griechenland',q:'he-N5MWKxnU'},
{title:'Legale Bankgeschäfte oder organisierte Kriminalität (antikrieg TV)',q:'krwZQqsnI0U'},
{title:'Legale Steuertricks - Google, Apple, Starbucks und Co.',q:'n8JNYQruqh0'},
{title:'LESCH UND WIR - Herrscher über Milliarden',q:'UlibpUKBLc8'},
{title:'Lets make money - Filmausschnitt - Hermann Scheer (antikriegTV Kanal2)',q:'BTbmZzj6wcc'},
{title:'Linke Utopien - Precht diskutiert mit Sahra Wagenknecht',q:'hOmINGMGcL8'},
{title:'Lobbyismus - Abgeordnetenkorruption in Deutschland',q:'emjSxEBMREc'},
{title:'Machtkampf der Oligarchen in der Ukraine - Zweite Front',q:'X842LKiwF2k'},
{title:'Machtkampf in Kiew - Söldner-Bataillon Dnepr-1 stürmt Staatskonzern UkrNafta',q:'Asi1ty85X9o'},
{title:'Malaysia - Umgang mit Senioren',q:'KluQA_vxtHo'},
{title:'Manifestacion Berlin - Las manos sucias de Chevrón en Ecuador 30.11.13',q:'c66PCRN8lVQ'},
{title:'Maria do Socorro Gomes Coelho - Presidente Conselho Mundial da Paz',q:'XV97OlRk4GM'},
{title:'Mark Lombardi   Künstler auf den Spuren der Mächtigen  - antikriegTV2',q:'Rb2ZBn3DbUE'},
{title:'Massaker im Gewerkschaftshaus in Odessa - Eine Überlebende berichtet',q:'FqBl-aaT5dY'},
{title:'Massenmord im Mittelmeer (Rotfuchs)',q:'6NuyIuzVIRQ'},
{title:'Massive Proteste gegen ukrainische Armee - Mädchen von Spähpanzer überfahren',q:'_qT1B2F2fdw'},
{title:'Max Uthoff (Die Anstalt) Über den Journalismus und dessen Niedergang',q:'ixo0jq3OOXY'},
{title:'Max Uthoff - Ukraine und die deutsche Qualitätspresse im Drogenrausch',q:'68QYPNZD9sI'},
{title:'MC King David calling for Peace and Justice - antikriegTV',q:'ZLn89jZjDBU'},
{title:'Medienkrieg in der Ukraine gegen TV-Sender mit russ. Programm (antikriegTV)',q:'YXxbGfe72W8'},
{title:'Medien und Politik ll Strippenzieher im Hinterzimmer',q:'FN3dSjZl5wU'},
{title:'Merkel - Russischer Präsident Putin ist beim G7 Treffen unerwünscht',q:'nk0dSE2ezPQ'},
{title:'MH17 Abschuss - Doch Kiew verantwortlich Hochrangiger SPÖ-Politiker fordert vorbehaltlose Aufklärung',q:'0MXtjKKnvCQ'},
{title:'#MH17 EXPLOSIV  OSZE Beobachter entdeckt an der Boeing Maschinengewehr-Einschüsse',q:'DkupbOoOl1o'},
{title:'#MH17 wurde mit Maschinengewehr beschossen - CBS Canada TV ll #Ukraine',q:'WIoH0Ep6XkU'},
{title:'Michael Lüders (Sicherheitsexperte) zur Krise in der Ukraine',q:'6MRFUM-ViCM'},
{title:'Michael Lüders zur brutalen Politik der USA',q:'PyqS8zobPpM'},
{title:'Militärisch industrieller Komplex der USA will Ausweitung der Kriege',q:'u9h3BzNJass'},
{title:'Militär und Abschottung gegen Wirtschaftsflüchtlinge - Die Anstalt Sept. 15',q:'Pch3Rxxo1GU'},
{title:'Millions Die in the Congo -  U S Role - The Struggle #509',q:'kz2JVojXPfc'},
{title:'Mit offenen Karten - Der Waffenhandel (antikriegTV Kanal2)',q:'1dbNjg8GIG4'},
{title:'Monitor (ARD)   Grenzenlose Überwachung durch NSA   Was wusste die Bundesregierung    04 07 2013',q:'9T3FzYpAkvU'},
{title:'Monitor - Deutschlands neue militaristische Politik (antikrieg.TV) 21.2.14',q:'7aIBVt5yFNQ'},
{title:'Monitor_ Geschäft mit dem Hunger 30.8.12',q:'XcC6Ok5aGgI'},
{title:'Monitor - Menschenrechte  Zusammenarbeit mit Diktaturen',q:'pBT4fgeDiXc'},
{title:'Monitor - Neue Atombomben für die deutsche Bundeswehr 19 06 14',q:'yAwts76aGlg'},
{title:'MONITOR - Scharfschützen in Kiew',q:'UR5T6VhtPlc'},
{title:'Morde in Deutschland - Wer terrorisiert hier wen - Die Anstalt',q:'_7P-xAo-sQI'},
{title:'Mr. Dax - Banken und Politik - antikriegTV2',q:'RU5kDoRB5-U'},
{title:'Multinational companies buy Greek mines at bargain prices',q:'K8XSQIE2Kvs'},
{title:'Muslime in Deutschland',q:'hFRRjIIViSI'},
{title:'Mütter gegen den Krieg - Brigitte Queck - Buchvorstellung',q:'SEAZd-fWFhs'},
{title:'NachDenkSeiten ll Albrecht Müller ll Gefaht durch manipulativen Kampagnenjournalismus',q:'KQbHYzlbqVE'},
{title:'Nachdenkseiten - „Sozialausgaben auf Rekordhoch gestiegen“ – Lügen mit Zahlen',q:'skLjwlqsOvU'},
{title:'Nach Protesten von 250.000 Demonstranten - „Spiegel Online“ diffamiert TTIP-Kritiker (Nachdenkseiten)',q:'se-PIjEAZ_g'},
{title:'Nachrichten aus der Ostukraine - 4. April 2015',q:'GN4mpeC6PnI'},
{title:'Nachrichten aus der Ostukraine _ Krim 24.11.15',q:'NbyVde2smCI'},
{title:'Nachricht von Mumia Abu-Jamal vom 26. April 2015 - Prison Radio',q:'kPSeVTaNgjs'},
{title:'Nächste Ausflug nach Stalingrad ll Christoph Sieber 30.8.14',q:'vi45jBQgOHg'},
{title:'NATO - Analyse der Opposition in Deutschland - Alexander Neu, DIE LINKE',q:'3ryv7O2svVM'},
{title:'NATO-Geheimarmee - Bombenlegerprozess Luxemburg - Sat3',q:'aQ6I8poqcMo'},
{title:'NATO Geheimarmee GLADIO - Bombenlegerprozess in Luxemburg - TV Sat3',q:'BIxOACTjroU'},
{title:'NATO General a.D. Kujat - Russland als Supermacht akzeptieren - Jan. 2015',q:'BAMIj5lTdFM'},
{title:'NATO General a.D. Kujat über gefälschte Beweise der USA gegen  Russland',q:'asEQ4lt4b6o'},
{title:'Nato Gipfel Chicago 2013 - US Kriegsveteranen werfen ihre Orden weg',q:'uZjLBD-oDAA'},
{title:'Nein zum Kapitalismus - Jean Ziegler _ Heiner Geissler',q:'oWh5JVfauwY'},
{title:'Neonazis und Holocaust-Leugner - Wahrheit macht frei  - Nieder mit dem Faschismus',q:'WJb0cGdAee0'},
{title:'Netanyahu Admits his Countrys Alliance with Saudi Arabia',q:'JRpeA77WTeY'},
{title:'Neues aus der Anstalt   Pelzig umgeht ZDF Verbot und zählt EU für den Wasserwahn aus 3 08 min',q:'284hgD4PlDU'},
{title:'Neues aus der Anstalt ZDF 29.4.14',q:'dh279AiSujw'},
{title:'Never Before Seen Footage 9_11',q:'tFTOFPds4eU'},
{title:'New York Protest - Dont Attack Syria! - Sept.8, 2013',q:'raWtjau_IyU'},
{title:'Nie wieder Krieg zwischen Deutschland und Russland',q:'L3K8R-vMs4c'},
{title:'Nie wieder Krieg zwischen Russland und Deutschland #2',q:'1L_hCAE67WY'},
{title:'NO al Fraude electoral en Honduras - Berlin 30. Noviembre',q:'h-GS5F61WRs'},
{title:'Noam Chomsky - Hat Grass recht',q:'kgXjytYa-9o'},
{title:'Noam Chomsky im Interview 25.6.13',q:'vlufl9ui4kw'},
{title:'Noam Chomsky - Schurkenstaat USA betreibt globale Ermordungskampagne  mit Kampfdrohnen',q:'vl2PnLq9JuE'},
{title:'Noam Chomsky - US-Drohnenkrieg, Folter und Terror - Politik des Iran',q:'lrVqLD2_jsg'},
{title:'Noam Chomsky - Weltweit gefährlichste Terror-Organisation heißt nicht „IS“ sondern ...',q:'Jm3fiiBMZ9w'},
{title:'Noch mehr Fragen - G8 Gipfel Genua Sommer 2001 - antikriegTV2',q:'s2cZLJUNGGc'},
{title:'#NoSpyAbkommen (antikriegTV)',q:'yWF0BrHKliE'},
{title:'Novinsky, ukrain. Oligarch gibt Poroschenko die Schuld am Tod der 70 Maidan-Toten',q:'uCkkifeb8P8'},
{title:'NS-Geheimsache Uran - Atomjagd in Brandenburg - Teil 1',q:'zTRIz-qX3g4'},
{title:'NS-Geheimsache Uran - Atomjagd in Brandenburg - Teil 2',q:'DnmzDvfgPFQ'},
{title:'NS-Geheimsache Uran - Atomjagd in Brandenburg - Teil 3',q:'sv-LEndwa34'},
{title:'NSU Prozessbeginn - brisante Hintergründe',q:'EBhgNwfweeo'},
{title:'NSU-Prozess - Die Engstirnigkeit bayerischer Richter',q:'vASx7-XeWG8'},
{title:'Nulands Hirn - Antikriegsgedicht',q:'el1SL-FXYhQ'},
{title:'Obama Jokes About Predator Drones At The 2010 White House Correspondents Association Dinner',q:'cm033GVNX3w'},
{title:'Obama - Russland  Feind der zivilisierten Welt',q:'3ZBxt0_XHjA'},
{title:'Obamas Videobeweise  für chemische Attacken in Syrien',q:'eFCxMPWPa1c'},
{title:'Occupy Police   United We Stand - antikriegTV2',q:'oBrEK1n6L1w'},
{title:'Oles Busina, ermordeter ukrainischer Journalist, Schriftsteller l Russ. TV',q:'19_OTGIRMps'},
{title:'Online Demo – Stoppt den Fremdenhass – Jürgen Todenhöfer',q:'zxqY-QNZ4aM'},
{title:'Oskar Lafontaine  Bush und Blair sind Terroristen!',q:'J8IWe5drYmI'},
{title:'Oskar Lafontaine Gute Nachbarschaftspolitik zu Russland!',q:'7yH5j23CcP0'},
{title:'Oskar Lafontaine - Türkei darf die IS-Mörderbande nicht weiter unterstützen - bei Maybrit Illner',q:'zVbPgqGySOk'},
{title:'Oskar Lafontaine über verlogene US-Politik - bei Maybrit Illner',q:'M9GBBOcZexY'},
{title:'Oskar Lafontaine - Westen muss aufhören Interventionskriege zu führen und Waffen zu exportieren',q:'p9Gar82Q-hI'},
{title:'Ostukraine l Kinder leben aus Angst vor Beschuss im Atombunker',q:'e9U5u31DoR0'},
{title:'Ostukrainer - Jazenjuk und Merkel in den Haag vor Gericht stellen',q:'gyEXl-C5QAQ'},
{title:'Ostukraine - Verbrechen der faschistischen “Ajdar” Kämpfer',q:'WV7V31mTDjo'},
{title:'Ostukraine - Zerstörungen in Perwomajsk',q:'EUYiAl9H9a8'},
{title:'Otpor  Gesteuerte Revolten Ukraine, Venezuela, Syrien, Iran  1 antikriegTV',q:'b2zBdvCYE-g'},
{title:'Otpor - Gesteuerte Revolten Ukraine, Venezuela, Syrien, Iran #1 (antikrieg.TV)',q:'EzmcPNC2Skk'},
{title:'Otpor - Gesteuerte Revolten Ukraine, Venezuela, Syrien, Iran #2 (antikrieg.TV)',q:'FgZJa4EQwPA'},
{title:'OXI-Party im Karl-Liebknecht-Haus in Berlin am 5.Juli 2015 - KIEKE MA FILM BERLIN',q:'wVUGN-N_fMI'},
{title:'PAN - Krieg (antikriegTV)',q:'hgpanuQRh94'},
{title:'PAN - mix',q:'NqsyPzJU6co'},
{title:'Panorama - Russland Krise - Mai 2015',q:'5unAFGZ8RRA'},
{title:'Panorama - Syrien - Flüchtlinge - Frontex',q:'jX_rlxigKQI'},
{title:'Parteitag DIE LINKE  - Sahra Wagenknecht, Christiane Reymann (antikriegTV)',q:'URLWMv6EyTY'},
{title:'Pelzig Lieber den Russen vor der Tuer als den Ami in der Leitung (antikriegTV)',q:'rpzFz2PGgEs'},
{title:'Pensionierter US-General fordert - Anfangen Russen zu töten!',q:'uczLeBo2sgo'},
{title:'PEOPLE OF THE WORLD STOP THE WAR',q:'OXCk6mh1XJ4'},
{title:'Perfide Medienlügen zum Thema Flugzeugabsturz MH17',q:'JhjN3baw57M'},
{title:'Peter Gauweiler (CSU) - Russland miteinzubeziehen wäre wichtig gewesen',q:'r8moNa6Di6Q'},
{title:'Peter Scholl Latour - Ukraine, Russland, China u. Iran',q:'imAhis-coX4'},
{title:'PKW MAUT und Massenüberwachung (antikriegTV)',q:'NHL1jrxtq84'},
{title:'Plant Kiew Angriff auf Russland S-300 Flugabwehrraketen einsatzbereit',q:'9VrBDAPpWKI'},
{title:'Platz der Unabhängigkeit Kiew Ukraine - Neonazis (antikrieg.TV)',q:'3m8XEJ_0lSE'},
{title:'Polen bereitet sich auf den Krieg mit Russland vor',q:'CRGMzsNTCgA'},
{title:'Polizeibeamter mit Kontakten zur Pegida-Bewegung',q:'ECjC9ICwYYM'},
{title:'Polizeigewerkschaftsboss - Facebook wird von CIA finanziert (antikriegTV)',q:'9xFf410iH9g'},
{title:'Portugals Nelkenrevolution - Viva Portugal - (antikriegTV)',q:'5l5zCd_wVXk'},
{title:'p.pl',q:''},
{title:'PPP - Public Private Partnership (antikriegTV)',q:'MvzjBqAk8fE'},
{title:'Präsident Ecuadors kritisiert US-Sanktionen gegen Venezuela - antikriegTV',q:'eGxuaBmIrNA'},
{title:'Präsident Putin - Bau von South Stream Pipeline abgebrochen',q:'rfaTf5Z186k'},
{title:'Präsident Rafael Correa - Ecuadors #Antichevron Kampagne',q:'LDxyPGW-1Wk'},
{title:'#PRISM Demo anläslich Obamabesuch in Berlin  19 6 2013',q:'zZ4xO5_AbVs'},
{title:'#PRISM Demo   Cornelia Otto 19 6 2013',q:'R7RRmqvGwXc'},
{title:'Prism - Spionagesoftware der USA',q:'y4UVgZynbQM'},
{title:'Prof. Dr. Manojlo (Moskau) - Ukraine von neonazistischen Gruppen kontrolliert',q:'y0Dn2IFfKRI'},
{title:'Prof. Foschepoth, Historiker ll #NSA, alliertes Recht in Deutschland ll ARD Tagesschau',q:'jV3VRBjUOb4'},
{title:'Prof. Michel Chossudovsky Part 1 - Rosa Luxemburg Konferenz Berlin 2014',q:'U1UHS9wWZXo'},
{title:'Prof. Michel Chossudovsky Part 2 - Rosa Luxemburg Konferenz Berlin 2014',q:'cSHup56PqqM'},
{title:'Prof. Noam Chomsky - US-Aggression gegen Russland - verständliche Politik Russlands',q:'sdSxKHYkjDI'},
{title:'Prof. Noam Chomsky (USA) - Griechenland und das Schuldenregime Europa',q:'151ENsX7S1w'},
{title:'Propaganda-Chemiewaffen Syrien - J. Hippler, Politikwissensch._Friedensforscher - ARD Monitor',q:'7I85FdOOQHI'},
{title:'Propaganda im US-Fernsehen - Putin und Assad schuldig an Flüchtlingskrise',q:'ReH6ofWm6T0'},
{title:'Propaganda und Falschmeldungen über Syrien 2013',q:'alkyY86ngno'},
{title:'Propaganda - WeiWei - PussyRiot - Femen - Euromaidan - Antichina - AntiPutin',q:'IVlBN71WFKg'},
{title:'Proteste in der Türkei - Brutales Vorgehen der Behörden - 4.6.13',q:'sl--oRXd2XY'},
{title:'Putin als Liebhaber',q:'Nu16xN5Tzxo'},
{title:'Putin Berater Glazjev  Russland will keinen Krieg! Hochgefährliche Situation l RT',q:'gHP4uMrLTqI'},
{title:'Putin Der Präsident Teil 1 - Russ. TV Kanal Rossija 1',q:'ugYi9mIvQSk'},
{title:'Putin Der Präsident Teil 2 - Russ. TV Kanal Rossija 1',q:'evGrf8AGQLI'},
{title:'PUTIN IST NICHT UNSER FEIND - Jürgen Todenhöfer',q:'LL2JIgn8amU'},
{title:'Putin Versteher Mathias Broeckers packt aus',q:'ttAf_GKif1A'},
{title:'Putschgefahr in Venezuela',q:'AkL6UzWuTgs'},
{title:'Quadrokopter-Drohnen Experimente -  ETH Zürich',q:'sgMAy1jR6ZQ'},
{title:'Radpanzer - Unbemannt, autonom operierend, serienreif (antikriegTV)',q:'OFXkjJZxuyQ'},
{title:'Ranghöchster US-General - ISIS wird  unterstützt von wichtigen arabischen Verbündeten (Sept.2014)',q:'lAU1EIGhWAI'},
{title:'Rapper aus Moskau unterstützen Putin',q:'RBVLeV3rc5Q'},
{title:'Razzia bei der Deutsche Bank am 12.12.12 - Zinsmanipulation(LIBOR)',q:'TYBttOtDQpQ'},
{title:'Razzia bei der Deutschen Bank Tagesausblick - Dirk Müller Mr. Dax (antikriegTV Kanal2)',q:'YdpK2xOJh6s'},
{title:'RBB Abendschau  Yes we Scan Chor   die PRISM Demo in Berlin   18 06 2013',q:'CKC9mcbp-II'},
{title:'Rechter Terror in Griechenland - Aufstieg der Chrysi Avgi',q:'FiBPWCXaXbw'},
{title:'Recycling von Kunstoff zurück zu Öl',q:'AtPdA5f4ZUk'},
{title:'Regierung dementiert - Atomwaffen in Büchel - ARD Monitor',q:'nA_d_3i3H4g'},
{title:'Regierungskriminalität und das Ende des Rechtsystems (antikrieg TV)',q:'CIlJhFNOa5w'},
{title:'Report München ll Smartphone als Super-Wanze',q:'P1UkCV91WfA'},
{title:'Revolutionen Made in USA - Wo die nächste',q:'3vhZUfZcWpo'},
{title:'Rhetorische Mobilmachung der NATO gegen Russland ll gefälschte Satellitenfotos der USA',q:'_djOMcOrKKA'},
{title:'Richard David Precht ll Rhetorik des Kalten Krieges extrem gefährlich',q:'aKigr_77YHg'},
{title:'Rick Rozoff - Nuland Instructed U.S. Envoy On Ukrainian Government Makeup',q:'shCYy7XpAe4'},
{title:'Riesige Gasvorkommen in Griechenland - Gezielte Destabilisierung - Dirk Müller',q:'jpJSx9-1V0U'},
{title:'Rod Starz _ Rebel Diaz - Refugees & Western Imperialism',q:'6s9LYcOq5Hc'},
{title:'Roland Dumas - Syrien Konfilkt seit langem geplant - 10  Juni 2013)',q:'FLlmLtIRNRA'},
{title:'Rome - Protests against austerity - May, 18, 2013',q:'QiYuP-bfObg'},
{title:'Ron Paul - Ukraine MH17 & what the Media Wont Report About',q:'34H69LoLAM8'},
{title:'Roseanne Barr - Die Wahrheit über Hollywood und Manipulation',q:'PzAWqJqxDaI'},
{title:'Russian President Putin at Waldai Disscussion Forum (Oct.2014)',q:'lvhjO-LHBNk'},
{title:'Russian President Putin on Ukrainian Crisis -  Feb 23',q:'d0wnNCCdHcs'},
{title:'Russian President Putin - Ukrainian army is NATO legion (english)',q:'MikMsGZeTBA'},
{title:'Russische Kriegsreporter in Syrien',q:'iVruPXqKGcI'},
{title:'Russischer Generalstab - Türkischer Su 24-Abschuss schwere Straftat',q:'_CHvjFBdwHg'},
{title:'Russland als Großmacht in einer multipolaren Welt -  Prof. Dr. Schröder (Uni Freiburg)',q:'nxe2UOhQVaM'},
{title:'Russland _ NATO  Neuer Kalter Krieg  ll  Monitor',q:'Jlcdtt6lsF4'},
{title:'Russlands Aussenminister - USA üben wegen Russland massiven Druck auf alle Länder aus -',q:'q5Tg3Q-PT7A'},
{title:'Russlands Außenminister - Was wollen die Deutschen',q:'3b3sHx3Ym40'},
{title:'Russlands geopolitische Rolle ll Interview Sergei Glasjew l antikriegTV',q:'EQSDQUsTS-Q'},
{title:'Russlands Präsident Putin - Aggressive Kräfte versuchen Russland zu destabilisieren',q:'CrN89PvAepo'},
{title:'Russland Versteher Max Uthoff und Claus von Wagner',q:'_UQclNdQNg4'},
{title:'Russland wie eine Orange zerlegen - Deutscher Plan Orangene Revolution l Ana von Keitz',q:'UI8qge4OE5w'},
{title:'Russ TV Erster Kanal USA planen Krieg gegen Russland',q:'zYF5NBKJKUE'},
{title:'Russ. TV - Neuer Kalter Krieg = Totaler Krieg des Westens gegen Russland',q:'GXBzzuIGEtI'},
{title:'Sahra Wagenknecht - Bundeswehreinsatz in Syrien ist völkerrechtswidrig',q:'aVkuJgptYso'},
{title:'Sahra Wagenknecht, DIE LINKE - Griechenland, Ukraine, Russland',q:'hcKo3lQ3US0'},
{title:'Sahra Wagenknecht - Zur falschen Politik der EZB l 22.1.15',q:'Mvel1-WMPUU'},
{title:'sample1',q:'WVT9ZUzw5AQ'},
{title:'Sanktionen gegen Russland gegen Interessen Deutschlands',q:'gQaZ08vMuDQ'},
{title:'Sanktionspolitik gegen Russland ll Monitor über die Doppelmoral',q:'iXNShg2xsKo'},
{title:'Sardiniens Geheimnis -  Nato-Schießplatz Quirra - Teil 2 - antikriegTV2',q:'1zQ4jYdGgmk'},
{title:'Saudi first suspected in Boston Martathon bombing deported for reasons of national security',q:'TwhqGv8p-SE'},
{title:'Scheinheilige EU-Flüchtlingspolitik - 10 Euro Nahrung pro Person_Monat in Syriens Nachbarländern',q:'eyM1s0A0Tsc'},
{title:'Schluss mit den Kriegen - Britische Kriegsveteranen',q:'_I2CPuMiUCE'},
{title:'Schmidt Helmut bei Beckmann - Auszug 4.5.13',q:'kpFBTMmWkX0'},
{title:'Schröder_Merkel Amtsübergabe - Tresor, Geheimunterlagen und Berlusconis Uhren',q:'F7BZz-XeR7A'},
{title:'Schweizer TV - Ukraine Reportage von Ch Wehrschütz  12.12.14',q:'26LBn34Xkns'},
{title:'Schwerer Beschuss der Wohnviertel Nähe Flughafen Lugansk - OSCE vor Ort',q:'B3H9CXqpBj8'},
{title:'Sigmar Gabriel und seine TTIP-Täuschungspolitik',q:'gJhTMCxNBs0'},
{title:'Situation von Geflüchteten in Deutschland und an den EU-Außengrenzen - Maik Bischoff',q:'wz-Nmc9itRE'},
{title:'Sky News Interview with Syrian and Foreign Wahhabi Radical Jihadis Captured in Syria',q:'Xca00-TUVfQ'},
{title:'Snowden - Geheimhaltung, Kriegsverbrechen, Folter - Chelsea Manning_Sam Adams Award',q:'7csI5QF7PCE'},
{title:'Soziale Gerechtigkeit _  Neid und Gier - Wilfried Schmickler 09.12.12',q:'h3KlgJAtisE'},
{title:'Spanische Arbeitskräfte in Berlin',q:'HQKc2w0GEUw'},
{title:'Spiegel TV Journalist steigt aus',q:'WMN0CdNdvzg'},
{title:'Spionageaffäre - Die Vertuschung der BND-Hilfe für die NSA 29.04.2015',q:'hwSFeszKSi8'},
{title:'Spionage der NSA offiziell erlaubt  Frontal 21 ZDF 30.7.13',q:'jwEfz5ulKw0'},
{title:'Ständige Publikumskonferenz Medien  Warum gegen Russland',q:'7xpKGvmm_cI'},
{title:'Stefan Kretzschmar zum Ukrainekonflikt ll Unsere Medien sagen nicht die Wahrheit',q:'3EPYdqAb70g'},
{title:'#StopWatching Demo am Samstag 27 07 2013',q:'9Q02rqSxSQo'},
{title:'Störsender -  Kernenergie  - Dieter Hildebrandt',q:'gj_2_eH7QbE'},
{title:'Störsender - Steueroasen - Dieter Hildebrandt',q:'t6AU2NZll9Q'},
{title:'Strategie Weltherrschaft Made in USA - Oberstleutnant a. D. Jochen Scholz l antikriegTV',q:'IZJbAOwx17s'},
{title:'STRATFOR - Kaukasus - Die Grundlagen der Geopolitik',q:'MsJKf5xPYbQ'},
{title:'Super-Mario, Goldman Sachs und Supereinfluss-Reiche',q:'QFd38m72ERA'},
{title:'Syrian refugees - We Didnt Leave Because of Assad - Terrorists made us refugees',q:'IbBNwCn6W94'},
{title:'Syria WMD - False Flag Attack - Ron Paul, US-politician',q:'_b65WPor1Ww'},
{title:'Syrien 2011 - Die Sozial- und Wirtschaftspolitik #4 Gespräch mit Karin Leukefeld',q:'2PdNkTBGARA'},
{title:'Syrien - Al Kaida Ableger erobert Palästinenser-Lager Yarmouk in Damaskus - antikriegTV',q:'Hz4qG3M4TmY'},
{title:'Syrien - BBC - Rebellen zwingen Gefangene zu Selbstmordattentaten',q:'FFPI4WxqsCs'},
{title:'SYRIEN - Chemie-Waffen - Klartext Prof. Günter Meyer',q:'KePy6FbYqEs'},
{title:'SYRIEN - Chemie-Waffen - Monitor - Klartext Prof. Günter Meyer',q:'mMiW-oEAK5I'},
{title:'Syrien   Der Täter steht schon fest',q:'qm-LHSrOn88'},
{title:'Syrien - Friedensforscher Daniele Ganser zu Obamas Kriegserklärung',q:'SkTmT8ODDy0'},
{title:'SYRIEN - Giftgas - Michael Lüders, Politik u. Islamwissenschaftler, bei Beckmann',q:'beWnF4bjpMw'},
{title:'Syrien Hintergrund -  Peter Scholl Latour 4.5.13',q:'MGtYUq1uMpY'},
{title:'Syrienkonflikt - US-Eliten verfolgen unterschiedliche Interessen (theRealNews)',q:'B_pGhMGk99g'},
{title:'Syrienkonflikt - US-Journalist stellt Obamas Führungsrolle in Frage',q:'Nmb2GHWHZAE'},
{title:'Syrienkrise - Harald Kujat (General a.D.) und Wolfgang Gehrcke, MdB',q:'W2UraTrfvJE'},
{title:'Syrien - Mythos Moderate Rebellen und Freie Syrische Armee - Harte Fakten',q:'cUdlEly68co'},
{title:'Syrien Propaganda-Berichterstattung ARD & ZDF',q:'bUGE5jZImG0'},
{title:'Syriens Präsident Assad - Interview 2015 - Westen will keine Partner sondern Marionetten',q:'aupk9SG_WeY'},
{title:'Syrien und Irak - Kriegspropaganda im Vergleich',q:'0xgEVKi1aJE'},
{title:'Syrien - Wer sind die Terroristen Von der FSA (Freie Syrischen Armee) und Al-Nusra Front (PBS)',q:'sFQ9YD7OssU'},
{title:'Syrische Frau attackiert US-Senator McCain wegen dessen Kriegshetze',q:'HMYgezBxrwg'},
{title:'Syrische Kriegsflüchtlinge - Hintergründe (antikriegTV)',q:'xD92dQz5zIk'},
{title:'Syrische Opposition und die Al Kaida, ZDF',q:'9WwlGIJ42ZI'},
{title:'Syrischer Präsident Bashar al Assad  - Interview',q:'cNa7tHzTMQo'},
{title:'Tacheles Berlin - antikriegTV',q:'C5RgasOen84'},
{title:'Tacheles zum Gaza Konflikt und Antisemitismusvorwürfen',q:'RBoTyYK_Pps'},
{title:'Tagesschaue -  Anti Terror Datei - Nov. 2012',q:'dMvArAA1w0g'},
{title:'Tagesschau - Supergeil - Propaganda - Supergeil',q:'n5TmCJw8Q84'},
{title:'Tagesthemen -  gegen den Iran - antikriegTV2',q:'eVzY27yDE68'},
{title:'Tagesthemen PR Desaster - Freiwilligen Bataillone ll 1.10.14',q:'GH5ELim57D4'},
{title:'Tagesthemen trommeln gegen Syrien - antikriegTV2',q:'mO_rgjPfUss'},
{title:'Terroranschlag Paris - Vorwarnungen (Beschreibung beachten)',q:'zrYzoZebTAY'},
{title:'Terror-Milizen erobern syrische Provinzhauptstadt Idlib',q:'UJNy-Cv4RQk'},
{title:'Terrormiliz IS  - Islamischer Staat - Militärische und wirtschaftliche Macht',q:'gwbomBsr0_I'},
{title:'The Role of the BBC in the Syrian Conflict',q:'UdjBPm-dqV4'},
{title:'Thomas Roth versucht Präsident Putin zu provozieren - Georgienkrise',q:'Z3fqFUVx604'},
{title:'Todenhöfer, Augstein und Gysi über die deutsche Medienlandschaft',q:'iIdkAo4i7Go'},
{title:'Tötung durch Drohnen - Fall von informeller Todesstrafe  - Johannes Feest',q:'Rf1jJDJ-Kw8'},
{title:'TTIP   Geheimakte Freihandelsabkommen',q:'3Tm2RHuW4x8'},
{title:'TTIP und Drohnen lügen nicht - ZDF Heute Show',q:'6KuxnTfs25I'},
{title:'Türkei - Beweise für Erdogans unterstützt des Islamischen Staat',q:'qzLuIRYO2tk'},
{title:'Türkei - Bilder der anhaltenden Proteste 2.6.13',q:'DkxoxMnxeNQ'},
{title:'Türkei bombardiert die Feinde des Islamischen Staates IS - Monitor',q:'P_YK7nweeDE'},
{title:'Türkei unterstützt Anti-Assad Kämpfer - Whistleblower Chefredakteur Dündar',q:'iDq2adZpmlQ'},
{title:'Türkei unterstützt Terroristenmiliz IS  - Ehem. NATO-Oberbefehlshaber Wesley Clark',q:'jx6JUt_7xos'},
{title:'TV-Hetze gegen Muslime in den USA',q:'JZ1z5YyrWXI'},
{title:'Überlebender Yezide berichtet über Massaker durch ISIS',q:'Sa36BXc__N4'},
{title:'Über Russland - Hart aber fair 9.9.14',q:'1_VLUN0bEPw'},
{title:'Ukraine - Abgeordneter von Bewohnern wegen Mobilmachung verprügelt',q:'abXNxU0KYJc'},
{title:'Ukraine - Berichte über zunehmende Proteste gegen die Regierung',q:'hcwQtVj-kpA'},
{title:'#Ukraine - Bewaffnete unter den Demonstranten in Kiew 18.2.14 (antikriegTV)',q:'dsAUdmxGXyE'},
{title:'Ukraine - Brutale Gewalt gegen Polizei in Kiew 18.2.14 (antikriegTV)',q:'wzl0NayIT3o'},
{title:'Ukraine - Ehem. US-Nachrichtendienstler bezweifeln Anschuldigungen gegen Russland',q:'mQL4ZU5gA_o'},
{title:'Ukraineeinsatz bewaffneter deutscher Fallschirmjäger und Drohnen ll 6.10.14',q:'4YsNs2vQKxU'},
{title:'Ukraine - Festgehaltene keine Mitglieder der OSZE-Mission - OSZE-Sprecher Neukirch',q:'mWeU_4UEAq8'},
{title:'Ukraine -  Gewalttätige Pro-EU Demonstrationen Januar 2014',q:'6ljK1OvuJpI'},
{title:'Ukraine - Julia Timoschenko - Autor Frank Schumann - Stimme Russland',q:'BqbrRbaCfYQ'},
{title:'Ukraine; Kampf um das Gas - Monitor 13 3.14',q:'s35HkTCByk0'},
{title:'Ukraine - Kiew entzieht Euronews die Sendelizenz - antikriegTV',q:'KR09zNwwmXE'},
{title:'Ukraine, Kiew - Gewalteskalation der Neonazis (antikrieg.TV)',q:'hFfokKSbeHQ'},
{title:'Ukrainekonflikt - Bremer Landesbank Chefökonom Hellmeyer',q:'bPWkAppvkfw'},
{title:'Ukraine-Konflikt - Vortrag von Gabriele Krone Schmalz l Harzsparkasse Dez. 14',q:'FRNeQuJ7CEk'},
{title:'Ukrainekrise - Österreichs Grüne gegen jede weitere Eskalation der USA',q:'awtX-1d_kPI'},
{title:'Ukraine - Krone-Schmalz - Unverantwortlicher Journalismus',q:'18tUv7kr5Xs'},
{title:'Ukraine - Lebensniveau massiv eingebrochen',q:'iJiPNbzepA4'},
{title:'Ukraine; Massive Proteste von Soldaten, Müttern und Ehefrauen. Massive Verluste',q:'4coa9zc_pJg'},
{title:'Ukraine - MH17 Augenzeugen berichten von Kampfjet ll russ. sprachiger BBC',q:'KdSH_ajncuA'},
{title:'Ukraine - Mütter gegen Krieg',q:'8kEWXmEw1a8'},
{title:'Ukraine - Nationalistische Kampfer bereiten sich auf den Krieg vor',q:'Q43GJJzZFBc'},
{title:'Ukraine, NATO-Kriege ll Mitternachtsspitzen - Wilfried Schmickler   30 8 14',q:'4zSpiaXgRzI'},
{title:'Ukraine Nazi like torture techniques used in Kramatorsk against POWs and civilians sitting in pits',q:'R2BECdCONiU'},
{title:'Ukraine; Neonazis attackieren Stadtverwaltungsgebäude von Kriwoj Rog (antikrieg.TV)',q:'5YVQkWvs4Tg'},
{title:'Ukraine - Protesters with guns caught on tape 18.2.14',q:'tfBFMqUl4Dg'},
{title:'Ukraine - Rechter Sektor und Putschisten Regierung arbeiten zusammen unterstützt von EU & USA',q:'n4x15N2iQ-I'},
{title:'Ukraines War in Donbass Vs  Russias War in Chechnya ll The Difference',q:'OU3aBvhtWXw'},
{title:'Ukraine - Trauma of War - Donbass Kids',q:'WyeEz07epVI'},
{title:'Ukraine  USA organisierten den Staatsstreich l Democracy Now',q:'dwhqwzcGXds'},
{title:'Ukraine - USA wollen den Krieg nach Europa tragen',q:'m53XxOgIndg'},
{title:'Ukraine - US-Instrukteur für Kiews Soldaten bei der Arbeit',q:'mjXoZ7g4muo'},
{title:'Ukraine - Verbrennen einer Puppe, die Putin darstellen soll',q:'Kq4J3Hs6r_c'},
{title:'Ukraine - Will Poroschenko den Transnistrien-Konflikt neu entfachen',q:'EpTJ2Gc4TRs'},
{title:'Ukrainian Major, military expert Oleksandr Taran - No Russian troops in Ukraine - Stop the War',q:'y-NUKPa-dV4'},
{title:'Ukrainische Faschisten im Bundeswehrkrankenhaus behandelt',q:'J2wTWJTKcU4'},
{title:'Ukrainische Faschisten vor dem Parlament in Kiew 19.10.14',q:'1bRT2xWIbgo'},
{title:'Ukrainische Militärs - Wir beschießen unsere Städte, bombardieren Wohnviertel',q:'SqLqbTxRgFs'},
{title:'Ukrainischer Botschafter im ARD - Neonazi-Brigaden sind ein Teil unserer Armee',q:'dnUMo6pziMs'},
{title:'Ukrainischer Journalist ruft im ukrain.TV zum Mord an Ostukrainern auf',q:'94WlwxYX2tE'},
{title:'Ukrainischer Politiker - Donbass zurückerobern oder unbewohnbar machen',q:'uyG2BL4iKFo'},
{title:'Ukrainischer Putschist Jazenjuk rechtfertigt sein Regime im Deutschen Fernsehen',q:'q57SQYwcmhs'},
{title:'Ukrainische TV Show - Ex-General beschreibt die Lage schonungslos',q:'d9RjpDXLJbk'},
{title:'Unbezahlte deutsche Kriegsschulden gegenüber Griechenland',q:'2GLq2R5h2jI'},
{title:'Unfassbare Kriegsverbrechen des Westens - Jürgen Todenhöfer _ Peter Scholl-Latour u.a.',q:'J2O7LSFLu0M'},
{title:'Unmenschliche Politik - Festung Europa',q:'ybVb32haKj8'},
{title:'UN session on Minsk2 - Russian TV',q:'PJB1ZsoQ0r4'},
{title:'Unterbringung von Flüchtlingen - Lösungsmodelle',q:'2LW6h2sTFTc'},
{title:'Unterstützung der ISIS über die Türkei - Deutsche Welle',q:'hTS2NkLcQD8'},
{title:'Uranium & Phoshor weapons led to cancer rise in Gaza - 21.4.13',q:'7GvfqXpOEcY'},
{title:'Uranmunition im Irak -  Reaktionen auf den Weltspiegel-Bericht',q:'C9HTKGQRXYg'},
{title:'Uranmunition und DU in Kriegswaffen - Edmund Lengfelder',q:'ggM6pGjanPc'},
{title:'USA &  EU unterstützen Nazis in der Ukraine',q:'O0Rw3jHLsv4'},
{title:'USA führen weltweit Kriege - weitere in Vorbereitung 14.7.14',q:'y62wAR-I330'},
{title:'USA ll Addicted to War ll Süchtig nach Krieg ll Irak Irak Irak Irak Syrien',q:'flBRhSF_wNU'},
{title:'USA okkupieren die Erde mit US Militärbasen',q:'kKHShIYTY1Y'},
{title:'US-Außenministerin  500000 Tote Kinder waren den Preis wert!!! 12.12.14',q:'8pkSOSxUHws'},
{title:'US-Congressma Grayson - Obama’s draft Authorization for the Use of Military Force against ISIS',q:'ZKHLifE3P7E'},
{title:'US Drohnen töten von Deutschland aus',q:'dVebhC6i9lw'},
{title:'US-General a.D. John M. Keane - Russland- u. China-Politik der USA',q:'4xMjGZbKU6s'},
{title:'U.S. Intelligence knew in 2012 - Rise of ISIS, Arms shipments from Libya to Syria',q:'tgSnEBqx97k'},
{title:'US-Kongressabgeordnete Gabbard - USA in illegalen Krieg gegen Syriens Regierung verwickelt',q:'Ppr7AsQm4Xw'},
{title:'US-Kriegsverbrechen Falluja Teil 1 _ Verbotene Nuklear u. Chemiekampfstoffe',q:'Ys8cusvlMHI'},
{title:'US-Kriegsverbrechen Falluja Teil 2 _ Verbotene Nuklear u. Chemiekampfstoffe',q:'RU5JDziBKn0'},
{title:'US-Kriegsverbrechen Falluja Teil 3 _ Verbotene Nuklear u. Chemiekampfstoffe',q:'d09WXBtu59s'},
{title:'US-Militärfilm belegt Biowaffen-Tests an der eigenen Bevölkerung',q:'OsMgT0OShVc'},
{title:'US-Militär im der Ukraine - Immer aggressivere Unterstützung',q:'2dEuipnEaDc'},
{title:'US-Politik der Vorherrschaft und die Folgen - Prof. Dr. Massarrat l antikriegTV',q:'js8AqZDgYuE'},
{title:'US-Politiker amüsieren sich über Krieg und Mord',q:'CaMqD2j_iXc'},
{title:'US-Politiker Paul zu Syrien - ISIS und Al-Qaida von USA geschaffen u. unterstützt',q:'xZDidZnqM5Q'},
{title:'US-Politiker Ron Paul - Paris und was getan werden sollte',q:'MUFjNDzGvBE'},
{title:'US Propaganda in der Ukraine und in Geogien - Ein Vergleich',q:'tWxSpYbfBR4'},
{title:'US-Senator McCain und die Terrorgruppe ISIS ll Hintergründe ll 28.9.14 (antikriegTV)',q:'w4RyJFPIKcs'},
{title:'US-Strategie gegen Russland l George Friedman STRATFOR @ Chicago Council on Global Affairs',q:'o060JXXVQ4U'},
{title:'US-Täuschungspolitik im Kalten Krieg gegen Russsland',q:'0gqVIMADrRI'},
{title:'US-Wahlkampf - Koch Brothers Milliarden für Republikaner',q:'DGOSWLlhzaQ'},
{title:'Verdacht auf Giftgaseinsatz durch syrische Rebellen 06 05 13',q:'p5cH9NAPX5A'},
{title:'Verfahrener NSU-Prozess und die Medien ZAPP',q:'R_G828Tdyl4'},
{title:'Verfassung aushebeln - Helmut Schmidt + Wolfgang Schäuble',q:'7YLUbudQfdw'},
{title:'Vergleich der Machtverhältnisse - USA und China',q:'mnd5chpIMlw'},
{title:'Verhaftungswelle in der Türkei - Einschüchterung der Protestbewegung',q:'ao6yNIKQotU'},
{title:'Verhör eines gefangenen ukrainischen Sodaten',q:'hxoXeSmHH8Q'},
{title:'Vermögenspyramide (english) (antikriegTV Kanal2)',q:'TrkalrZineI'},
{title:'Versäumte Chancen in Partnerschaft EU-Russland - Ehem. Generalsekretär d. Europarates, W. Schwimmer',q:'1cVcbAaACEg'},
{title:'V-Leute und mögliche Straftaten - Hans-Christian Ströbele, MdB B90_Grüne',q:'ky87C8_u6ec'},
{title:'Volker Pispers - Antirussische Propaganda der USA',q:'jFDc83_9434'},
{title:'Volker Pispers ll USA im Endstadium des Kapitalismus ll 2014',q:'_xDSNyOimjg'},
{title:'Volker Pispers - Skrupelloser Weltpolizist USA - 9_11 und Terrorismus',q:'L6aNXjYHV50'},
{title:'Volker Pispers - Über Russen, Iraner und US-Amerikaner',q:'3zqzYrnlnXs'},
{title:'Volker Pispers - Verschwoerung am Fruehstueckstisch (antikriegTV)',q:'aikYu8GSYlo'},
{title:'Völkerrechtsbruch Kosovo als Blaupause für die Krim -Altkanzler Schröder',q:'rFy5ZBvUC-0'},
{title:'Von Boko Haram entführt l Schülerin aus Nigeria macht Aussage beim Menschenrechtsgipfel in Genf',q:'a9PAhjlfKpQ'},
{title:'Von den USA und der EU versuchte Putsch Nr.2 in der Ukraine',q:'Dr3I5NTSF3s'},
{title:'Vorbild Island Ausweg aus der Krise (22.08.2012)',q:'mLsh0a_WWgE'},
{title:'Vortrag Renate Bastian - Kriegsgefangene, Zwangsarbeiterinnen, deutsche Deserteure (1939-1945)',q:'rawt9rgIG0c'},
{title:'Waffenexporte und Nachrichten . Deutschland 12.12.12',q:'6lNSkGgpz9M'},
{title:'Wagenknecht - Klartext zu Griechenland',q:'qYIHIp0xJMI'},
{title:'Wahrheiten hinter der Politik - Lisa Fitz - antikriegTV2',q:'fAzrtlozqZA'},
{title:'Wahrheit über ISIS, USA, Taliban, 11.September, Russland, Ukraine.',q:'J6Q_fxenrIw'},
{title:'Walther Stützle (SPD) - Wir sind möglicherweise am Vorabend eines großes Krieges',q:'EPQpcNRw5VM'},
{title:'Warcrimes Iraq - Depleted Uranium du weapons - 21.4.13',q:'UlTYgqhxUdY'},
{title:'Warnung - Nach dem Dritten Reich droht jetzt das Vierte Reich',q:'JxDoI-Pzjcs'},
{title:'Warnung vor dem globalen Handelsabkommen „TTIP“',q:'QxMIyVJOqrA'},
{title:'Was geschah wirklich in Libyen Für was stand Gaddafi',q:'7zbDLaSEN-c'},
{title:'Was westliche Politik im Orient anrichtet - Michael Lüders, Nahostexperte (antikriegTV)',q:'Xc1S4sUql7w'},
{title:'WDR 2 Klartext zu Obamas Berlin-Besuch - Politik der Lüge',q:'2O0c53r5xK0'},
{title:'WDR  - Dirk Müller, die verarschte Bevölkerung (antikriegTV Kanal2)',q:'NDn1mHSiNsM'},
{title:'WDR  Ukrainisches Militär terrorisiert die Zivilbevölkerung - Europa mitveranwortlich!',q:'LEH3j8kol8E'},
{title:'Weltflüchtlingstag 2015 Refugees Welcome - Flucht ist kein Verbrechen  Berlin 20.6.',q:'fKXgo_Vau_A'},
{title:'Weltspiegel Ecuador - Die schmutzigen Hände von Chevron - Umweltverschmutzung im Regenwald',q:'NsLKhtovAyo'},
{title:'++ Weltweiter Protest gegen Monsanto ++ 25. Mai ++',q:'lyHDGda0irs'},
{title:'Wem gehört das Geld - Der Andere Neue Fabian',q:'tKqUi04YIho'},
{title:'Wer hat das Dorf Sartana (Ostukraine) beschossen',q:'DL-wI68KEwM'},
{title:'Wer hat den Umsturz in der Ukraine gefördert und bejubelt Rückblick',q:'xtYvWSAEMoA'},
{title:'Westen kontrollierte Ost-Post - Souveränität Deutschlands 20.11.2012',q:'or3tzI-JvyU'},
{title:'Westliche Propaganda - totale Manipulation ist möglich - Nachdenkseiten',q:'Dn5a49_6ch0'},
{title:'Westliche Strategie der Einkreisung Russlands',q:'nAEdV1BkkjE'},
{title:'Wie Banken die Regulierung umgehen - Die miesen Tricks der Finanzaristokratie',q:'5iQAiKW0wEU'},
{title:'Wie konnte die NSA der mächtigste US-Geheimdienst werden - mit James Bamford • BRAVE NEW FILMS',q:'ARZYnq02Syo'},
{title:'Wie und warum die USA Kriege anheizen',q:'f6drI_h0XFk'},
{title:'Wieviel totale Überwachung ist möglich',q:'1h8SxsrP0cw'},
{title:'Wikileaks Enthüllungen - Uranmunition im Irak - antikriegTV2',q:'mizQGNqKZrU'},
{title:'William Blum - USA wollen Weltherrschaft seit 200 Jahren',q:'7kWznShQ0Lw'},
{title:'Willy Wimmer (CDU) - Der Konflikt im Yemen - iran. Rundfunk',q:'9GK2jqc5g_A'},
{title:'Willy Wimmer (CDU) - Geopolitik und Wiederkehr der Hasardeure',q:'6dNmQrNBN5w'},
{title:'Willy Wimmer (CDU) - Lausanner Abkommen Iran und G5+1 - iran. Rundfunk',q:'HDII61ggAdg'},
{title:'Wirtschaftslobbyisten machen Politik und schreiben Gesetze',q:'Dg2C6DdTaOM'},
{title:'Wirtschafts-Refugees Welcome - Willkommenskultur fürs Kapital - Die Anstalt Sept. 2015',q:'ieeTSE4rh6g'},
{title:'Wirtschaftsspionage der USA - Geheimdienst-Experte Schmidt-Eenboom',q:'4PFlTHFcXlE'},
{title:'Wladimir Putin über die USA und andere Feinde des Weltfriedens',q:'9ickBGWJRKw'},
{title:'Wladimir Putin - Wir akzeptieren keine Weltordnung Made in USA',q:'kaoXYqVjr2w'},
{title:'Wolfgang Hetzer -  Finanzkrise 2008 (antikriegTV)',q:'nQVSLlboLUY'},
{title:'World Wealth Report 2012',q:'cdA853pm7l0'},
{title:'yarmouk',q:'bmcw7YPXTGc'},
{title:'ZAPP Magazin gegen Russia Today 13.11.14',q:'cvX9DGi9l2E'},
{title:'Zbigniew Brzezinski - USA befeuern weltweit Konflike',q:'W-yo6eihwLA'},
{title:'ZDF - Das Deutsch Russische Verhältnis',q:'5It9C8mtHy8'},
{title:'ZDF Die Anstalt Anticapitalista 1.1.14',q:'XQ-a0ih0Nn8'},
{title:'ZDF Die Anstalt - Drohnenkrieg ist Frieden 2.2.15',q:'vTCyzs1S16k'},
{title:'ZDF Die Anstalt - Freihandelsabkommen 4.2.15',q:'PrWFprp-eMo'},
{title:'ZDF Die Anstalt - Medien & Meinungsmathematik 2.2.15',q:'q2euIizoGa4'},
{title:'ZDF erklärt Griechenland-Folter - Neues aus der Anstalt',q:'fayj-dlc2rk'},
{title:'ZDF - Hacker beweisen - Türkei liefert Waffen an Islamisten in Syrien!',q:'NFd7JuKNYAo'},
{title:'ZDF heute journal   Datenschützer fordern mehr Transparenz 27 06 2013',q:'sHIORmepoig'},
{title:'ZDF Heute-Show vs. RT-Deutsch - Kostenlose Werbung',q:'1cwDrmi9bIg'},
{title:'ZDF heute  Überwachung   Datenskandal weitet sich aus   01 07 2013',q:'bSHmKv8E-_Y'},
{title:'ZDF macht Russland für MH17 Abschuss verantwortlich  10.9.14',q:'RlhX_9MgcUU'},
{title:'ZDF über Seitensprünge von Sarkozy & Merkel - Neues aus der Anstalt',q:'gW9fb3Ud5s4'},
{title:'ZDF - Ukrainischer Präsident attackiert Russland im deutschen Fernsehen',q:'W5eY8hgwM4M'},
{title:'ZDF - USA finanzierten Putsch in Ukraine - Neues in der Anstalt',q:'T9CXm598q4k'},
{title:'ZDF verharmlost ukrainische Neonazis als politische Hardliner 10.9.14',q:'0VvUQHS1bJQ'},
{title:'Zugriff im Tunnel - Das tödliches Drama von Bad Kleinen',q:'_B2eiC5pWTA'},
{title:'Zugriff im Tunnel - Das tödliches Drama von Bad Kleinen (Kurzversion)',q:'9m6V9sS6VEM'},
{title:'Zur Außenpolitik der Russischen Föderation Fragen an Botschafter Wladimir M. Grinin, Berlin',q:'J9uha25WNNc'},
{title:'Геополитика - Планы по расчленению России в 1914 и 2014',q:'H4rjqHddbUE'},
{title:'ヒットラーの米国ビジネスパートナー --- 極秘 - Hitlers business partners from the U.S.',q:'6-fv28NOMcA'}
    ];


  $scope.accounts = [
    {
      url: 'http://tutorialzine.com/2013/07/50-must-have-plugins-for-extending-twitter-bootstrap/',
      title: '50 Must-have plugins for extending Twitter Bootstrap',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/07/featured_4-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/08/simple-registration-system-php-mysql/',
      title: 'Making a Super Simple Registration System With PHP and MySQL',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/08/simple_registration_system-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/08/slideout-footer-css/',
      title: 'Create a slide-out footer with this neat z-index trick',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/08/slide-out-footer-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/06/digital-clock/',
      title: 'How to Make a Digital Clock with jQuery and CSS3',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/06/digital_clock-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/05/diagonal-fade-gallery/',
      title: 'Smooth Diagonal Fade Gallery with CSS3 Transitions',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/05/featured-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/05/mini-ajax-file-upload-form/',
      title: 'Mini AJAX File Upload Form',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/05/ajax-file-upload-form-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/04/services-chooser-backbone-js/',
      title: 'Your First Backbone.js App – Service Chooser',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/04/service_chooser_form-100x100.jpg'
    }
  ];



  $scope.news = [
    {
      url: 'http://tutorialzine.com/2013/07/50-must-have-plugins-for-extending-twitter-bootstrap/',
      title: '50 Must-have plugins for extending Twitter Bootstrap',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/07/featured_4-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/08/simple-registration-system-php-mysql/',
      title: 'Making a Super Simple Registration System With PHP and MySQL',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/08/simple_registration_system-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/08/slideout-footer-css/',
      title: 'Create a slide-out footer with this neat z-index trick',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/08/slide-out-footer-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/06/digital-clock/',
      title: 'How to Make a Digital Clock with jQuery and CSS3',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/06/digital_clock-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/05/diagonal-fade-gallery/',
      title: 'Smooth Diagonal Fade Gallery with CSS3 Transitions',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/05/featured-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/05/mini-ajax-file-upload-form/',
      title: 'Mini AJAX File Upload Form',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/05/ajax-file-upload-form-100x100.jpg'
    },
    {
      url: 'http://tutorialzine.com/2013/04/services-chooser-backbone-js/',
      title: 'Your First Backbone.js App – Service Chooser',
      image: 'http://cdn.tutorialzine.com/wp-content/uploads/2013/04/service_chooser_form-100x100.jpg'
    }
  ];



}
